### ISSUE TITLE
Sparql GET Method Query endpoint

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1021]
A new method/ endpoint is available in v1.3 to make a sparql query 

It's debatable whether this new way needs to be covered by the SDK or not

**Comment by samuel-kerrien** [comment]
Unsure if that makes sense to support GET in the JS SDK. It offers the same functionality as POST but has the potential drawback to have a URL length limitation. Might be worth checking with @bogdanromanx but I think it might not always be enabled by default while POST would.

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by umbreak** [comment]
I would not add it either. Stick to POST.

Even though there is a maximum URL length defined in the RFC, each implementation is doing whatever it wants, from the browsers to ech proxy to our server. So it isn't safe to rely on any of those values. 

We had a previous truncation of authentication redirect on one of our proxy's, for example. That was a pain to figure out and to fix.
