### ISSUE TITLE
Use given_name instead of name for user login label

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1025]
For some people, the name field provided by the OIDC provider is duplicitous. To fix that we can either show the `preferred_username` which will display their internet handle, or `given_name` which should also be sufficient.

**Comment by umbreak** [comment]
In my case `given_name` Is `Didac Montero` which seems kind of accurate.

**Comment by kenjinp** [comment]
but mine would just be `Kenneth` which is okay... I think maybe we should use the `preferred_username` instead, which is how you ask the auth service to call you.
