### ISSUE TITLE
Result Plugin for Studio

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1029]
It would be useful to have different `ResultViews` for Studio. For example, instead of displaying a table, to display a bar chart or graph view.

- [x] Review and implement table UX/UI https://github.com/BlueBrain/nexus/issues/1127 
- [ ] Review the UX flow (from query or tabular file to table view or plot)
- [ ] Design and implement the flow

**Comment by adulbrich** [comment]
Proposed journey (draft):
1) User adds a new element in the studio
2) User can either upload a tabular file, such as csv, txt, tsv, or write a SPRQL query
3) --- Editor phase: either SPARQL editor/load query/etc. or file import flow (to be defined)
4) Data is displayed in table, or user can choose to configure a visualization (plot)

**Comment by adulbrich** [comment]
Parked for now
