### ISSUE TITLE
Improve plugin not found error

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1085]
I feel like this can be improved somehow

![Screenshot 2020-03-10 at 14 49 52](https://user-images.githubusercontent.com/5485824/76318803-8b723180-62de-11ea-9b8a-65e29305c935.png)

**Comment by adulbrich** [comment]
I propose wrapping the following inside the collapsible box?
1) Show a message saying "The <plugin-name> plugin could not be loaded, see details."
2) Show the error message.

In addition, I suggest managing known errors in the plugin itself?
