### ISSUE TITLE
Image in Resource does not Update

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1097]
1) Access list of file with images: https://bbp.epfl.ch/nexus/web/bbp/somatosensorycortex?shareList=JTdCJTIybmFtZSUyMiUzQSUyMkpQRyUyMiUyQyUyMnZpZXclMjIlM0ElMjJueHYlM0FkZWZhdWx0RWxhc3RpY1NlYXJjaEluZGV4JTIyJTJDJTIyaWQlMjIlM0ElMjJjZjE0MTVhMS1jNDVkLTQyOTgtYTM2Yy04YjY4ODI4MmE4ZWUlMjIlMkMlMjJxdWVyeSUyMiUzQSU3QiUyMnNpemUlMjIlM0ExMDAlMkMlMjJkZXByZWNhdGVkJTIyJTNBZmFsc2UlMkMlMjJxJTIyJTNBJTIyanBnJTIyJTdEJTdE
2) Click on resource, you see an image of a cell
3) Navigate to Links and Click on another resource
4) The image will stay but the rest of the resource will change

Reported by @annakristinkaufmann

**Comment by kenjinp** [comment]
This image preview component should be removed from he metadata ticket, and should be done with this task: https://github.com/BlueBrain/nexus/issues/1099.

The image preview plugin should be careful not to have this issue https://github.com/BlueBrain/nexus/issues/1105
