### ISSUE TITLE
Full text search not working if the start is not correct (even with *)

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#110]
From nexus-kg created by [antonelepfl](https://github.com/antonelepfl) : BlueBrain/nexus-kg#281  

I'm trying to full search by part of the entity name.

BASE = https://nexus-int.humanbrainproject.org/v0/data/brainsimulation/simulation/memodel/v0.1.1
We have an entity
BASE/a27fdf49-1798-4b76-99d5-4cf8afe3c31b

This entity has the **name** attribute `CA1_int_cAC_031031AM1_20180201104443`

If I query:
`BASE?q=CA1_int_cAC_031031AM1_20180201104443` -> Works
`BASE?q=*CA1_int_cAC_031031AM1_20180201104443*` -> Works
`BASE?q=*CA1_int_cAC_031031AM1*` -> Works
`BASE?q=*031031AM1_20180201104443*` -> NOT Working (I removed some part from the beginning)

**Comment by bogdanromanx** [comment]
Unless critical, we don't plan on fixing v0 issues. With v1 I would argue that this is no longer an issue as a client can target specifically the elastic search index. The issue was caused by the limited full text search support in BlazeGraph.
@pgetta does that seem reasonable to you?

**Comment by pgetta** [comment]
Great, that works for me, thank you @bogdanromanx!

**Comment by umbreak** [comment]
We are switching to ElasticSearch to perform full text search. Not relevant
