### ISSUE TITLE
"Data Access" Plugin

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1101]
Estimate: 4 sp

- [ ] Expanded by default, default plugin.
- [ ] List all files available in entity in the form of a table.
- [ ] If the file is a nexus address, the user can download it. If the file is a GPFS path, the user can copy the path. 
- [ ] What happens when no file present? Should be display the plugins or not? Should we display a message to the user?
- [ ] Remove current file download buttons in plugins (not metadata)

Please look at screenshot below for layout:
![image](https://user-images.githubusercontent.com/11705901/76625151-ef8f3280-6536-11ea-932f-1999d7a83a98.png)

See https://bbpteam.epfl.ch/project/issues/browse/SSCXDIS-219?src=confmacro for more details.

**Comment by samuel-kerrien** [comment]
A few other points to consider:
- Human readable file size would be a useful addition in this table.
- Do we want to show mime type ? There could be different file type associated to the same entity type (ephys: igor, nwb)
- Downloading from GPFS might also be considered.
- Generally, we might have to cap download based on a maximum file size.
