### ISSUE TITLE
MINDs "Metadata" Plugin

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1102]
Estimate: 4 sp

- [x] Develop new "Metadata" plugin, always displayed for type entity, and expanded by default
- [x] If not MINDs metadata available, display message to user, encouraging him or her to add the information
- [ ] Information to display is available in screenshot below or in [Jira ticket](https://bbpteam.epfl.ch/project/issues/browse/SSCXDIS-223?src=confmacro), developer is encouraged to first adapt design in Adobe XD.

![image](https://user-images.githubusercontent.com/11705901/76625658-0aae7200-6538-11ea-8b33-8155f0e2fcf4.png)

See https://bbpteam.epfl.ch/project/issues/browse/SSCXDIS-223?src=confmacro for more details.

**Comment by adulbrich** [comment]
@kenjinp update from @MFSY 

- [ ] the metadata to be more ordered. How about spliting it in two tables nicely aligned and one next to the other (i.e horizontal alignement).
- [ ] The missing values to be left empty instead of 'No ...'

**Comment by adulbrich** [comment]
@MFSY could you maybe provide a small drawing of the table and order of the fields?

**Comment by adulbrich** [comment]
Additional ideas:
- [ ] the link to the license is nice, have the same behavior for other fields (transform text to link to the information)
- [ ] do we have the specific license name in addition to the link?

Note that in the future we might re-think the nested classification depending on the data (e.g. Allen Institute classification).

**Comment by adulbrich** [comment]
![Plugin - MINDS (default expanded) v1](https://user-images.githubusercontent.com/11705901/77909461-ac9ac200-728d-11ea-981b-6d5f07ff90c9.png)

**Comment by adulbrich** [comment]
![Plugin - MINDS (default expanded) v1 two-columns](https://user-images.githubusercontent.com/11705901/77912237-7a3f9380-7292-11ea-8eff-20dc1aac072f.png)

**Comment by samuel-kerrien** [comment]
This plugin is rather specific about the metadata is shows, shouldn't the name shown in the top of the panel be too ? Like "MINDS Metadata" ...

**Comment by adulbrich** [comment]
@samuel-kerrien it was decided together with françois to use the name Metadata

@MFSY do you like better the one or two-columns design (see above comments) + are you OK with using the dash - to indicate missing value?
