### ISSUE TITLE
Improved Neuron Morphology Plugin - Soma

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1104]
Estimate: 1 sp

- [ ] User can toggle the soma.

**Comment by adulbrich** [comment]
Is the soma on by default?

**Comment by kenjinp** [comment]
It is, and the geometric view is enabled by default (will be slower, though...)

right now, there's no way to show the soma in the poly-line view. We'll have to make some clever additions to the library to draw a circle in the center of mass where it should be or something.
