### ISSUE TITLE
No Plugins Configured Warning - Resource View

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1123]
Estimate: 0.5 SP

If you don't have admin access to a project, and there are no plugins configured to visualize that resource, the resource view will simply be empty. That's pretty ugly, so we should figure out a nice warning in that case, or maybe a default table view to show properties.

**Comment by adulbrich** [comment]
Display message telling user to contact the resource creator for more information if nothing is displayed

**Comment by adulbrich** [comment]
Show the JSON in a long table, be careful with nested information.
On top, show the following message: "There are no plugin configured for this resource, and you don't have admin access. Please ask the resource creator for more information."
