### ISSUE TITLE
Redirect after login after trying to access a resource does not work (production)

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1126]
### Example (only happens in production)

Estimate: 1 SP

1) Open new incognito tab
2) Access a resource, e.g. https://bbp.epfl.ch/nexus/web/demo/ephys-demo/studios/https%3A%2F%2Fbbp.epfl.ch%2Fnexus%2Fv1%2Fresources%2Fdemo%2Fephys-demo%2F_%2Fb88744a8-a414-45ce-a787-a91eb1446789
3) You should see a login prompt
4) Login, you should access the resource, instead, you have an error:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/11705901/77637241-a509af00-6f55-11ea-94de-844b162584d9.png">

**Comment by adulbrich** [comment]
This link does not ask the user to login when accessing the resource though https://bbp.epfl.ch/nexus/web/demo/ephys-demo/studios/https%3A%2F%2Fbbp.epfl.ch%2Fnexus%2Fv1%2Fresources%2Fdemo%2Fephys-demo%2F_%2Fb88744a8-a414-45ce-a787-a91eb1446789

**Comment by adulbrich** [comment]
Today, Rajnish tried to access the LNMC portal not being logged in, and he was not redirected (production). https://bbp.epfl.ch/nexus/web/bbp/lnmce/studios/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fa8e1527a-86d4-41a2-b5f2-34d4732a3d94?workspaceId=https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fc31e01be-677d-423b-bfa3-aa805ddd9a68

**Comment by dhaneshnm** [comment]
Pending deployment, code is merged in this PR : https://github.com/BlueBrain/nexus-web/pull/618
