### ISSUE TITLE
Studio support for ES views

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1169]
Currently, users have performance issues because of the load on BlazeGraph. We need to support ES instead in order to increase speed and reliability.

See the requirements in the comments.

Implementation: https://github.com/BlueBrain/nexus/issues/1798

Acceptance test:
- [x] a user can take the search results from the Search sub-app and create a Studio dashboard from it

**Comment by kenjinp** [comment]
We'll discontinue feature updates to the studio feature for the time being

**Comment by adulbrich** [comment]
Meeting summary:

## Migration:
* continue supporting and editing SPARQL dashboards
* disable SPARQL dahsboards creation
* allow ES view dashboard creation
* name a view (backend)
> Announce change on roadmap and different users.
> Help them migrate large studios.

## Incremental dev:
1. support basic ES view and display
2. support multiple ES views (composite views)
3. build composite views (e.g. sparql test and sample results, then mapping)
4. search the graph
5. build index for the studios
6. should we build a different index for each table? bogdan says not a good idea, better to consume variations of the same index?

**Comment by samuel-kerrien** [comment]
After discussion with @slhill in our demo today, we have decided to maintain the support of SPARQL data source and add an additional Elasticsearch source support.
