### ISSUE TITLE
Data Access Plugin: add url in addition to contentUrl

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1185]
- [x] Add url in addition to contentUrl
- [x] Currently, when clicking Copy URI, “undefined” is copied to clipboard.
- [x] Check with Anna: map this plugin when there is a distribution, not on entity

Example from Anna:

> An example with two distribution objects out of which one contains a url instead of a contentUrl property: https://bbp.epfl.ch/nexus/web/bbp/neocortex/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fd70203af-71a3-48f0-b926-dbb96020f32c

**Comment by Stafeeva** [comment]
#### Comment from Anna:

Yes, it would be super nice if the Nexus Data Access plugin was triggered just by the presence of a distribution property on the JSON payload without depending on a particular @type.
