### ISSUE TITLE
Web crashed when clicking on the Resource

### ISSUE THREAD

**Issue by yiiifan** [BlueBrain/nexus#1188]
I'm testing some features on the Nexus Sandbox. And I got a blank page when I try to click on the resource I just created. Here is the context of the bug:

Firstly I upload a simple CSV file to diskStorageDefault. The generated identifier is https://sandbox.bluebrainnexus.io/v1/resources/kg/test/_/7d55edde-1a58-4921-836c-b786a32d4ee8

Secondly, I create a schema called `test:file` with the following SHACL:
```
{
    "@context": {
        "this": "https://sandbox.bluebrainnexus.io/v1/schemas/kg/test/kkk/shapes",
        "ex": "http://example.com/"
    },
    "shapes": [
        {
            "@id": "this:MyShape",
            "@type": "sh:NodeShape",
            "nodeKind": "sh:BlankNodeOrIRI",
            "targetClass": "ex:File",
            "property": [
                {
                    "path": "ex:name",
                    "datatype": "xsd:string",
                    "minCount": 1,
                    "maxCount": 1
                },
                {
                    "path": "ex:binary",
                    "nodeKind": "sh:IRI"
                }
            ]
        }
    ]
}
```
Then I create a data Resource against this schema:
```
{
    "@context": {
        "ex": "http://example.com/"    
    },
    "@id": "base:testfile-4",
    "@type": "ex:File",
    "ex:name": "file1",
    "ex:binary": {"@id": "base:7d55edde-1a58-4921-836c-b786a32d4ee8"}
}
```
The resource is created successfully. But when I click on the resource on the default query panel, the whole page go blank and I got error message as follow:
![截屏2020-05-26 下午2 31 17](https://user-images.githubusercontent.com/17526810/82937188-bb37e980-9f5d-11ea-8db9-e6039feed0e9.png)

**Comment by dhaneshnm** [comment]
@yiiifan  We have fixed the issue in this PR https://github.com/BlueBrain/nexus-web/pull/634. This will be available with next minor release of the nexus-web. Mean while you can get around this issue by having  mime-type and size properties in you file resource.
