### ISSUE TITLE
Resource resolution fails when specifying uuids in the schema and resource segments

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#1222]

**Comment by imsdu** [comment]
- assuming a resource constrained by a schema (other than unconstrained.json)
- if the schema is identified by a generated uuid
- if the resource is identified by a generated uuid
- when trying to fetch the resource using: /v1/resources/{org}/{proj}/{schema_uuid}/{resource_uuid} it returns 404
- when trying to fetch the resource using a wildcard for the schema: /v1/resources/{org}/{proj}/_/{resource_uuid} it returns the resource
- when trying to fetch the schema using its uuid: /v1/resources/{org}/{proj}/_/{schema_uuid} it returns the schema

And we expect exactly /v1/resources/{org}/{proj}/{schema_uuid}/{resource_uuid} == /v1/resources/{org}/{proj}/_/{resource_uuid}
