### ISSUE TITLE
Studio fails to load or is slow to load when large data present

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1259]
Example Studio:
https://bbp.epfl.ch/nexus/web/bbp/somatosensorycortex/studios/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fb20ccd38-3ffc-4cd4-8578-eca4f8ec9e71?dashboardId=https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fce59285c-8ea0-4ac1-a2c2-96894fd1c36d&workspaceId=https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F2918b3a4-a6f7-4cb3-8f3f-dfa960f38261

See slack #team-nise-frontend for video.

Could we solve it also by doing #1169 ?

**Comment by kenjinp** [comment]
We will explore alternate solutions after migration as a Subapp to Fusion, perhaps local caching.

**Comment by adulbrich** [comment]
Will be fixed by https://github.com/BlueBrain/nexus/issues/1169
Can we do local caching as a quick fix?
