### ISSUE TITLE
Happy Path: Simulation Chart

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1260]
part of #1226

Create a Project that replicates the simulation report chart from https://bbpteam.epfl.ch/project/spaces/display/NEX/Product+Requirements%3A+Project+Fusion

- [x] Happy Path 1: Update Status
- [x] Happy Path 2: Work Artifacts, Notebooks

**Comment by kenjinp** [comment]
Morphology Release Activity Page

![Annotation 2020-06-29 122308](https://user-images.githubusercontent.com/5485824/86021778-c46b1900-ba29-11ea-9e95-e324bdf40972.png)

**Comment by kenjinp** [comment]
Thalamus Region Project Board
![thalamus region](https://user-images.githubusercontent.com/5485824/86024169-f336be80-ba2c-11ea-9a2b-449abd9298f1.png)

**Comment by kenjinp** [comment]
Thalamus Region v1 mockup
![thalamus v1](https://user-images.githubusercontent.com/5485824/86025983-2da15b00-ba2f-11ea-853a-9d2ce55b8233.png)

**Comment by kenjinp** [comment]
Single Cells Path

![Single Cells](https://user-images.githubusercontent.com/5485824/86027392-ef0ca000-ba30-11ea-9ff9-44c91bd34caa.png)

**Comment by kenjinp** [comment]
Repair workflow (simplified as a single workflow notebook)
![repair workflow](https://user-images.githubusercontent.com/5485824/86105748-00e95400-bac0-11ea-81a3-e5a83d64969c.png)

- Some questions
- How do we mark items as inputs and outputs?
- Do we need to specify input and outputs before data it put in them, or do we flag datasets as inputs/output after they've been uploaded?

**Comment by adulbrich** [comment]
To start let's build the following workflow (included nested):
![image](https://user-images.githubusercontent.com/11705901/86236030-ab817580-bb99-11ea-839b-7b74890bc86b.png)

We can have 4 template choices at the project level: either the whole workflow, or each of the 3 main boxes (single cell models, circuit reconstruction, and simulations). Sean mentioned a fourth one but I don't know where it should live yet.

If you load a workflow, you will also end up with the corresponding sub-activities.
One activity displays the status (color-coded) and the list of sub-activities also with their status.

**Comment by kenjinp** [comment]
User reaches Fusion Home page
    User clicks on Studio app
    User reached Studio Index page (with list of personal and organisation projects)
    User clicks to create new project
    User fills in project name (Microcircruit blabla) and adds supervisor to project
    User reaches project/studio page
    User receives a prompt to instantiate a template
    User chooses the full template (with 3 steps)
    User sees the three new activities with status to do (not started)
    User sees the sub activities for activities 1 and 2, all with status to do
    User clicks on first activity 
    User reaches activity page, and see the three single cell models activities, with the list of sub-activities, all with status to do
    User opens the morphology release activity
    User changes the activity to in progress
    User comes back through nested navigation to the project view
    User sees that activity 1 is now in progress, with sub-activity morphology release also in progress

**Comment by kenjinp** [comment]
Happy Path (Work Artifacts, Notebooks)
User reaches Fusion Home page
User clicks on Studio app
User reached Studio Index page (with list of personal and organisation projects)
User clicks on Project (Microcircruit blabla)
User reaches project/studio page
User clicks on first activity (Single Cell Models)
User reaches the first activity page
User clicks on first sub-activity (Morphology Release)
User reaches the first sub-activity page
User clicks on repair activity
User reaches the Repair activity page
User sees the list of morphologies tagged as input (if any)
User sees a instantiated notebook (python script)
User clicks on the notebook and sees a preview
User can edit the notebook metadata (incl. git location)
User opens notebook in companion app (Open On Demand or Jupiter Hub)
User saves notebook and closes companion app
User sees new version had been stored in activity (and automatically pushed to git)

**Comment by kenjinp** [comment]
Check out the happy path 1 here: https://xd.adobe.com/view/f8c2a49c-130e-4a91-883e-380682d54467-ad91/screen/556a8ab6-ac8b-40a3-a238-2d887b065a68/1-Fusion-Home-Page

**Comment by Stafeeva** [comment]
Happy Path 2 https://xd.adobe.com/view/66eeca1e-49a4-4e1b-a0e3-3d0701e3d1aa-33bd/

**Comment by adulbrich** [comment]
Let's have two stable happy flows that we can put in slides and or pdf. We'll use that as base for dev work.

**Comment by adulbrich** [comment]
> Check out the happy path 1 here: https://xd.adobe.com/view/f8c2a49c-130e-4a91-883e-380682d54467-ad91/screen/556a8ab6-ac8b-40a3-a238-2d887b065a68/1-Fusion-Home-Page

Please update to latest (with corrections) so that we can show stakeholders! 👯‍♂️
