### ISSUE TITLE
Studio Migration

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1265]
Options
- Port entire functionality as a "Studio Widget" 
- Each studio becomes project, each workspace becomes an activity, each dashboard becomes its own widget
- Studio becomes an activity, with a workspace and dashboard as nested activities
- Keep it insides Admin "subapp"
- Studio Legacy subapp that lives aside Admin and Studio (v2)

**Comment by kenjinp** [comment]
We suggest following roadmap
- Create a Studio Legacy subapp that lives aside Admin and Studio (v2) that provides all the functionality
- At the point where Studio v2 functionality allows Studio Legacy usecase, we migrate Studio Legacy to studio v2
- Migration strategies (Studio Legacy as Widgets):
    Port entire functionality as a "Studio Widget"
    Each studio becomes project, each workspace becomes an activity, each dashboard becomes its own widget
    Studio becomes an activity, with a workspace and dashboard as nested activities

**Comment by adulbrich** [comment]
To be reviewed with NSE/DKE.
