### ISSUE TITLE
Wireframes: ACTI-001a

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1266]
part of #1247

Create an Activity with the following metadata

Metadata:

    Start Date
    Expected End Date
    Activity Name
    Activity Description (markdown?)
    Expected Deliverables
    Status (to do/in progress/blocked/done)

**Comment by kenjinp** [comment]
![act001a](https://user-images.githubusercontent.com/5485824/85700724-f2282900-b6dc-11ea-8f75-59df850ed07f.png)

**Comment by kenjinp** [comment]
@adulbrich Questions to validate:

- [ ] - How to show status, issue?
- [ ] - Will the user change the status, or is it automatic?
- [ ] - Should we set default status as awaiting action, or should we allow user to set it straight away?
- [ ]  - Should we show the status in the create form at all?

Status Icon: We've defined 3 stages of progress
- Todo, awaiting action
- In Progress
- Completed

**Comment by adulbrich** [comment]
- How to show status, issue?
- Will the user change the status, or is it automatic? _Manual action from the user for now. In the future, we can imagine linking the delivery of deliverables with a status change._
- Should we set default status as awaiting action, or should we allow user to set it straight away? _By default, todo/awaiting action is selected, but the user can change it right away._
- Should we show the status in the create form at all? _Yes for now, what would be the downside?_

**Comment by kenjinp** [comment]
I meant, how to show status. I kind of didn't like the traffic light, opted for github style icons (which we made ourselves!) . There was the word "issue" miscopied from somewhere

**Comment by adulbrich** [comment]
Should we have a status "blocked"?
