### ISSUE TITLE
Wireframes: Activity Small Preview Card

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1270]
As a user I want to visualize my activity in a small preview with important details there

part of #1247

**Comment by kenjinp** [comment]
![Activity Preview Card](https://user-images.githubusercontent.com/5485824/85732799-f44db000-b6fb-11ea-999f-23b2e3d4ddbb.png)

**Comment by kenjinp** [comment]
![Activity Preview Card](https://user-images.githubusercontent.com/5485824/85869752-67bef280-b7cc-11ea-90c4-e99994a5e42b.png)

Another version, this time with action icons inlined, and a nice tooltip

**Comment by adulbrich** [comment]
I like the comments and ability to "star" an activity.
I would remove the Jupyter icon for now, and leave the ability to open a notebook inside the activity, not on the card. 
Now that I think of it, I guess it would make sense to differentiate between work artifacts and code?
