### ISSUE TITLE
ACTI-003a

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1271]
As a user, I can manually add an existing work artifact to the activity, in order to make it visible to others in the project or activity. | 1 Must Have | 3 (existing) + 5 (sharing)

part of:  #1247

**Comment by kenjinp** [comment]
![Add Resource](https://user-images.githubusercontent.com/5485824/85720753-037b3080-b6f1-11ea-9802-1d0979ed212d.png)
![Search and add resouce 2](https://user-images.githubusercontent.com/5485824/85720755-0413c700-b6f1-11ea-8656-81ce91396370.png)
![resource on activity](https://user-images.githubusercontent.com/5485824/85720791-0bd36b80-b6f1-11ea-87b3-1253c8e4d353.png)

**Comment by adulbrich** [comment]
Please change the name of the app to Nexus Fusion and remove EPFL Blue Brain Project.
You can have a second frame showing this (as we would allow at one point the administrators to customize the logo of the app for their organization).

**Comment by adulbrich** [comment]
In addition, as discussed previously, we should have the list of work artifacts/datasets listed in the activity somewhere, like in a legacy Studio. And not have cards at first (to make it more constrained and straightforward).
