### ISSUE TITLE
Wireframes: Work Artifact Preview Card

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1279]
part of #1226

There should be a common card component for work artifacts

**Comment by kenjinp** [comment]
A couple of examples of work artifact, using a single card component that displays little previews

![Work Artifact Preview Card](https://user-images.githubusercontent.com/5485824/85869835-87561b00-b7cc-11ea-8811-92c530f191e2.png)

**Comment by adulbrich** [comment]
Could we split the canvas into:
- the canvas were people can move and see the activities
- an area for work artifacts (data)
- an area for code?
