### ISSUE TITLE
Wireframes: ACTI-004, ACTI-015

### ISSUE THREAD

**Issue by Stafeeva** [BlueBrain/nexus#1280]
Part of BlueBrain/nexus#1247

### ACTI-004
- As a user,
- I can get the instructions to link my work artifact programmatically in the activity
- In order to make it available and traceable in the project.

### ACTI-015
- As a user,
- I can get the work artifact programmatically from that activity
- In order to make use of it outside the software.

We have added a link to Jupyter Notebook:

![Screenshot 2020-06-26 at 15 00 04](https://user-images.githubusercontent.com/23080476/85859867-1f98d380-b7be-11ea-9743-4336d44074cd.png)

**Comment by kenjinp** [comment]
We'll add Nexus Forge code snippets to read all artifacts in this activity as well as a code snippet to push artifacts into this activity programmatically from the notebook

**Comment by adulbrich** [comment]
I would suggest having a separate work artifacts list with cards, not on canvas to start with.
Each work artifacts or a collection of selected work artifacts can be "exported" to Python code or to a new notebook.
Jupyter Notebook is one of many (albeit an important one) work artifact that can use other work artifacts.
