### ISSUE TITLE
Product Page Header

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1341]
part of https://github.com/BlueBrain/nexus/issues/989

0.5 sp

**Comment by Stafeeva** [comment]
![Screenshot 2020-07-29 at 14 53 58](https://user-images.githubusercontent.com/23080476/88803536-e41e6a00-d1ac-11ea-9693-7e8b7dd504f0.png)

![Screenshot 2020-07-29 at 14 54 17](https://user-images.githubusercontent.com/23080476/88803558-ebde0e80-d1ac-11ea-9850-e60dfa8cb18b.png)

**Comment by adulbrich** [comment]
Are you all happy with the icons I used in the design doc?
We should have consistent icons across the website. If you have better ideas, feel free to propose them.
