### ISSUE TITLE
Prevent multiple resolvers from having the same priority in the scope of a project

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1356]
In the case multiple `CrossProjectResolver` resources with the same `priority` value exists for the same project, the resolution of resources might not be deterministic, since the [ordering of resolvers is done just by priority](https://github.com/BlueBrain/nexus/blob/master/delta/src/main/scala/ch/epfl/bluebrain/nexus/kg/cache/ResolverCache.scala#L60).

That can be fixed having something like

```scala
  implicit private val ordering: Ordering[Resolver] = Ordering.by[Resolver, Int](_.priority).orElseBy(_.ref)
```

Ideally we would prefer it ordered by label, but we cannot access it easily at that level...so UUID would do the trick.

An alternative solution to the problem is to only allow creation of resolvers with different priorities within the scope of a project.

**Comment by pafonta** [comment]
Hello @umbreak,

Thank you for having documented this issue.

As a user, I would prefer the solution of "only allow creation of resolvers with different priorities within the scope of a project".

**Comment by bogdanromanx** [comment]
We will prevent the creation of resolvers with the same priority in the same project.

**Comment by umbreak** [comment]
When creating/updating a resolver, check for the previously existing resolvers priorities. If there is a resolver with the same priority, reject the request
