### ISSUE TITLE
Ephys plugin  (RAB) improvements

### ISSUE THREAD

**Issue by dhaneshnm** [BlueBrain/nexus#1379]
For the Ephys RAB plugin:
- [x] Add more than one unit for volt and amp (default should be mV and pA): can plotly-dash manage that by default?
- [ ] ~~Allow user to select a particular range~~.
- [x] There should always be a default selection (default: first stimuli, first repetition, all sweeps).
- [x] Indicate the number of available stimuli in parenthesis next to the Stimuli selector (e.g. "12 stimuli available").
- [x] Indicate the number of available repetitions in parenthesis next to the Repetition selector once a stimulus is selected.
- [x] Rename "Trace" to "Stimulus" for the first selection field.
- [x] Rename "Repitition" to "Repetition" for the second selection field
- [x] ~~Is it possible to measure the distance between two points on the plotly-dash plot?~~

For the Data Access plugin:
- [ ] User should not see the RAB file, only the NWB file.

**Comment by adulbrich** [comment]
@dhaneshnm just for my understanding: the new ephys/rab plugins will always use the new plotly-dash viz, independently of whether we have a RAB file available or not, and repetitions available or not?

**Comment by dhaneshnm** [comment]
No, current implementation uses plotly only when we RAB available. This can be changed though.

**Comment by dhaneshnm** [comment]
@adulbrich Can you elaborate on the need to measure the distance between two points in the graph? what is the use case?

**Comment by adulbrich** [comment]
> @adulbrich Can you elaborate on the need to measure the distance between two points in the graph? what is the use case?

We had a user (Darshan) asking for it (it's something he could benefit from for his postdoc: he has to measure the distance between peaks). I was wondering if we could have something like that out-of-the-box from plotly.

**Comment by dhaneshnm** [comment]
> > @adulbrich Can you elaborate on the need to measure the distance between two points in the graph? what is the use case?
> 
> We had a user (Darshan) asking for it (it's something he could benefit from for his postdoc: he has to measure the distance between peaks). I was wondering if we could have something like that out-of-the-box from plotly.

Plotly.js does not seem to support that out of the box. We can consider adding that capability ourselves.

**Comment by Stafeeva** [comment]
Regarding 'Allow user to select a particular range.': users can click on a graph and select a particular range to be zoomed in.
