### ISSUE TITLE
Everything in Fusion should update in real-time

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1395]
While editing an org (or project) description, after saving, the text does not update automatically. You have to switch context or force reload the page. Clicking on the sidebar admin does not refresh (but is that an issue? probably not).
![2020-08-07 09 32 40](https://user-images.githubusercontent.com/11705901/89621128-1b69d680-d891-11ea-9c7f-66c1d211b871.gif)

**Comment by adulbrich** [comment]
1. Enumerate where it fails, where we need it
2. Check with backend
3. Plan

**Comment by nicwells** [comment]
List of api methods to support new execution=performant|consistent flag for now (projects and composite views coming later):

Files - Create, link, update, tag, deprecate
Resources - Create, update, deprecate, tag
Projects - Create, update, deprecate
Views - Create, Update, tag, deprecate, restart indexing
Schemas - Create, Update, tag, deprecate
Storages - Create, Update, tag, deprecate

API will default to performant so we need to specify execution=consistent where we require it. Nexus SDK to be updated to support this parameter with it defaulting to execution=consistent.

**Comment by nicwells** [comment]
## Where updates aren't currently happening in real-time

- [x] Organizations (/admin) - organization does not update when description updated or is deprecated
- [ ] Project Admin (/admin/{org}/{project}) - newly created resources whether using 'Create Resource' or uploading a file does not update list of resources
- [ ] Workflow (/workflow/{org}/{project}) - newly created steps, tables, or datasets aren't displayed after creation.

anywhere else @adulbrich @dhaneshnm @smitfire ?
