### ISSUE TITLE
Cannot edit the JSON payload of a View

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#1407]
Steps to reproduce:

1. I uploaded a file in the project bbp > samuel
2. I open the entity: https://staging.nexus.ocp.bbp.epfl.ch/bbp/samuel/resources/https%3A%2F%2Fstaging.nexus.ocp.bbp.epfl.ch%2Fv1%2Fresources%2Fbbp%2Fsamuel%2F_%2F88f244ba-6a3b-4396-8b3c-47af2e36e07b
3. I added the following to the payload:
"http://schema.org/name": "studios diagram"
I got the following response:

![Screenshot 2020-08-11 at 10 18 21](https://user-images.githubusercontent.com/3679766/89874697-80d50480-dbbc-11ea-9ce3-45c9fe5c517f.png)

![Screenshot 2020-08-11 at 10 18 31](https://user-images.githubusercontent.com/3679766/89874723-87637c00-dbbc-11ea-9b1c-cd361e421f20.png)

I have tried the same thing on a view in bbp > nmc where I have also added a name and got the same error.

However, it works on a newly created entity.

Acceptance Criteria:
- Views can be modified and saved by a user with proper ACLs.
- An error message is displayed if the user tries to save the View and it does not comply with the expected schema. The error message refers to the docs with the right shape for the View.
- Rollback: Don't show a message in the resource view for File and View resources.

Out-of-scope:
- Files: to be addressed in https://github.com/BlueBrain/nexus/issues/2569

**Comment by samuel-kerrien** [comment]
More of a feature actually, I think File and Views have a closed schema so you cannot add a property like that.
If anything, the error message could just be improved, might be worth double checking what Delta is actually returning to see if we can provide a more helpful message.

**Comment by adulbrich** [comment]
Can we add a message for resource types that cannot be edited?

**Comment by adulbrich** [comment]
Instead of a message in the admin. We should display a proper error message if the user tries to save the modified payload instead of throwing an error. Or just disable the editing altogether for Files.

**Comment by bogdanromanx** [comment]
Proposed solution: make use of specific resource endpoints for creation, update, tagging and deprecation.

Scope: verify and ensure all resource types are handled in the same way (e.g. resolvers, schemas, storages etc.)
