### ISSUE TITLE
Event naming inconsistency

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1413]
Since the services have been merged, we have inconsistent naming for events:
- ProjectCreated
- ProjectUpdated
- AclCreated
- AclUpdated
- Created?
- Updated?

Probably it should be `ResourceCreated` and `ResourceUpdated`.

Note that introducing this would be a breaking change on the SSE.

**Comment by bogdanromanx** [comment]
Fixed in #1794.
