### ISSUE TITLE
links to deprecated objects

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#144]
_From @EnricoScanta on August 20, 2018 14:10_

I suggest that links to deprecated objects should also have a 'deprecate' mark. 

_Copied from original issue: BlueBrain/nexus-explorer#22_

**Comment by julienmachon** [comment]
Right now, we don't display the deprecated links by default. We need to add a toggle button

**Comment by julienmachon** [comment]
We should also use the new incoming/outgoing links API, as opposed to sparql query.

**Comment by julienmachon** [comment]
This have now been fixed
