### ISSUE TITLE
Incorrect remainingEvents when project events count is not up to date

### ISSUE THREAD

**Issue by wwajerowicz** [BlueBrain/nexus#1452]
When project event count is not up to date, `remainingEvents` count is negative. This happens because total project event counts offsets are not stored and a recalculated upon restart.

<img width="646" alt="Screenshot 2020-08-18 at 11 01 47" src="https://user-images.githubusercontent.com/1240210/90499734-34547080-e14a-11ea-9912-1c435bcd59f1.png">

**Comment by umbreak** [comment]
This should not be the case currently, since we store the project counts progress in the primary store.
