### ISSUE TITLE
Data model for Projects subapp

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1454]
## Questions
- [x] data model for projects and their characteristics
- [x] where do we store workflows projects
- [x] should each user have their own Nexus project

## Notes
- status of the project (based on activities?)
- number of activities
- number of work artifacts
- members of the project
- personal or organization
- name 
- description
- creation date
- target release date
- modified date
- close date
- history
- admin
- permissions
- ...

## Proposal

- One Nexus Organization per user
- As many Nexus Projects as Workspaces created by the users
- Input resources: link it from existing org/proj, if users edit them, then copy it to user's project
- Output resources: created in the user's project

> Quid storage? If linking or copying a resource to own project, the storage might be inaccessible to another user who doesn't have the rights.

**Comment by slhill** [comment]
We should largely keep the same structure as Nexus Delta already defines: Organization->Project. Each user may have permission to work in multiple projects. Within a project the user can create or (instantiate from a template) multiple Workspaces.

**Comment by dhaneshnm** [comment]
Back End is OK with this model and don't see any technical limitations.  Since internally, orgs are created on need basis ( by creating tickets), We will discuss with DKE to see if there is any administrative concerns.

**Comment by slhill** [comment]
Which model? I would like to review your plans as it doesn't make sense to me as written.

**Comment by bogdanromanx** [comment]
> There shouldn’t be a separate type of project for workspaces.

This is an interesting statement... what would this enable? Creating data boundaries in the same project (workspaces) would generate a burden on the frontend logic. Is there a specific reason why we would want workspaces to be colocated in a project?

**Comment by bogdanromanx** [comment]
Trying to rephrase the above: is there a reason why a workspace <-> project equivalence wouldn't suffice?

**Comment by slhill** [comment]
We would potentially have multiple workspaces per project.

**Comment by slhill** [comment]
I suggest we have a meeting to review the current assumptions and requirements.

**Comment by slhill** [comment]
We need to be absolutely clear about the user experience and requirements before discussing technical implementation and shaping the solution to fit current technical capabilities.

**Comment by dhaneshnm** [comment]
> Which model? I would like to review your plans as it doesn't make sense to me as written.

I was referring to the model described in the issue description. We will set up a meeting to discuss the concerns.

**Comment by dhaneshnm** [comment]
> We need to be absolutely clear about the user experience and requirements before discussing technical implementation and shaping the solution to fit current technical capabilities.
> […](#)
> Sent from my iPhone
> On Aug 20, 2020, at 09:16, Sean Hill ***@***.***> wrote: ﻿I suggest we have a meeting to review the current assumptions and requirements. Sent from my iPhone >> On Aug 20, 2020, at 09:15, Bogdan Roman ***@***.***> wrote: >> > ﻿ > This has implications on access control (limited to the level of projects) -> granting access to a single workspace would not be possible with the current design of Delta. > > There's also the matter of listing available workspaces, which in the case of project == workspace it would be a simple API call. In the case of multiple workspaces within a project, that would not be possible without iterating over all projects. > > The third implication is assigning data or metadata to a workspace; if ingestion happens with a tool outside the scope of Fusion, the resources would not be automatically "tagged" to "belong" to a certain workspace. > > I'm not arguing for or against, but rather just trying to see what are the implications of moving workspaces "one level down" over the proposed design. > > — > You are receiving this because you commented. > Reply to this email directly, view it on GitHub, or unsubscribe.

Apart from the items @bogdanromanx mentioned earlier, at this point we may want a flexible data model for fusion.  Data model for fusion will evolve, making changes in delta to accommodate our current needs may not be good in long term.  So our strategy should be to get to a stable data model (may be by v2) and then move some of the enabling features to Delta. Until then we should try and handle the user requirements at front end(application layer) as much as possible, with in the constraints of Delta.  
I understand that this will require a longer discussion, and we will set  up a meeting to review this like you suggested.

**Comment by adulbrich** [comment]
Here's a first draft.

### Activity

https://www.w3.org/TR/2013/REC-prov-dm-20130430/Overview.html#term-Activity

**Properties**

prov:generated (-> Entity)
https://www.w3.org/TR/prov-o/#generated 

prov:used (-> Entity)
https://www.w3.org/TR/prov-o/#used

prov:invalidated (-> Entity) when updating an existing entity?
https://www.w3.org/TR/prov-o/#invalidated

prov:wasInformedBy (-> Activity)
Communication is the exchange of an entity by two activities, one activity using the entity generated by the other.
https://www.w3.org/TR/prov-o/#wasInformedBy
> Good for same-level activities (relationship between two activities relying on each others, input->output)
> **What should we do for parent-child activity relationship?** Can we use isPartOf?

prov:qualifiedAssociation (-> Agent)
https://www.w3.org/TR/prov-o/#qualifiedAssociation

prov:wasAssociatedWith (-> Agent)
https://www.w3.org/TR/prov-o/#wasAssociatedWith

* SoftwareAgent: a software agent is running software. The type of a software agent is denoted by **prov:SoftwareAgent**.
* Organization: an organization is a social or legal institution such as a company, society, etc. The type of an organization agent is denoted by **prov:Organization**.
* Person: person agents are people. The type of a person agent is denoted by **prov:Person**.
