### ISSUE TITLE
Initalise new subapp called Projects

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1456]
Wireframes: https://docs.google.com/presentation/d/1dpNTR9rN9KCzRHEzXYHBdPwb4sh4u_3VaW1FClngokc/edit#slide=id.p

A new subapp called Workspaces becomes available in Fusion sidebar.

When clicked, users are brought to the Workspaces home page that will (see additional issues for those):
- list existing, open, personal workspaces/projects
- list existing, open, organization workspaces/projects
- let them create a new (personal) project
- find a hidden list of past (closed) or archived/deprecated workspaces
- cards for each workspaces in the list with key summary (status, dates, members, ... to be decided) and basic actions (edit, archive)
- search and sort the list of workspaces

**Comment by Stafeeva** [comment]
Implemented in BlueBrain/nexus-web#663
