### ISSUE TITLE
Upgrade sentry version

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1548]
https://docs.sentry.io/platforms/javascript

5 to 6 major revision update (library)

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/1548?planning-poker) with ZenHub @adulbrich @bogdanromanx @dhaneshnm @imsdu @nicwells @samuel-kerrien
