### ISSUE TITLE
Can't edit a resource even with proper access

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1551]
Sometimes you cannot edit a resource even with proper access, even though you can through the API

"I was trying to work in a project in production named users/akkaufma.
While I seem to have all the permissions required, I am not able to edit resources through Nexus Web (while I am able to edit them through e.g. Postman). Nexus Web shows a This resource cannot be edited message on top of the resource card"

**Comment by dhaneshnm** [comment]
Requested a meeting with Anna to investigate this further. Code analysis and trying to replicate the issue with user's ACL did not yield any result.

**Comment by dhaneshnm** [comment]
Unable to replicate. Closing thus unless we get a fresh report.
