### ISSUE TITLE
interactive project and step views canvas

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1567]
In the project and step views, users want to see and move step cards around.
This will allow users to see the relationships between different same level steps (input/output).

What's the best tech to achieve this?

Is there a better way to represent this relationship between steps? Columns instead of relationship thread?

What's the easiest to implement? We should go for easy in the MVP.

**Comment by Stafeeva** [comment]
https://github.com/BlueBrain/nexus-web/tree/Experimatal-project-canvas

Google Doc: https://docs.google.com/document/d/1_FtR0VCdZLy_gsJDnQt3VSKzX9gNQBvLHx2dv-KS1jM/edit

**Comment by Stafeeva** [comment]
- [ ] Come up with the solution on how to order cards
- [ ] Come up with the solution on how to save cards' new position
- [ ] Show link direction (svg)
- [ ] Update canvas when screen width changes (nice to have)
