### ISSUE TITLE
Unable to create resource with % in JSON key

### ISSUE THREAD

**Issue by adeel-ansari** [BlueBrain/nexus#1572]
Trying to create a resource with the following payload:
 
```
{
	'@id': 'http://iri.nidash.org/test1',
	'@type': ['AcquisitionObject', 'prov:Entity', 'assessment-instrument'],
	**'bids:%_Analgesia_WOMAC': 'n/a',
	'bids:%_Analsesia_VAS': 'n/a',**
	'bids:Age': '58',
	'bids:Drug': 'n/a',
	'bids:Response': 'n/a',
	'bids:study': 'n/a',
	'bids:type': 'control',
	'prov:wasGeneratedBy': {
		'@id': 'http://iri.nidash.org/test2'
	},
	'gender': 'female',
	'@context': 'https://nexus-research.camh.ca/v1/resources/users/xnat_testing/_/nidm_context'
}
```

The resource seems to be valid JSON-LD according to JSON-LD playground.  However, getting the following error:

```
{
	"@context": "https://bluebrain.github.io/nexus/contexts/error.json",
	"@type": "InvalidJsonLD",
	"reason": "Invalid payload due to 'Invalid input '_' (line 1, column 30):\nhttp://bids.neuroimaging.io/%_Analgesia_WOMAC\n                             ^'."
}
```

 If I try to insert the resource without the '%' sign, it is successful.

**Comment by bogdanromanx** [comment]
Thank you for submitting the issue, we're in the process of replacing our RDF support, which should also address this issue. Would the use of `bids:Percent_Analgesia_WOMAC` instead of `bids:%_Analgesia_WOMAC` be a viable temporary alternative?

**Comment by adeel-ansari** [comment]
Thanks @bogdanromanx, that sounds good.  We'll use the work-around to handle this issue until the fix is in.

**Comment by umbreak** [comment]
@adeel-ansari the IRI `http://bids.neuroimaging.io/%_Analgesia_WOMAC` is NOT a correct IRI. It will still fail after we update the RDF library:
> The host component a percent occurred without two following hexadecimal digits. see: URI <http://www.apps.ietf.org/rfc/rfc3986.html#sec-2.1> [[ A percent-encoded octet is encoded as a character triplet, consisting of the percent character "%" followed by the two hexadecimal digits representing that octet's numeric value. ]]
