### ISSUE TITLE
Electrophysiology Recording Plugin: Use scale bars

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#1574]
Srikanth has provided feedback on the current plugin (capture below for the record):
![Screenshot 2020-09-01 at 10 58 03](https://user-images.githubusercontent.com/3679766/91829745-26224c00-ec42-11ea-84b7-1704cefd9f1c.png)

Srikanth reports that scientists are used to not see the X/Y axis and instead to see `scale bars`. 
He provided an example for reference (I have highlighted red the scale bars):
![Screenshot 2020-09-01 at 10 45 34](https://user-images.githubusercontent.com/3679766/91829847-43571a80-ec42-11ea-9626-480d7887fc1d.png)

Srikanth is not opposed to have 2 ways to represent the traces:
- Scale bars (default)
- The current view with numbered axis 

It was also discussed that @annakristinkaufmann has produced this kind of rendering of traces in the past and could have information about hot to implement it in the plugin (e.g. how to pick a meaningful value for the scale bars).

**Comment by samuel-kerrien** [comment]
After further investigation with Rajnish, Srikanth, Anna and discussions, it was concluded that we would like this plugin to have the option to render both `axis` and `scale bars`. This should be configurable so that the plugin can render by default either of these 2 modes and optionally render a mean to switch between the modes. In the SSCx portal, it will be configured to use the `scale bars` while in the BBP studio we will keep using the `axis` mode.

Summary of the work to be done:
- [ ] Create a new view in the plugin called `scale bars`. @annakristinkaufmann might be able to provide input on how to process the trace data to render the scale bars.
- [ ] Make the plugin configurable so that a developer can choose the default view (default: `axis`)
- [ ] Add a mechanism to switch between `scale bars` and `axis`
- [ ] Add a configurable option to render or hide the above mechanism

The mockup below shows the two views `scale bars` and `axis`:
![Screenshot 2020-09-08 at 10 58 23](https://user-images.githubusercontent.com/3679766/92455687-49a94180-f1c2-11ea-8333-7b37afe5e84e.png)

**Comment by adulbrich** [comment]
Scale bars will be computed based on max value (from 0), that's the way it's done in Matlab (cfr @dhaneshnm)
