### ISSUE TITLE
Dashboard doesn't load if SPARQL query uses 'project' keyword as sparql variable

### ISSUE THREAD

**Issue by adeel-ansari** [BlueBrain/nexus#1584]
Creating a dashboard with the following is ok:

```
# This is a simple example query
# You can directly edit this
prefix nxv: <https://bluebrain.github.io/nexus/vocabulary/>
prefix nidm: <http://purl.org/nidash/nidm#>
SELECT DISTINCT ?self ?nidm_project
WHERE {
  ?nidm_project nxv:self ?self .
  ?nidm_project rdf:type nidm:Project .
}
LIMIT 20 
```

However, changing 'nidm_project' to just 'project' will cause the dashboard to not load:

```
# This is a simple example query
# You can directly edit this
prefix nxv: <https://bluebrain.github.io/nexus/vocabulary/>
prefix nidm: <http://purl.org/nidash/nidm#>
SELECT DISTINCT ?self ?project
WHERE {
  ?project nxv:self ?self .
  ?project rdf:type nidm:Project .
}
LIMIT 20 
```

Console shows the following error:

> TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
>     at Object.t.parseProjectUrl (index.ts:274)
>     at i (ResultsTable.tsx:61)
>     at t.value (TableCell.js:117)
>     at Ga (react-dom.production.min.js:181)
>     at $a (react-dom.production.min.js:180)
>     at Os (react-dom.production.min.js:261)
>     at vc (react-dom.production.min.js:230)
>     at dc (react-dom.production.min.js:229)
>     at ic (react-dom.production.min.js:223)
>     at react-dom.production.min.js:121

I'm ok with using '[x]_project', but would be good for it to not crash if reserved words are used.

**Comment by adulbrich** [comment]
Fusion

- handle the error properly, meaningful message

Delta

- investigate

**Comment by adulbrich** [comment]
@adeel-ansari Does it still happen? We tried this and it works with 1.6.1.
