### ISSUE TITLE
Setup project for v1

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#161]
_From @julienmachon on October 17, 2018 12:20_

TypeScript, Jest, Lint and SSR

_Copied from original issue: BlueBrain/nexus-explorer#33_

**Comment by julienmachon** [comment]
We now have our basic project setup in a new branch (that will be out "master" while we support v0 for a while): https://github.com/BlueBrain/nexus-explorer/tree/nexus-web
