### ISSUE TITLE
Token expiration issue (for collaborators from China)

### ISSUE THREAD

**Issue by patilurie** [BlueBrain/nexus#1633]
Hi,
Do you remember about the problem I noticed while interacting with our Chinese collaborator? (it seems that  a new access token is not fetched automatically using the refresh token on Nexus Fusion ). In this case an external user had to re-login every time he wanted to refresh the page (to see uploaded file). Could you, please, have a look on it? Thank you!

**Comment by adulbrich** [comment]
@patilurie  Could you give us a little more information about:
- the organization/project the user was trying to access
- what file(s) the user is trying to upload
- the exact steps the user was performing
- when this happened (approximate date and time)
- browser used and eventually extensions used
- location (I suppose China)

I don't see much in our error tracking tool right now (Sentry). We'll do our best to see if we can reproduce the problem.

Thanks! Cheers
A

**Comment by patilurie** [comment]
Hi @adulbrich,
It was a problem I signalised (Slack) on August, 14th.
- external/seu
- it was just one .zip 2.5 MB (with .swc files) 
- the user logged in (using this, please note that it was the previous and still NexusWeb, UI: https://docs.google.com/document/d/13h4HBUsVRZUxBtEfg7cTUePa4y9nYrq_lki1oJDFC4A/edit?usp=sharing). Then, he had to re-login every time he wanted to refresh the page (to see uploaded file).
- August, 14th
- it was a chrome-based browser
- Nanjing, China
- Bogdan said that it could be caused by a time offset

Thanks a lot for looking into it! Cheers,
Pat.

**Comment by adulbrich** [comment]
@patilurie could you confirm if the issue still persists?

**Comment by patilurie** [comment]
Hi! I think that the issue doesn't exist anymore. I'm still waiting for the confirmation from our collaborators for what concerns the new Nexus release. I'll let you know in case they have problem logging in. Thanks for your help!

**Comment by bogdanromanx** [comment]
@patilurie have you heard back from the collaborators?

**Comment by patilurie** [comment]
@bogdanromanx Unfortunately no. I have a meeting with them tomorrow so I'll ask and let you know.

**Comment by patilurie** [comment]
Hi @bogdanromanx! Good news: the issue doesn't exist. Thanks for your help!

**Comment by bogdanromanx** [comment]
Excellent, thanks for confirming.
