### ISSUE TITLE
Have the possibility to use caller identities on CrossProject resolution

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1661]
In some cases we want the CrossProjectResolver resolution depend on the current caller identities and not on the identities defined in the CrossProjectResolver. 

One use case for it comes from @annakristinkaufmann , where project `A` has a crossProjectResolver to resources on other projects and project `A` is used as an entry point to access all resources using the endpoints `/v1/resolvers/{org}/projectA/_/{resource_id}`.

One proposal to implement this feature, keeping backwards compatibility, would be to allow for empty identities on `CrossProjectResolver` creation. If no identities are defined, we will use the caller identities.

When identities are present, the resolution would use those identities to fetch resources and ignore the caller identities

**Comment by imsdu** [comment]
Fixed in #1813
