### ISSUE TITLE
Firefox-Ubuntu style issues

### ISSUE THREAD

**Issue by Stafeeva** [BlueBrain/nexus#1690]
- Weird scrollbars
- Box shadows?
- 'Add Button' icon is messed up
Please see refer to the screenshots:

![Screenshot from 2020-10-15 11-00-59](https://user-images.githubusercontent.com/23080476/96104896-aabae800-0ed9-11eb-903b-25d20bcf9737.png)

![Screenshot from 2020-10-15 11-08-54](https://user-images.githubusercontent.com/23080476/96104904-ac84ab80-0ed9-11eb-8e77-c471b7ad423b.png)

**Comment by adulbrich** [comment]
Not enough demand / no complaints
