### ISSUE TITLE
YouTube Video Viewer Plugin

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1697]
How should we handle videos?

- hosted on youtube, can we embed it? (Youtube Video Plugin)
- hosted on the filesystem, should we have a viewer?
- how to handle multiple video files? gallery? and on click plays video in overlay.

What is the data model for the resource? Will we use distribution?

**Comment by bogdanromanx** [comment]
Decision: OSS YouTube plugin, the URL of the view is expected to be provided in the `distribution` property.

**Comment by adulbrich** [comment]
We should probably use the `embedURL` property of https://schema.org/DataDownload.

@annakristinkaufmann Would you have an example of a resource that has a YouTube video linked to it?

**Comment by adulbrich** [comment]
After a second look at it, we could use the following:
- https://schema.org/VideoObject for the YouTube URL, specifically using `embedURL`
- https://schema.org/video points from the `Dataset` to the `VideoObject`

So if a https://schema.org/Dataset has a video property, that points to a `VideoObject`, that has an `embedURL` value, that contains a youtube link: the plugin will display the video and allow to play it.

What happens then if there are multiple videos? We could then use `ItemList`together with `VideoObject`. 

Some details can be found here: https://developers.google.com/search/docs/data-types/video

**Comment by samuel-kerrien** [comment]
I agree with the above.

In addition, I think if a user opened a `VideoObject` directly, you probably also would want to see the plugin.
I would also recommend listing the properties the plugin will support. schema.org offer quite a lot but we only need a subset to start:

- https://schema.org/Dataset (video[https://schema.org/VideoObject])
- https://schema.org/VideoObject (description[text], name[text], thumbnailURL[URL], embedURL[URL])

As for the question on potentially having multiple videos, I think your proposal to have an [item-list](https://developers.google.com/search/docs/data-types/video#item-list) and a carousselle presentation would be good to start.

**Comment by adulbrich** [comment]
@MFSY approved the `VideoObject` approach. The plugin should activate on an `Entity` and not a `Dataset` though. Because `Dataset` extends `Entity`.

**Comment by annakristinkaufmann** [comment]
Hi @adulbrich @MFSY @samuel-kerrien : Just a quick comment about plugin "activation": While Dataset does extend Entity, i.e. each Dataset is an Entity, we are not always explicitly providing both types on resources. This should be considered when designing the plugin!

**Comment by adulbrich** [comment]
I wrote a small payload with a `"https://schema.org/video"` property and an array of `"https://schema.org/VideoObject"` inside. The prefix should resolve if schema.org is properly defined in the context, which I believe is the case in neuroshapes.

In the payload below, I created an array of VideoObjects because there could be multiple. But on [this link](https://developers.google.com/search/docs/data-types/video#video-carousel-example), they use an `ItemList` and `itemListElement`. I would stick with an array for now.

Payload example:

```jsonld
{
    "@context": "https://bbp.neuroshapes.org",
    "@id": "whatever.ch",
    "@type": [
      "Entity",
      "Dataset"
    ],
    "brainLocation": {
        "@type": "BrainLocation",
        "brainRegion": {
          "@id": "http://purl.obolibrary.org/obo/UBERON_0008933",
          "label": "primary somatosensory cortex"
        },
        "layer": {
          "@id": "http://purl.obolibrary.org/obo/UBERON_0005390",
          "label": "layer 1"
        }
      },
      "subject": {
        "@type": "Subject",
        "species": {
          "@id": "http://purl.obolibrary.org/obo/NCBITaxon_10116",
          "label": "Rattus norvegicus"
        }
      },
      "description": "This is a whatever description of whatever.",
      "name":"",
      "video": [ 
          {
            "@type": "VideoObject",
            "name": "cool brain video",
            "description": "a description of the video",
            "thumbnailUrl": [
              "https://example.com/photos/1x1/photo.jpg",
              "https://example.com/photos/4x3/photo.jpg",
              "https://example.com/photos/16x9/photo.jpg"
             ],
            "uploadDate": "2016-03-31T08:00:00+08:00",
            "duration": "PT1M54S",
            "embedUrl": "https://www.example.com/embed/123"
          },
          {
            "@context": "https://schema.org",
            "@type": "VideoObject",
            "name": "second cool brain video",
            "description": "another description of the video",
            "thumbnailUrl": [
              "https://example.com/photos/1x1/photo.jpg",
              "https://example.com/photos/4x3/photo.jpg",
              "https://example.com/photos/16x9/photo.jpg"
             ],
            "uploadDate": "2016-03-31T08:00:00+08:00",
            "duration": "PT56M2S",
            "embedUrl": "https://www.example.com/embed/456"
          }
      ]
}
```
