### ISSUE TITLE
Jupyter Notebook and Unicore Integration for Fusion Workflows

### ISSUE THREAD

**Issue by dhaneshnm** [BlueBrain/nexus#1752]
Goals:

- Instantiate and track Unicore  jobs from Work Flow Sub App.
- Develop a plugin in JupyterHub that can login to Nexus using BBP KeyCloak and manage the token.

**Comment by adulbrich** [comment]
What was achieved up to now:

- [x] launch a job
- [x] retrieve the list of submitted jobs

What still needs to be done:

- [ ] access to the jupyter instance UI
- [ ] chosen notebook must be available in root directory
