### ISSUE TITLE
ES View support: Implementaion

### ISSUE THREAD

**Issue by dhaneshnm** [BlueBrain/nexus#1798]
- [x]  Allow ES views in Workspace. ES view shows up on edit workspace/view drop down. 1 SP
- [x]  Execute ES query in a Dashboard. 1 SP
- [x]  Show ES query result as a  table. 2 SP
- [x] Show ES query editor in Dashboard Edit window, when the parent workspace has a ES view. 3 SP.

**Comment by adulbrich** [comment]
Waiting for result cards and table view from @kenjinp (search app)

**Comment by adulbrich** [comment]
Linked to https://github.com/BlueBrain/nexus/issues/1169
