### ISSUE TITLE
Fix issues found by integration tests.

### ISSUE THREAD

**Issue by wwajerowicz** [BlueBrain/nexus#1804]
- [x] 1. when trying to create an org that already exists, `label` field is missing in the error response
- [x] 2. missing `orgLabel` and `label` fields in error response when trying to create a project that already exists.
- [x] 3. missing `provided` and `expected` fields in error response when incorrect revision is used
- [x] 4. ~missing _label in response when creating/updating realm~ (will be handled in #1809)
- [x] 5. checking for orgs/projects write permissions instead of create
- [x] 6. ~`_authorizationEndpoint`, `_endSessionEndpoint`, `_grantTypes`, `_issuer`, `_tokenEndpoint`, `_userInfoEndpoint` fields are returned for deprecated realms~
- [ ] 7. can't list projects for an organization

**Comment by umbreak** [comment]
Point `6` I guess is not only on deprecated right? It probably is the payload you get as response to any writing operation on realms?

**Comment by wwajerowicz** [comment]
It's only an issue when fetching a deprecated realm.

**Comment by umbreak** [comment]
In general, about the response fields on writing operations we should follow one of the following strategies and stick to it:

1. Return all fields (there is the edge case of ACLs)
2. Return only `ResourceF`  metadata fields. This is the current approach
3. Return fields considered as metadata (fields starting with `_`)

A hybrid in between seems confusing
