### ISSUE TITLE
The resource event routes do not include all event types (e.g.: resolvers, schemas, views etc.)

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#1807]
This is a change of behaviour since v1.4

**Comment by umbreak** [comment]
There are 3 ways to deal with it:
- Create a tag `event` for each resource type and fetch them using `eventsByTag`.
- Request each tag from each module separately and merge all the streams ordered by timestamp
- Do not provide this global functionality and just offer SSEs per event type (resources, resolvers, files, etc)

**Comment by umbreak** [comment]
We need the following SSEs, which can be implementing using the `EventExchange` and the `GlobalEventLog`:
- SSEs for all resources (`v1/resources/events`)
- SSEs for all resources on an org (`v1/resources/{org}/events`)
- SSEs for all resources on an project (`v1/resources/{org}/{proj}/events`)
