### ISSUE TITLE
Make header and sidebar sticky, scrolling only in the subapps

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1831]
Right now, when scrolling, it scrolls also the header and the sidebar. The scrolling should only work in the body/subapp. The header should always be visible, and the sidebar as well for now (the sidebar should not scroll).

The goal is to make the elements in the sidebar and header easily accessible even when the user is browsing the app.

**Comment by Stafeeva** [comment]
Implemented as Part of BlueBrain/nexus#2209
