### ISSUE TITLE
Deprecation status of imports in schemas

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#1855]
**Motivation**
When resolving imports in a schema during creation/update of a schema, deprecated resources and schemas are currently valid imports.

This should raise an error and the resolution process should continue to the next resolver

**Acceptance criteria**

1. When an import is resolved as a deprecated schema/context, an error should occur, logged in the report and the resolution should continue

**Comment by umbreak** [comment]
Guys do you have any thoughts on this item @MFSY @annakristinkaufmann ?

**Comment by crisely09** [comment]
@imsdu maybe any resource (not only schemas) should be checked, to ensure there isn't deprecated resources linked to them, for example deprecated files.
