### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1890]
How to improve the performance of Nexus Fusion:

- Reduce Plugin Load time
- Reduce time to interactive
- Reduce no. of requests
- Reduce loading large images

**Comment by kenjinp** [comment]
Reduce large image loading: 

- Something like an image resizing nexus plugin / microservice that can serve images uploaded to nexus in whatever dimensions could be the solution here, something like what www.imgix.com does (loads of similar examples). Requested images in their dimensions  /  resolution would be processed by the microservice then cached.

**Comment by kenjinp** [comment]
Reduce no. of requests:
This might be able to be resolved via graphql, which shifts query / compute to server instead of client. Server-side rendering might also alleviate clients. Making client requests cancel-able will also help.

**Comment by adulbrich** [comment]
Postponed until additional issues pop up. For now, it works.
