### ISSUE TITLE
'No data' shown when scrolling down a resource list in the 'Admin' view

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus#1897]
Behaviour observed when scrolling down a resource list (e.g. the Default Query one shown by default when clicking on the 'Admin' view in a project): At first, loading of additional resources works fine but when scrolling too far, 'No data' will be shown. See attached gif:

![query_panel_scrolling](https://user-images.githubusercontent.com/27771434/102521651-7f00dd80-4095-11eb-957b-56367deb80bc.gif)

**Comment by adulbrich** [comment]
Problem is still present, e.g. in https://staging.nexus.ocp.bbp.epfl.ch/admin/neurosciencegraph/datamodels

**Comment by adulbrich** [comment]
Replace infinite scroll with pagination

**Comment by adulbrich** [comment]
solves https://github.com/BlueBrain/nexus/issues/802
