### ISSUE TITLE
Perform validation of a resource inside the Schema state actor

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2017]
We have to change the `EventSourceProcessor` to allow for execution of arbitrary `IO` on the current state. 

This is very important in the case of Schemas in order to avoid serializing the `Schema` instance. This serialization is expensive because the flatten schema Model is big and the validation triples added to the shape are many (almost 4000 triples).

Once this is added, validation will be performed on the Schema state actor instead of the resource state actor.

**Comment by bogdanromanx** [comment]
Duplicates #1533 .
