### ISSUE TITLE
Keep in memory not only the latest state but also the tagged states

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2023]
We have in memory the latest state of a persistenceId (EventSourceProcessor.ChildActor) until passivation kicks in.

It would be a performance improvement to cache in a similar fashion (until passivation kicks in) the tagged state (or event the revisioned state).

We probably want a separate passivation strategy for those instead of keeping it on the same place

**Comment by imsdu** [comment]
Not relevant anymore as we have now snapshots of both the latest states and the tagged states
