### ISSUE TITLE
Nexus Data Access plugin: Enable download for versioned file identifiers

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus#2065]
Currently, the **Nexus data Access** plugin enables download of files through their **_self** as value of the **contentUrl** property of **distribution objects** on a resource. However, the download operation is throwing an error when a versioned **_self** is being used. See below:

Download possible:
```
{
      "@type": "DataDownload",
      "contentSize": {...},
      "contentUrl": "https://12345",
      "digest": {...},
      "encodingFormat": "application/swc",
      "name": "abc.swc"
    }
```

Download causing an error:
```
{
      "@type": "DataDownload",
      "contentSize": {...},
      "contentUrl": "https://12345?rev=1",
      "digest": {...},
      "encodingFormat": "application/swc",
      "name": "abc.swc"
    }
```

**Comment by Stafeeva** [comment]
Resource to test:
https://bbp.epfl.ch/neurosciencegraph/data/neuronmorphologies/52ee8e04-86ce-420e-b7b3-12c5af6ffbd1
