### ISSUE TITLE
Introduce a configuration structure convention for plugins to avoid collisions

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2074]

**Comment by umbreak** [comment]
Isn't it [already the case](https://github.com/BlueBrain/nexus/blob/master/delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/plugin/PluginDef.scala#L30)

**Comment by bogdanromanx** [comment]
This is about avoiding plugin configuration collisions when the configuration is merged during bootstrapping. I think it would be safer for plugins to use a configuration root like:

```
delta.plugins.storage {
  # configuration goes here
}
```

**Comment by umbreak** [comment]
This could be done as it is currently by just removing (or throwing) when there is any root key in the plugin configuration other than `info.name`

**Comment by bogdanromanx** [comment]
Not really, because plugins may wish to configure global settings.

**Comment by umbreak** [comment]
Yeah, could be. In any case, that can be handled when merging the configurations

**Comment by bogdanromanx** [comment]
The two locations that need to be changed are: `PluginDef` and the custom config decoder that loads each plugin configuration from the merged config (e.g. `StoragePluginConfig`)
