### ISSUE TITLE
Add a way to exchange metadata fields between plugins

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2085]
`PluginDef` should have another field (as we have with RemoteContextResolution) as follows:
```scala
/**
  * Metadata context provided by the plugin.
  */
def metadata: Json
```

This will then by used in `WiringInitializer` to compose the `contexts.metadata` from the core deepMerge with all the plugins.

Once this is done we should remove from the current metadata.json the knowledge of the modules (storages, elasicsearch, blazegraph, files, etc)

**Comment by bogdanromanx** [comment]
An alternative would be something like:
```
def metadataContext: ContextValue
```
for direct context value merge.
