### ISSUE TITLE
Remove backend

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#211]
_From @kenjinp on October 18, 2018 13:53_

The search app consumes the Nexus API directly so any backend dependancies can be removed to keep things simple.

_Copied from original issue: BlueBrain/nexus-search-webapp#108_

**Comment by mdupont** [comment]
_From @kenjinp on October 22, 2018 11:52_

This might still be needed to run the script automation, unless we use a new docker image for some chron job perhaps

**Comment by kenjinp** [comment]
Closing as we'll need the server for automated ETL
