### ISSUE TITLE
Design morphology Release Cards and Details Page

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#213]
_From @kenjinp on October 18, 2018 13:58_

connects #212 

_Copied from original issue: BlueBrain/nexus-search-webapp#110_

**Comment by mdupont** [comment]
_From @kenjinp on October 22, 2018 14:52_

![Screen Shot 2018-10-22 at 16.51.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae7335e24284b0011eb9fe8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f16b7191a379e90c2e50415f46be5d4a1f06a3a3dc78e2a436628f0d5eead26f0d75946b43afbd8a1fbf00e821dd4c85e3ee9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58f44ae84457a41a3665f43b.png)

First pass on the Search Result Snippet

**Comment by mdupont** [comment]
_From @kenjinp on October 22, 2018 15:9_

You can find an example of the Morphology release instance here [https://bbp-nexus.epfl.ch/staging/explorer/thalamusproject/simulation/morphologyrelease/v0.1.2/effa469e-4781-4454-9dc4-ea8942695dfb](https://bbp-nexus.epfl.ch/staging/explorer/thalamusproject/simulation/morphologyrelease/v0.1.2/effa469e-4781-4454-9dc4-ea8942695dfb) although you may need to manually navigate to it...

**Comment by elisabettai** [comment]
Release cards looks good, the one on the far right has more information which I'd like to see: for example the species and the brain region ("thalamus" is what I'd expect in this example). The name is also good, from our side we can work to make it more informative). Date and time can be made more explicit, maybe on two lines (and not part of the title).

**Comment by kenjinp** [comment]
mTypes and morphologies, as well as previews might be tough because there are LOTS inside the index file, so we can't load it on the client.

 Perhaps a pre-processing step could show these 🤔

**Comment by elisabettai** [comment]
I see. None of the above points is critical I think, they were just ideas on what to show in the detailed view.

@genric added a step to the workflow engine to get mTypes, layers and number of morphologies, maybe you can leverage this. 

About previews, we also discussed about showing morphologies "on demand".

**Comment by jdcourcol** [comment]
do you have a live instance of the app where I can see the morphology cards ?

**Comment by kenjinp** [comment]
The morphology releases can be found living in the staging environment, as long as you have access. 

https://bbp-nexus.epfl.ch/staging/search/?filter=%7B%7D&listType=Grid&size=15&sort=%7B%7D&type=nxv%3AMorphologyRelease
