### ISSUE TITLE
Wrong ACLs for Search app resources

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#219]
It seems that people outside of our team cannot access Search app data even though they're authenticated. The datasets should be accessible to any authenticated user.

**Comment by kenjinp** [comment]
Access rights per dataset must be respected, but there's not way to control this in search at the moment. We'l resolve this with #223  in some fashion, until then users can request access to DKE

connected to #223

**Comment by kenjinp** [comment]
public data is now freely available!
