### ISSUE TITLE
Enable community defined schemas

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus#22]
There is a great value in enabling community defined schemas. Different organizations (let say H and B) sharing the same use cases may want to develop a common set of schemas that don't really belong in one organization domain or the other.

Challenge:
 * schema naming and identification
 * ...

**Comment by samuel-kerrien** [comment]
It is probably worth mentioning that INCF NeuroShapes is where we are currently enabling the community building of shared Neuroroscience schemas:
https://github.com/INCF/neuroshapes
