### ISSUE TITLE
Iri normalization

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#2211]
The order of the query parameters should not matter when comparing two iris

**Comment by bogdanromanx** [comment]
According to the RFC, the IRI equality logic is something that a system can decide (normalization can be implemented).
https://tools.ietf.org/html/rfc3987#section-5.3

Pre v1.5 we disregarded that, so I'm not sure this is an actual bug. @umbreak, what are your thoughts ?

**Comment by umbreak** [comment]
Yeah, I think it is not a must have either. You can consider then as separate ids when the query params are in different order.

But that would mean having to do some fixed during migration probably. Since it seems that the @ids in the payload aren't always the exact same as the ones in the event

**Comment by bogdanromanx** [comment]
I presume that doing a normalization will not have a significant performance impact; is that correct? We would test for equality only for resource ids, right?

**Comment by imsdu** [comment]
If we normalize, we should also normalize the ones that may be in the payload of resolvers and views for example

**Comment by umbreak** [comment]
Yes, maybe we have to normalize the `rootId: IriOrBNode`  on the CompactedJsonLd and ExpandedJsonLd documents. However I wouldn't go too far with this. As @bogdanromanx said, we are not forced to implement normalization at all.

If it becomes difficult/annoying, we should just not do it.

**Comment by imsdu** [comment]
If we do it later, it will be more complicated as we will have to apply normalization on existing data.

We can't have a Iri circe decoder that would do it when deserializing user data ?

**Comment by umbreak** [comment]
My point was more that we don't need to do it at all.

**Comment by imsdu** [comment]
It is ok to close it and assumes it works differently from 1.4 then ?

**Comment by imsdu** [comment]
Iri normalization is not part of the desired features for the moment.
