### ISSUE TITLE
Find a way to serve the static contexts directly from json, instead of through the docs

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2228]
Right now the static jsons have to be manually copied and assembled from our `resources` inside the scala project to the [paradox context folder](https://bluebrainnexus.io/contexts/resource.json).

This is a very bad approach and it is very easy for us to forget updating it and so on.

We should be able to serve those contexts though nexus while keeping the URLs they have.

**Comment by imsdu** [comment]
Fixes with #2387
