### ISSUE TITLE
Prevent duplicate resource ids within the same project across all resource types

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2247]

**Comment by umbreak** [comment]
This can be done querying the DB before a resource, schema, resolver, view, storage, archive is created. It can be achieve with the following query:
- Postgres: 
``` 
SELECT COUNT(persistence_id) from event_journal WHERE persistence_id='{moduleType1}-{project}_{id}' OR persistence_id='{moduleType2}-{project}_{id}' ...;
```
- Cassandra: 
```
SELECT COUNT(persistence_id) FROM all_persistence_ids WHERE persistence_id in ('{moduleType1}-{project}_{id}', '{moduleType2}-{project}_{id}', ...);
```

**Comment by bogdanromanx** [comment]
The query should be sufficiently fast, I don't think there's a need for a LRU cache.

**Comment by imsdu** [comment]
How much time to perform the cassandra query on production data ?

**Comment by umbreak** [comment]
Around 30ms

**Comment by bogdanromanx** [comment]
Is that on nvme disks?

**Comment by umbreak** [comment]
No idea. It is in that VM inside docker

**Comment by umbreak** [comment]
In production it seems more like 200ms

**Comment by umbreak** [comment]
Ok. For  cassandra is faster to run in parallel the following query:
```
SELECT COUNT(persistence_id) from persistence_id 
   WHERE persistence_id='{moduleType1}-{project}_{id}' 
```
and retrieve the first result where count = 1, using something like [race](https://monix.io/docs/current/eval/task.html#race-many)

the IN clause requires coordination between different nodes of the cluster
