### ISSUE TITLE
Processing FailedEvents in views

### ISSUE THREAD

**Issue by adeel-ansari** [BlueBrain/nexus#2292]
There can be failedEvents due to some reason.  Currently we don't know which resource failed to insert.  If the project is large, restarting the view will take too long to process.  

Is there a way to view which event failed?  Also a way to replay just the failedEvents and/or deleting the failedEvents in case we insert it in another process?

**Comment by bogdanromanx** [comment]
Currently the failed events are not exposed through the API, they are only visible in the database. There's also no functionality to attempt to reindex only the failed events.

The behaviour of the system with respect to indexing failures is the following:
- if during indexing, the target system becomes unavailable or returns a server error (5XX status code), the failure is retried with an exponential back-off and nothing is recorded in the database, no failed events will be presented in the statistics
- if the response we get from the target system is a client error (4XX status code) the failure will not be retried, it will be recorded in the database and it will be presented in the statistics

Considering the above, attempting to reindex only failed events would result in the same kind of error, with the possible exception when the system is mis-configured.

I should also note that the indexing process will also attempt to index the last revision of a resource so, for example, if for a specific resource id there are 5 events and the indexing just starts, the index will reflect revision number 5 even after processing only the first event.

The simplest way to correct a failure for a specific event during indexing is to perform an update on the affected resource.

I've created a #2299 to keep track of the ability to expose failure information through the API.

**Comment by adeel-ansari** [comment]
Thanks @bogdanromanx , the explanation helps.  

I had raised this issue because I sometimes notice that re-indexing the default graph view reduced the number of failedEvents (due to a system misconfiguration like Blazegraph going down but Cassandra is still up?).  

Would #2299 provide us with a way to get the failed resources payload?

**Comment by umbreak** [comment]
- We'll definitely work on improving visibility on the occurring failures.
- There is also a ticket to restart a view from a specific offset, which can help with this.
- We'll think about ways to try to recover from failures, when those are server errors (maybe the retry exponential backoff was not enough for a recovery in those cases).
