### ISSUE TITLE
Enable users to remove a step from the workflow

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2426]
In the step info pane, add a button to delete the step. This will deprecate the step, remove any links to or from it, and deprecate and delete sub-steps and sub-components a well, recursively.

Let's chat about a solution.

**Comment by nicwells** [comment]
Discussed implementation with @adulbrich. Implementation will deprecate any subcomponents associated with the step or sub-steps apart from datasets, which will be untouched.
