### ISSUE TITLE
Metadata plugin: Brain region label shown as "undefined" if the same brain region @id appears twice on the same resource

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus#2433]
In some cases, we have resources with the same brain region information in
 
* brainLocation.brainRegion
* neuriteFeature.projectionBrainRegion

In those cases, the **Metadata plugin** is sometimes showing "undefined" as Brain Region (since the label only appears once in the resource graph)
This behaviour could potentially be avoided by fetching the /source endpoint of the resource

**Comment by adulbrich** [comment]
@annakristinkaufmann could you provide a couple of examples so that we can fix it? if possible a project where you have many resources with that specific path

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2433?planning-poker) with ZenHub @adulbrich @imsdu @nicwells @smitfire @wwajerowicz
