### ISSUE TITLE
Nexus Studio: Tag specified in custom Sparql view not respected when fetching resources

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus#2434]
We have a use case where a studio is targeting a custom Sparql View which specifies a particular tag. While the list of resources is consistent with resources that contain this tag, the resources fetched are their latest versions and not the resource at the specified tag.

**Comment by adulbrich** [comment]
The rev and tag parameters should be respected when we open a resource. 
If the user or table (or dashboard) provides a revision or tag, the resource view should show the correct revision.
The tag is an alias of a specific revision.

A resource view should show the selected revision, and the plugins should render that revision as well. 

Basically we should fetch the resource like in the API:
https://bluebrainnexus.io/docs/delta/api/current/kg-resources-api.html#fetch-a-resource

In the new resource view proposal, there's an explicit toggle for the revision. We should probably combine the development efforts.
