### ISSUE TITLE
Admin is not available in Fusion when not logged in

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2444]
When testing out Nexus with minikube or docker swarm one cannot use Fusion to create organizations, projects and resources, although Anonymous has full privileges and there are no realms configured.

I think it would be good to enable admin if one of the following conditions are met:
1. there are no realms configured delta (`/v1/realms` returns an empty list)
2. the `Anonymous` user has some one of the following permissions defined in the scope tree (`/v1/acls/*/*?self=true&ancestors=true`): `resources/read`, `orgs/create`, `projects/create`

**Comment by adulbrich** [comment]
@bogdanromanx Do you mean the "create organization" button does not work? Or you don't see the admin app? In the latter case, could you try accessing `/admin`?
@Stafeeva could this be related to the default configuration/visibility of subapps?

**Comment by bogdanromanx** [comment]
The admin app is not available at all, and accessing `/admin` redirects to `/login` returning an empty page.

**Comment by adulbrich** [comment]
@Stafeeva will have a look. It seems related to a misinterpretation of the [original ticket ](https://github.com/BlueBrain/nexus/issues/1693) that aimed to hide the subapps from the sidebar and homescreen.

**Comment by Stafeeva** [comment]
The Admin should be now available on `/admin`.

**Comment by bogdanromanx** [comment]
Can this ticket be closed, then?
