### ISSUE TITLE
Investigate cassandra pub/subs in order to reduce polling intervals but retain performance

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2462]
If this works, it should allow us to reduce the pressure on Cassandra (from multiple views streams parallel executions) while keeping the `eventsByTag` delay low.

**Comment by imsdu** [comment]
While pubsub can be used to lower latency as advertised in the [akka-persistence-cassandra documentation](https://doc.akka.io/docs/akka-persistence-cassandra/current/events-by-tag.html#tuning-for-lower-latency), the tests show that enabling it and increasing significantly the polling interval is not a valid solution to reduce pressure on the primary store as it prevents indexing to work correctly.
