### ISSUE TITLE
Offset instant can lead to confusion

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2489]
Sometimes on the API we return the `Offset` (restarting a view, statistics). 

In some cases the Offset shown has a value called `instant` (when using Cassandra offsets). This instant is NOT the event instant but the offset instant (which can be different after migrations).

Maybe we don't need to do anything about it (except for document it properly) but it is something t be considered.

**Comment by imsdu** [comment]
Not relevant anymore as offsets are now relying on a sequence
