### ISSUE TITLE
Login is broken in Safari when you login after opening a link

### ISSUE THREAD

**Issue by Stafeeva** [BlueBrain/nexus#2493]
Probably related to this one: https://github.com/BlueBrain/nexus/issues/2328

Try this link and login with bbp: 
https://bbp.epfl.ch/nexus/web/admin/public/sscx

<img width="485" alt="Screenshot 2021-05-27 at 15 27 47" src="https://user-images.githubusercontent.com/23080476/119841610-40096a80-bf06-11eb-84e4-ad2a1301ea0a.png">

**Comment by Stafeeva** [comment]
Doesn't happen in Safari Version 14.1.1 (16611.2.7.1.4) + Big Sur

**Comment by adulbrich** [comment]
It is not broken anymore but the redirect does not work, will create or check if we have an issue related to it
