### ISSUE TITLE
Awake indexing stream at random times for edge cases (cassandra timeouts)

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2519]
There can be edge case situations where the combination of idleTimeout on indexing streams plus `IndexingStreamAwake` is not enough (maybe very long retrystrategies or cassandra timeouts).

We should test those edge cases and see how the system behaves. If that's a real problem, we could have a process that awakes some indexing stream at random.

**Comment by imsdu** [comment]
Not relevant anymore with Nexus 1.8
