### ISSUE TITLE
Provision a default project for a user upon his first interaction with the API while authenticated

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2520]
This is to support the EDX Course Integration (#2514), where for UX a user should be automatically provided with a specific project where he can interact with the system.

The general flow would be:
1. Login to Fusion
2. List organizations
3. Select the Course organization
4. List projects (the user project should already appear in the list)

Important aspects:
- the behaviour change may incur an additional computational cost; prefer the use of caches or devise a mean to perform this check only once (the existence of the pre-assigned project)
- when supporting multiple IdPs there's the possibility of subject (preferred_username) collisions; the default project must include a realm discriminator in its label
- the behaviour must have an enabled/disabled flag (e.g. `app.projects.automatic-provisioning.enabled = true`) in the configuration such that environments that are not meant to integrate with EDX do not have to incur the check's runtime penalty
- the collection of permissions that need to be assigned to the user for which the project is provisioned needs to be configurable (e.g. `app.projects.automatic-provisioning.permissions = ["resources/write", ...]`)
- the organization under which the projects will be provisioned needs to be configurable (e.g. `app.projects.automatic-provisioning.organization = "users"`)
- the project `description`, `base`, `vocab` and `api-mappings` need to be configurable (e.g. `app.projects.automatic-provisioning.config.base`)

Other notes:
- provisioning should only check for project existence
- provisioning does not need to reconcile permissions
- provisioning does not need to handle the existence of a deprecated project (if the user deprecated his project, this should not be handled; the guard that could be put in place is to avoid granting "projects/write" permission to the user, but this would impact changing the project's API mappings, base and vocab values)

**Comment by wwajerowicz** [comment]
One way to do that, could be to create a project on login redirect.
The flow could be like that:
1. User visits fusion
2. User logins through IdP
3. Upon redirect to fusion, fusion creates a project for user.

This could need some changes in Delta api, but rather than automatic provisioning, we could set the default values for projects (permissions, description, base, vocab and api-mapppings)
In this case, Fusion would need to be aware in which organization to create the project.

Alternatively, we could provide an endpoint that would create the project in the correct organization.

Provisioning the project at login would be much simpler, since we would only need to do it once, rather than check for project existence everywhere in the API.
The downside is that it would require also some frontend changes.

**Comment by bogdanromanx** [comment]
Provisioning of the project can only happen in Delta, due to required permissions and only if Delta is configured for automatic provisioning.
I think there are two ways to go about it:

1. Execute the logic to check and provision a project, only when enabled by config, during project listing, where we can perform the check with very little cost
2. Expose a specific endpoint that can be called only when authenticated that will provision the project for the current user regardless of his permissions; this change is a little more involved in the sense that requires many more changes (Fusion and Delta with a specific endpoint)

I think option 1 is quite ok, other thoughts?

**Comment by umbreak** [comment]
What is the use case to have current `api-mappings`? What values do we want to have for the MOOC?

What is the use case to have custom permissions? What values do we want to have and why they should be different to `permissions.owner-permissions` (that field is there exactly for this of setting default permissions to a project for the owner). It seems we are reimplementing an already implemented feature.

**Comment by bogdanromanx** [comment]
1. we're unsure at this stage if the api-mappings need to be configured for the mooc because the tutorial is still evolving, but we should be able to support a custom configuration for api-mappings to avoid later changes.
2. because the permissions set for this use-case are more limited than the owner permissions, like for example, the ability to grant access on the project (users provisioned will not have ACL write, for example). See #2514.

**Comment by umbreak** [comment]
@bogdanromanx so point 1) is indeed over engineering since there is no use-case.

and point 2) I still don't see the use cause even after reading the issue. It is written TBD and there is no argument why a student should NOT have acls/write on his/her own project. I think `owner-permissions` do the job without extra complicating the codebase

**Comment by wwajerowicz** [comment]
If we don't need custom permissions and custom default api mappings, couldn't we just allow the users to create the projects themselves as part of the tutorial?

**Comment by bogdanromanx** [comment]
> so point 1) is indeed over engineering since there is no use-case.
to configure how the project is provisioned is not over-engineering, just common sense

> and point 2) I still don't see the use cause even after reading the issue. It is written TBD and there is no argument why a student should NOT have acls/write on his/her own project. I think owner-permissions do the job without extra complicating the codebase
project provisioning is a functionality that's different from simple project creation; project creation is done by the user, provisioning is done for showcase purposes like the sandbox or the mooc; the subject which creates the project will be different in these two cases, which is why using separate configuration is better. The default permissions for automatic provisioning can simply be `{app.permissions.owner-permissions}`, but I think it should still be different configuration.

> If we don't need custom permissions and custom default api mappings, couldn't we just allow the users to create the projects themselves as part of the tutorial?
we need to make sure that we limit the number of projects that are created; currently there's no way to allow a user to create a single project

**Comment by umbreak** [comment]
> we need to make sure that we limit the number of projects that are created; currently there's no way to allow a user to create a single project

If that's the only reason to have this features, it would have been easier to just start by that :)

It seems to me those gathered requirements are a bit arbitrary. 'Common sense' is not a reason to implement a feature, but how it relates to a real use case.

That the default permission points to `{app.permissions.owner-permissions}` would just make the code more complicated for no reason. Right now the same functionality, ACLs initialization, happens in 2 places: 
- ProjectProvisioning
- OwnerPermissionsScopeInitialization

**Comment by wwajerowicz** [comment]
> If that's the only reason to have this features, it would have been easier to just start by limiting the number of resources that a user can create (we know which resources are created by which user since we have the createdBy).

Limiting the number of resources created by a user across multiple projects seems much more complicated that provisioning the project and limiting the permissions to create projects.
