### ISSUE TITLE
Restrict volume of data through quotas (static configuration)

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2525]
For deployments that are meant to showcase the Nexus features, like for example one that supports an EDX course, there's a need to enforce quotas because of the lack of control on how many resources and files a user may create.

The system should allow the configuration and enforcement of quotas:

- maximum number of resources in the project (all persistent resource types with the exception of files)
~- maximum number of files in the project~
- maximum size of a single file in the project: Handled through storages
- maximum size of all files in the project: Handled through storages

**Expected behaviour:**

- project creation will apply a default quota defined in the configuration (e.g. `app.projects.quota.{quota-config-entry}`)
- an user can view the project quota if she/he has the `quotas/read` permission on the project
- the default project permissions need to include the new quota specific permissions
- an API call will return the project quota on read (e.g. `GET /v1/quotas/{org}/{proj}`)
- Fusion will display the quota configuration in the project details (mock-ups should be defined and presented to @adulbrich)
- nexus.js needs to be updated to support quota endpoints
- attempting to create new resources after the quota is reached should result in `400 Bad Request` or `429 Too Many Requests` (TBD) with a descriptive reason as to why the request has failed; Fusion and CLI should display the error in their standard notification mechanism
- deprecated resources should count for the quota

**Not included in the ticket:**
- quotas for number of revisions (per resource, per file, globally within a project)
- the CLI will show the quota configuration through a subcommand to projects (e.g. `projects quota {org}/{proj}`)
- the CLI will enable setting a new quota configuration through the same subcommand (e.g. `projects quota {org}/{proj} --max-resources=<int>`)

**Comment by umbreak** [comment]
## Get project quotas

`GET /v1/quotas/{org}/{proj}`

```json
{
   "@type": "Quota",
   "resources": 1000
}
```

## Get project statistics

Modify the statistics endpoint to include `eventCount` and `resourceCount`. E.g.:

`GET /v1/projects/{org}/{proj}/statistics`

```json
{
    "@context": "https://bluebrain.github.io/nexus/contexts/statistics.json",
    "lastProcessedEventDateTime": "2021-08-04T13:33:01.329Z",
    "eventCount": 12,
    "resourceCount": 10
}
```

## Storage creation

Add the optional field capacilty. E.g.:
```
{
  "capacity": {max_accumulated_file_size}
}
```

**Comment by umbreak** [comment]
Delta Split work:

- [ ] Implement the fetch `/v1/quotas/{org}/{proj}` endpoint using static config @umbreak 
- [ ] Update the project statistics endpoint & logic to include resources count (and not only events count) @umbreak 
- [ ] Enforce quotas @umbreak 
- [ ] Add `capacity` field to storages payload @imsdu 
- [ ] Keep track of the capacity currently used by each storage @imsdu 
- [ ] Enforce capacity

**Comment by adulbrich** [comment]
Fusion Split work:

(moved from https://github.com/BlueBrain/nexus/issues/2656)
nexus.js needs to be updated to support quota endpoints

- [ ] an API call will return the project quota on read (e.g. GET /v1/quotas/{org}/{proj})
- [ ] an API call will allow updating the project quota (e.g. PUT /v1/quotas/{org}/{proj})

**Comment by umbreak** [comment]
All the issues related to quotas have been tackled. So I guess I can close this.

**Comment by adulbrich** [comment]
@umbreak @Stafeeva please sync on the additional items Natalia would like to tackle: either create another issue or close this one after discussion.
