### ISSUE TITLE
Record and present deployment usage stats

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2528]
**Design proposal timeboxed to 2 days**

Expose Delta metrics that allow visualizing the usage of deployment for showcasing Nexus features, for example in the case of a deployment that supports an EDX course.

Metrics over time:

- number of active projects
- project creation
- project deprecation status
- project deletion
- resource count per project
- file count per project
- file size distribution per project
- total file size per project
- ... check current grafana dashboards

Configure two Kibana dashboards (templates to be version controlled) that present:

- a global view on the project statistics (total values for all projects)
- a specific project view (values of a specific project)

Note: considering that the statistics need to be recorded over time, the `influx` projection should be generalized from the CLI and ported as a plugin of Delta instead. An initial implementation can be done without any runtime configuration; static configuration is sufficient.

Tasks:

- collect resource events and move them to ES
- create dashboards in Kibana and save them in git somewhere (GitHub)

Not in scope?

- install Kibana https://bbpteam.epfl.ch/project/issues/browse/NISE-195
- dashboard: file size distribution (Gitlab?)
- dashboard: ACLs information

**Comment by adulbrich** [comment]
@bogdanromanx could we consider in the future having it as part of fusion? have a proper route like /nexus/web/statistics?

**Comment by adulbrich** [comment]
This could be answered by ElsaticSearch instead of InfluxDB @imsdu 
Could we use it to also improve upon project statistics?

**Comment by adulbrich** [comment]
@dhaneshnm @imsdu @nicwells @Stafeeva @umbreak Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2528?planning-poker)
