### ISSUE TITLE
Support multiple versions in the website documentation

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2529]
The documentation is currently updated prior to a minor release with the supported functionality, thus losing the information of what is supported on each version. The immediate impact is that documentation cannot be written unless the functionality is completed because it needs to be deployed only after the release.

The support of multiple versions within the documentation would allow a smoother evolution of the documentation during development where a "in development" meta version can be updated for each individual functionality added to the system.

General requirements:

- the documentation must remain at `https://bluebrainnexus.io/docs` without affecting the product website
- it must support markdown with html customisations
- it must be searchable
- it must allow checking references
- it must support multiple versions (with navigation between version)
- it must be controlled through CI (deployment from the master branch)
- optionally: it must notify users that are browsing an older version of the documentation to navigate to the latest released version

**Comment by imsdu** [comment]
To keep older versions of the documentation, there is a PR in `sbt-ghpages` that has been opened for ages:
https://github.com/sbt/sbt-ghpages/pull/39

But from what I saw, the best approach is the one adopted by typelevel for cats-effect.

There is a special branch for docs: https://github.com/typelevel/cats-effect/tree/docs
* This branch contains git submodules pointing to the branches of the versions 2.x and 3.x
* Dependabot updates the references of the submodules
* A github action is launched to build the docs and deploy to github pages: https://github.com/typelevel/cats-effect/blob/docs/.github/workflows/microsite.yml

For the message about the old version, akka just includes a simple js asset in paradox that parses the url: https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/assets/js/warnOldDocs.js

**Comment by imsdu** [comment]
An alternative that still uses `sbt-ghpages` is described here:
https://github.com/sbt/sbt-ghpages/issues/10#issuecomment-385053640
That seems the approach taken by sbt:
https://github.com/sbt/website/blob/0.13/project/Docs.scala#L162

**Comment by imsdu** [comment]
Paradox seems to have a feature to show a warning when the user is not looking at the current version:
https://developer.lightbend.com/docs/paradox/current/configuration.html#version-warning
Which seems to have a minor bug: https://github.com/lightbend/paradox/issues/417

**Comment by imsdu** [comment]
An example of what I can achieve while relying on Paradox:

![Screenshot 2021-06-14 at 16-41-41 Nexus Versions · Blue Brain Nexus](https://user-images.githubusercontent.com/10530477/121913755-f310fb00-cd31-11eb-9ab0-bdc639b8f84a.png)

https://github.com/imsdu/nexus/commit/f6ac2fc8525240e198b3b5178ae0aa144ff57e9a

Main aspects:
* The solution relies on git submodules, the branch is created with no history
* Current docs and contexts are published on /
* Snapshot docs and contexts are meant to be published on /snapshot
* v1.4.x docs are meant to be published under /v1.4.x
* The version page is the same for all version and has a copy for each of them (its content is just an example).

We are quite limited by Paradox and the theme we used:
* In the navigation menu (on the left), we can't have pages that are not included in the project (so no way to have a external version page or to point directly from this menu to the different docs)
* For some reason, customizing templates work while calling the `paradox` command but not the `makeSite` command
* When using a variable (ex: the doc version) inside a #h1, the h1 value is correctly displayed in the page content but not in the header

**Comment by imsdu** [comment]
What an older version can look like:

![Screenshot 2021-06-15 at 16-23-14 Blue Brain Nexus](https://user-images.githubusercontent.com/10530477/122070231-11d8c580-cdf6-11eb-8bfd-14ddf42d1a5a.png)

**Comment by imsdu** [comment]
Completed when merging #2555
