### ISSUE TITLE
When a prefixmapping that collides with a valid Uri schema is defined, it is not used

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2532]
If a project contains in the `apiMappings` a `prefix` with is also a [valid Uri scheme](https://en.wikipedia.org/wiki/List_of_URI_schemes), this won't be used (since we can build a `IriSegment` directly)

**Comment by adulbrich** [comment]
solves https://github.com/BlueBrain/nexus/issues/2602
