### ISSUE TITLE
Defaultquery text search is acting up

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2536]
![2021-06-08--default-search](https://user-images.githubusercontent.com/11705901/121196798-125ee280-c871-11eb-9940-fcbdb1b1c9b7.gif)

In staging, can be tested on `cells/emodel_pipeline`

**Comment by bogdanromanx** [comment]
Looks like the default ES configuration does not account for that case... @umbreak can you comment on this?

**Comment by umbreak** [comment]
We are doing a strict match, even for those cases of full text search. We have tokenizers that try to split different tokens. In this case, the `path` with the value `gpfs/bbp.cscs.ch/project/proj71/cells/optimizations/mechanisms/NaTg.mod` gets split into
```
gpfs
bbp
cscs
ch
project
proj71
cells
optimizations
mechanisms
na
tg
mod
```

If you match any of those terms, it will match the query. We need something different on the query side, for example a [match phase prefix query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase-prefix.html). This effectively matches on a regex `string*`
