### ISSUE TITLE
Enable consistent resource writes through the API

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2537]
Interactive tools expect that data that has been created / updated should automatically (instantly) be indexed: e.g. Fusion workflows, Luigi pipelines etc.

Introduce a new query parameter for write operations `execution=performant|consistent` that defaults to `performant` but when set to `consistent` Delta will force index the resource in question in all respective views of the project.
This change will incur a latency penalty, but in some situations this is justifiable and very important.

Make the necessary changes in Fusion such that all interactions are using the consistency flag. E.g.: resource creation / update / tag / deprecation and implicitly entity (resource, schemas, views, storages, resolvers, workflows, workflow steps, tables, studios etc.) creation/update/deprecation in workflows, studios, admin.

To be investigated if bulk file upload in Fusion needs to be set to "performant".

Affected components: Delta, Fusion and Forge.

- [x] https://github.com/BlueBrain/nexus/issues/2573
- [ ] Fusion
- [ ] Docs
- [ ] Create ticket to update Forge
- [ ] Integration tests

Not included in this ticket: A forced update to CompositeViews (#2564), consistent writes for projects (https://github.com/BlueBrain/nexus/issues/2567)

Related work (depends on this work): #1395

**Comment by wwajerowicz** [comment]
Error when consistent write fails
Status Code: `500`
```
{
   "@type": "IndexingFailed",
   "details": [],
    "resource": {
        "@id": ""
     }
}
```
