### ISSUE TITLE
Implement and expose routes to easily consume types relationships statistics

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2545]
### Request:
```
GET v1/statistics/{org}/{project}/relationships
```
### Example:
```json
{
  "@graph": [
    {
      "@id": "Trace",
      "_count": 3567,
      "generatedBy": "PatchedClamp",
      "derivedFrom": "Cell",
      "contribution": {
        "agent": "Person"
      }
    },
    {
      "@id": "PatchedClamp",
      "_count": 4000,
      "usedBy": "Cell",
      "contribution": {
        "agent": "Person"
      }
    },
    {
      "@id": "Person",
      "_count": 500
    },
    {
      "@id": "Cell",
      "_count": 1242
    }
  ]
}
```

## Relationship API contract:
Same as [properties API](https://github.com/BlueBrain/nexus/issues/2544)

**Comment by imsdu** [comment]
For the first one:
* Could we put together the relationships in a nested object to make easily the distinction with the other property ?
* Could we put together the type information in a nested object ?
* Could we have the relationship id besides the name ?

For the second one:
Could the response could be identical (or very close) to an item of the `@graph` array of the first response ?

**Comment by umbreak** [comment]
This is the way a JSON-LD document is represented when there are multiple entries referencing the same entry. With that I mean: each of those types can be related to the others. With that encoding, you don't need to duplicate any information and have convoluted nested structures. It is the least verbose representation and it does the job.

Notice that there is NO root node here and that's exactly what this graph represents, so it makes total sense

**Comment by umbreak** [comment]
> Could the response could be identical (or very close) to an item of the @graph array of the first response ?

The second response is identical to the `properties` API endpoint for convenience (and since both response will be used to build the right hand side panel)

**Comment by imsdu** [comment]
> This is the way a JSON-LD document is represented when there are multiple entries referencing the same entry. With that I mean: each of those types can be related to the others. With that encoding, you don't need to duplicate any information and have convoluted nested structures. It is the least verbose representation and it does the job.
> 
> Notice that there is NO root node here and that's exactly what this graph represents, so it makes total sense

What if we have a relationship `name` or `counts` or any other field we want to add in the future ? Is there a way to avoid these collisions ?

**Comment by umbreak** [comment]
Sure. In the same way we always avoid collisions on JSON-LD: by prefixing those fields with `_`

**Comment by Stafeeva** [comment]
Given the current structure, we have to rely on the fact that everything, that is not `@id`, `name` and `_count`, is a relationship, which can be fine to work with.
But I think @imsdu's suggestion to put links in a nested object totally makes sense.

This is a tricky bit though:
```
"contribution": {
    "agent": "https://schema.org/Person"
  }
```
Do we display an `agent` link here? Does this mean that `contribution` can also be an array with multiple links? Can we just have a flat list of links here instead of a nested `contribution` object? 

We will need a link id as @imsdu suggested, as names can be identical.

**Comment by umbreak** [comment]
> Given the current structure, we have to rely on the fact that everything, that is not @id, name and _count, is a relationship, which can be fine to work with.

Yes, that's how JSON-LD works. Everything that has a value that is an @id is a relationship (if the @id is defined somewhere else).

Nested structures are not necessary for the relationship use case

**Comment by bogdanromanx** [comment]
I think we may indeed need a list there... because I think that we need to detail the path, meaning that:
```
"contribution": {
    "agent": "https://schema.org/Person"
  }
```
... will not suffice, we may need something like this instead (to be modified for json-ld representation):
```
[
  {
    "_name": "contribution",
    "@id": "https://.../contribution"
  },
  {
    "_name": "agent",
    "@id": "https://.../agent",
    "@type": "https://schema.org/Person"
  },

]
```

**Comment by umbreak** [comment]
I don't think we need to use anything custom to provide the compacted/expanded form of a predicate. JSON-LD already supports that, and that's why you have 2 representations: compacted and expanded

**Comment by bogdanromanx** [comment]
Because the client would need both, the short form by default and the full Iri on hover.

**Comment by umbreak** [comment]
> Because the client would need both, the short form by default and the full Iri on hover.

If the client is JSON-LD aware (they should) that's not a problem.

**Comment by umbreak** [comment]
For now (before proper JSON-LD support on the client side is implement) we would do it as follows:

```json
{
  "_nodes": [
    {
      "@id": "https://neuroshapes.org/Trace",
      "_name": "Trace",
      "_count": 3567
    }
  ],
  "_edges": [
    {
      "_source": "https://neuroshapes.org/Trace",
      "_target": "https://neuroshapes.org/PatchClamp",
      "_count": 3000,
      "_path": [
        {
          "@id": "https://neuroshapes.org/generatedBy",
          "_name": "generatedBy"
        }
      ]
    },
    {
      "_source": "https://neuroshapes.org/Trace",
      "_target": "https://neuroshapes.org/Person",
      "_count": 3000,
      "_path": [
        {
          "@id": "https://neuroshapes.org/contribution",
          "_name": "contribution"
        },
        {
          "@id": "https://neuroshapes.org/agent",
          "_name": "agent"
        }
      ]
    },
    {
      "_source": "https://neuroshapes.org/Trace",
      "_target": "https://neuroshapes.org/Person",
      "_count": 100,
      "_path": [
        {
          "@id": "https://neuroshapes.org/contribution",
          "_name": "contribution"
        }
      ]
    }
  ]
}
```
