### ISSUE TITLE
Support JWT "aud" (audience) claim

### ISSUE THREAD

**Issue by kaij** [BlueBrain/nexus#2546]
### Motivation
We are using Nexus with a custom API Gateway ("API") which itself uses the Nexus Keycloak ("Keycloak") to issue API tokens. The motivation behind this is to restrict access and channel specific users through the API, which also provides domain-specific use-cases. The API Gateway should however preserve the original user identity in face of Nexus Delta, such that access remains transparent (i.e. identities, access permissions and histories stay the same within Delta).

In order to implement this, we tested the following method:

- API tokens are issued with specific "aud" claim ("api-gateway")
- API rejects tokens which were not issued for this audience
- API uses Keycloak OIDC Token Exchange (see https://www.keycloak.org/docs/latest/securing_apps/#_token-exchange) to fetch a valid Nexus Delta Token for the given user identity using the API access token ("exchange API token with Nexus token for the given user identity")

This works surprisingly well. However the problem we are facing is that tokens issued for the API are also accepted as valid tokens on Nexus Delta (and of course Nexus Fusion/CLI). This happens because Nexus Delta currently accepts any token issued by the configured Keycloak server.

### Proposed solution
Implementing support for the "aud" claim when checking the access token within Nexus Delta would allow 3rd party integrator applications (like our API) to use Keycloak in this manner, while not changing any of the key infrastructure mechanisms.
 
- Implement configuration option to force audience checks
- Implement support for "aud" claim according to https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3 (could be implemented as optional if no configuration is given)

Checking for a valid audience could be added to the current token check. If the given audience(s) are not within the configured values, the token is rejected.

**Comment by umbreak** [comment]
From what I've read about [audience claim](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3) in the JWT token, it is an optional field and its function is application specific.

That said, we could have in our configuration the following:

```
app {
   ...
   identities {
      ....
      acceptedAudiences = ["a", "b"]
   }
}
```

And when the JWT token is used, Nexus will also check if some of the strings contained in the `aud` JWT are also contained in the configuration. 

If the configuration `app.identities.acceptedAudiences = []` then the `aud` field in the JWT token is being ignored.

**Comment by umbreak** [comment]
The other option is to have the `acceptedAudiences` configured by the realm and not by static configuration.

**Comment by kaij** [comment]
> The other option is to have the `acceptedAudiences` configured by the realm and not by static configuration.

In our use case, application access and realm users are independent of each other, i.e. different users in the same realm have different access to applications. So configuration per realm would not work (if this is what you meant). The solution in https://github.com/BlueBrain/nexus/issues/2546#issuecomment-880689671 however would work perfectly fine.

**Comment by umbreak** [comment]
If the first solution would work for you, the second solution should work too:

- Solution 1 defines a global `acceptedAudiences` for all the delta app (regardless of the realm)
- Solution 2 defines an `acceptedAudiences` per realm. If you want to achieve the same results as in 1) you just need to define the same `acceptedAudiences` across all your realms.

Is there something I'm missing, @kaij ?
