### ISSUE TITLE
Transformation before ElasticSearch indexing

### ISSUE THREAD

**Issue by kaij** [BlueBrain/nexus#2549]
### Motivation
JSON-LD documments sometimes have different nesting structure than what is required for ElasticSearch indexing. These  nesting requirements can not be solved with `copy` mappings in the index settings as `copy` cannot create new nestings.

#### Use case 1: Date range indexing
A good example to illustrate this is the use case of "date range" indexing and aggregations over date ranges: a https://schema.org/Event uses the properties `startDate` and `endDate` to denote a time interval. ElasticSearch mapping requires a nested structure for correct range mapping (see https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html):
```
{
     "event_date": {
          "gte": "2021-10-31 12:00:00",
          "lte": "2021-11-01"
     }
}
```
where `gte` equals `startDate` and `lte` equals `endDate`. By using the correct mapping, we can e.g. do date range aggregations as described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html. This is used often to visualize historical distribution of documents (histograms). Instead of events, we can also 

#### Use case 2: Language mappings
JSON-LD documents may contain language declarations as described in https://datatracker.ietf.org/doc/html/rfc5646. For an example refer to the description of IIIF Manifests at https://iiif.io/api/presentation/2.0/#language-of-property-values. An exanple in the wild can also be seen here: https://energy.ld.admin.ch/elcom/electricityprice?format=jsonld.
```
{
   "description": [{
        "@language": "de",
        "@value": "<eine deutsche Beschreibung>"
   }, {
        "@language": "en",
        "@value": "<an english description>"
   }]
}
```
For the correct multilingual indexing, german values need to be indexed with a different indexing chain (analyzers, stemmer tokenization, stopwords, synonyms, ...). With Nexus 1.5 these can be correctly defined in the index settings for the ElasticSearchView. However, it is not possible to map the above structure to the correct multilingual fields.

#### CompositeView
It is possible to define a Nexus CompositeView with suitable SPARQL transformation to create the documents. However, this might have an impact on performance and storage requirements for larger amounts of data. It seems to be an overkill as only a simple transformation step is needed for the required structures, not an aggregation or enrichment over different sources.

#### Transform with external process (or on import)
Use custom document properties outside document schema ("_eventdate") which are created by an external process. This has the huge drawback of "polluting" and modifiying the original data.

### Proposed solution
Ideally, it would be possible to define a simple transformation script in the index definition. This could be
1. either a SPARQL construct query as used in the CompositeView
2. an embedded scripting language function (e.g. Javascript using javax.script)

The transformation step can be defined as optional and permissions for modifications are derived from permissions on the ElasticSearchView ressource itself.

**Comment by kaij** [comment]
Side note for use case 2: if data is structured according to https://w3c.github.io/json-ld-syntax/#example-71-language-map-expressing-a-property-in-three-languages (language map with @container), it should be possible to index the data correctly without transformation. However, this kind of structure can not be guaranteed.

**Comment by umbreak** [comment]
Thanks for the thorough explanation. It makes a lot of sense to have something like that supported.

If the goal is to transform the data within the existing payload of the document (all the information you need, you have it in each Event) then a solution like  [ElasticSearch pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/current/pipeline.html) should be the way to go.

We could consider this solution or any of your suggested solutions for the future. We'll plan accordingly with the rest of the team and let you know about an ETA.

**Comment by kaij** [comment]
Oh yes, ES pipelines definitely look interesting and I'm pretty sure they would solve all these cases. Thanks for looking closer into this!

**Comment by wwajerowicz** [comment]
I think there are a few options which we could use to implement this kind of functionality:
- create an in memory Jena model of the resource and run SPARQL query on it
- expand the JSON-LD and compact it using another context defined in the view
  The two above options shouldn't be too complicated.
- elasticsearch pipelines
   a bit more complicated, because it needs change to ES configuration to enable [ingest mode](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#node-ingest-node) on some nodes

**Comment by umbreak** [comment]
I understand that options 1 and 2 have to be used combined in order to achieve what @kaij mentions.

I'd add an option 4 which would be more involved but it would allow us to have more control and flexibility:
4. Have a custom plugin for ES views transformations. Usually clients would need to just implement a simple interface. The very minimal would be something like this (this could be then implemented in Scala or Java):
```scala
trait ElasticSearchTransformation {

  // The name of the transformation plugin
   def name: Label
   
   // Converts the event to the desired data to be indexed
   def transform(exchangedValue: EventExchangeValue[_, _]): IndexingData
}
```

We could then discover those plugins using dependency injection and then when building an ES view there should be an extra field:
```
{
   ...
   "transformation": "myTransformationPlugin"
   ...
   
}
```

**Comment by umbreak** [comment]
An specialization of that plugin can be the one that @wwajerowicz mentions in 1) and 2)
```scala
trait ElasticSearchSparqlTransformation {
   def query: SparqlQuery
   def context: ContextValue
   def name: Label
}
```
(we can then derive `ElasticSearchTransformation` from this information by creating a jena model, running the provided sparql query against it and generating the `IndexingData` output)

**Comment by imsdu** [comment]
The trait is still a little bit complicated what about something like this:

```
trait ElasticsearchTransformation {

  def identifier: Label
  
  // HOCON being a superset of Json, we could just use it and people can still use json if they prefer
  def config: Config

  // It will be easier for people just to deal with Circe/circe-optics and just to modify json
  def transform(json: Json): Task[Json]

}

object ElasticsearchTransformation {
  
  // To register in distage to know how to create the transformation of a given label, we will need something like this too
  final case class Factory(label: Label, make: Config => Task[ElasticsearchTransformation])

}
```

**Comment by umbreak** [comment]
This signature is not enough:
```scala
def transform(json: Json): Task[Json]
```

Not even for our [current](https://github.com/BlueBrain/nexus/blob/master/delta/sdk-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/views/model/IndexingData.scala#L70) (and simple) use case.

1. The interface needs to have access to `sourceAsText`, `includeMetadata`. This could be part of the `Config` but it seems obfuscating.
2. The interface needs to have access to all the resource representations and not only the json (btw what does it mean Json? The compacted? The expanded? the source?)

If we decide to allow a chain of transformation we could have what you described, **plus** some others:

```scala
trait ElasticsearchSourceTransformation {

 // identifier and config ...

  def transform(json: Json): Task[Json]

}
```

```scala
trait ElasticsearchGraphTransformation {

 // identifier and config ...

  def transform(metadata: Graph, value: Graph): Task[Json]

}
```

```scala
trait ElasticsearchExpandedJsonLdTransformation {

 // identifier and config ...

  def transform(metadata: ExpandedJsonLd, value: ExpandedJsonLd): Task[Json]

}
```

```scala
trait ElasticsearchCompactedJsonLdTransformation {

 // identifier and config

  def transform(metadata: CompactedJsonLd, value: CompactedJsonLd): Task[Json]

}
```

And so the client could provide multiple transformations and we would run them all:

```json
{
   "@type": "ElasticSearchView",
   "transformations": [
     {
        "name": "mySourceTransformation",
        "@type": "SourceTransformation",
        "config": {"customKey": "customValue"}
     },
     {
        "name": "myGraphTransformation",
        "@type": "GraphTransformation",
        "config": {"customKey": "customValue"}
     },   
     {
        "name": "myJsonLdTransformation",
        "@type": "JsonLdTransformation",
        "config": {"customKey": "customValue"}
     },        
   ]
}
```

**Comment by imsdu** [comment]
Sorry not to have been clearer in my example, I was thinking that:
* the operations on `sourceAsText`, `includeMetadata` were happening before
* the json is the generated json after all these operations (what would be indexed to ES if no additional transformations)

**Comment by umbreak** [comment]
What I was suggesting from the beginning was something more powerful and custom, something that would let us refactor even our own current logic on the elasticsearchview transformation[[1]](https://github.com/BlueBrain/nexus/blob/master/delta/sdk-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/views/model/IndexingData.scala#L70) [[2]](https://github.com/BlueBrain/nexus/blob/master/delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/indexing/ElasticSearchIndexingStreamEntry.scala#L73) while at the same time can give clients the full flexibility.

The other use case to have in mind is the @jonathanlurie use case, where he wants to control the output format of the ES documents on an index (for that one could use a `CompactedJsonLdTransformation` or `ExpandedJsonLdTransformation`)

**Comment by smitfire** [comment]
@adulbrich @imsdu @nicwells @samuel-kerrien @Stafeeva @wwajerowicz Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2549?planning-poker)
