### ISSUE TITLE
Fix data table actions and layout

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2556]
Actions in the dropdown menu:
- Download as CSV
- Add to the Cart
- Edit
- Delete (in red, with confirmation pop-up)

Must be a self-contained component.

Details in the comments below.

**Comment by adulbrich** [comment]
@nicwells UI/UX for Table (requirements will come later):

- Table Creation from Project (from scratch using project graph statistics): https://xd.adobe.com/view/f4afd29f-11b3-486f-838c-46d356286073-a1fc/?hints=off
- Table Creation from Search Results (from the global index, not statistics): https://xd.adobe.com/view/8ac356ae-0294-45d6-b2bc-c17441c9f780-df90/

⚠️ The prototypes above are being improved daily, they are not final nor validated yet.

**Comment by adulbrich** [comment]
An preliminary draft of the read-only table:

![image](https://user-images.githubusercontent.com/11705901/122888006-b8b2e980-d341-11eb-9c77-dfb37cc2804c.png)

**Comment by nicwells** [comment]
Have updated the layout of the data table to match more closely to your design for the read-only table @adulbrich , see below.

#### Existing Data Table (for reference)

<img width="1043" alt="2556-data-table-original" src="https://user-images.githubusercontent.com/11296166/123133015-9dce9b00-d44f-11eb-8cb4-02c12f83f5a5.png">

#### New table Data Table

* Moved the table title to be inline with the search box
* Reduced size of search box and aligned to the right
* Minimised the search box when not active. Expand (with short transition) the search box when focused or has a value

![2556-data-table-layout-change](https://user-images.githubusercontent.com/11296166/123132616-36185000-d44f-11eb-96e7-63f402e6fdb4.gif)

Is that what you had in mind @adulbrich ? The sorting options are being addressed here https://github.com/BlueBrain/nexus/issues/2314 I think. What else is within scope for this issue?

**Comment by adulbrich** [comment]
@nicwells it looks good like this!

**Comment by adulbrich** [comment]
`Add from Cart` button should not be there or be disabled if not working:

![image](https://user-images.githubusercontent.com/11705901/130455799-41187552-1b84-4cf7-88f8-2f57f0f020bd.png)
