### ISSUE TITLE
PDF Viewer Plugin

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2566]
If a Dataset distribution contains one or more PDF files, the user would like to see the file directly in a plugin instead of downloading it to view it.

There might be more than one PDF file and we need a way to navigate the files/select the file of interest in the plugin.

We are only interested in viewing/browsing/searching the PDF file(s), not edit or change it.

### Acceptance criteria
* Plugin shows only when resource is a dataset with a distribution containing PDF files
* PDF files within distribution are listed
* User can select a PDF file which will open a preview of the pdf
* PDF Preview shows PDF contents inline on page large enough to read the contents
* PDF Preview shows number of pages in pdf, the current page and controls to change page

**Comment by nicwells** [comment]
### Acceptance criteria
* Plugin shows only when resource is a dataset with a distribution containing PDF files
* PDF files within distribution are listed
* User can select a PDF file which will open a preview of the pdf
* PDF Preview shows PDF contents inline on page large enough to read the contents
* PDF Preview shows number of pages in pdf, the current page and controls to change page

**Comment by nicwells** [comment]
### Demo
![PDF_Viewer_demo](https://user-images.githubusercontent.com/11296166/124485868-4adcd800-ddad-11eb-908f-8cee38e54f4b.gif)

### Questions
* Feedback on demo above?
* Acceptance criteria met? Anything additional?
* This is similar to the Download files plugin, tsv/csv plugin and youtube plugin. Do we want to keep these as separate plugins or would it be worth combining?

XD mock-up next time...

@adulbrich

**Comment by adulbrich** [comment]
Answers @nicwells 

- Feedback on demo above? **It looks great!**
- Acceptance criteria met? Anything additional? What happens on smaller screens? **Can users easily zoom in on the document? Otherwise, it meets the criteria!**
- This is similar to the Download files plugin, tsv/csv plugin and youtube plugin. Do we want to keep these as separate plugins or would it be worth combining? **It is totally worth combining...**
