### ISSUE TITLE
Fusion: Saving/Deprecating views results in 404

### ISSUE THREAD

**Issue by kaij** [BlueBrain/nexus#2570]
### Steps to reproduce:
1. Create new resource of type "ElasticSearchView" (or SparqlView), wait until indexing is finished
2. Click on the resource in the Admin View, insert a space in the JSON view and remove the space right away (so the resource appears to have changed)
3. Click on "Save"
4. This will issue a PUT request to `${HOST}/v1/resources/SW/cleaned_0505/${ORG}/${PROJ}/${ID}` which will fail with HTTP 404

### Analysis
If the PUT request would go to `/v1/views/...`, the resource is saved correctly. I tested this directly on the Delta API.

### Possible fixes
Either Fusion is handling views differently using the `views` endpoint or the `resources` endpoint is enabled to handling views.

**Comment by jonathanlurie** [comment]
Hey, just to let you know that this issue is also present when using `DELETE`.
