### ISSUE TITLE
Global Search UI

### ISSUE THREAD

**Issue by dhaneshnm** [BlueBrain/nexus#2575]
Redo the current search UI to match new mocks.

Link to the Mock : https://xd.adobe.com/view/50ef3eb0-46be-4b49-8e1a-6232cedf127e-05bc/

- Current search UI has lots of elements (search bar, facets etc) that is common with the new mocks. The idea is to keep the over lapping elements and add the missing elements in the UI. 
-  Update the color scheme of the current search UI  to meet the new mocks.

Sub-tasks
- Update the ES query building logic to match new mocks 3SP #2576
- Different facets types: single select, implement multi-select 3 SP
- Search property values in facets (works already)
- Counts of property values in facets (for relevant property types) (works already)
- Full-text search on specific "text/string" properties 2 SP
- Result cards (for neuron morphologies) 1 SP
- Align layout/design with new mocks 1 SP

**Comment by adulbrich** [comment]
Let's review the following as well:

- https://github.com/BlueBrain/nexus/issues/2163

**Comment by adulbrich** [comment]
old issue
