### ISSUE TITLE
Definition of the properties required to demonstrate Global Search on neuron morphologies

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#2577]
#### Summary

| Column Name | Column Type | Path | MINDS | Example | Data Type |
| -------------- | ------------- | ----- | ------- | -------- | ---------- |
| Project | Multi-Select |  |  | public/sscx |
| Types | Multi-Select | `@type` |  | Entity, Dataset, Trace
| Name | Full-Text Search | `name` or `label` or `prefLabel` in that order |  | C231296A-P4A2 |
| Description | Full-Text Search | `description` |  | This dataset is about electrophysiology traces recorded from cell 001150217A1CA1pyMPG for the project Adaptive Stimulus Set. The dataset contains one distribution of the traces in NWB file format.
| Brain Region | Multi-Select | `nsg:brainLocation / nsg:brainRegion / rdfs:label` | Yes | primary somatosensory cortex |
| Subject Specie | Multi-Select | `nsg:subject / nsg:species / rdfs:label` | Yes | rattus norvegicus |
| Contributors | Multi-Select | `nsg:contribution / prov:agent` optional `/ schema:givenName` and `/schema:familyName` | Yes | John Doe |
| Organisation | Multi-Select | `nsg:contribution / prov:agent` optional `/ schema:name` | Yes | EPFL (École polytechnique fédérale de Lausanne) |
| License | Multi-Select | `nsg:license` | Yes | Attribution 4.0 International (CC BY 4.0) |
| Distribution |  |  | Yes |
| M-Type | Multi-Select | `nsg:annotation / nsg:hasBody` filter `"@type":"MType"` then `/ rdfs:label` |  | L1_DAC | Neuron Morphology
| Nexus Registrator | Multi-Select | `_createdBy` |  | ulbrich
| Nexus Registration Date | Date Range | `_createdAt` |  | 2020-04-07T14:59:17.089Z
| Nexus Tag | Multi-Select |  |  | SSCX2021

#### Generic (Nexus) Properties:

- Nexus Registrator: nxv:createdBy ?registered_by
- Nexus Registration Data: nxv:createdAt ?registeredAt

#### MINDS properties:

- Brain Region (facet, multi-select): nsg:brainLocation / nsg:brainRegion / rdfs:label ?brainRegion 
- Subject Specie (facet, multi-select): nsg:subject / nsg:species / rdfs:label ?subjectSpecies 
- nsg:contribution / prov:agent ?agent 
- Agent Role (full-text search): OPTIONAL { nsg:contribution / prov:hadRole / rdfs:label  ?role }
- License (facet, multi-select): nsg:license / ...
- Contributor Name (full-text search): 
  - OPTIONAL { ?agent schema:givenName ?givenName } + OPTIONAL { ?agent schema:familyName ?familyName }
- Organisation Name (full-text search): OPTIONAL { ?agent schema:name ?orgName }

> Some properties come from traversals, such as Agents.

#### Support for  Neuron Morphology (nsg:NeuronMorphology):

- M-Type (facet, multi-select):
  - schema:name ?name
  - nsg:annotation / nsg:hasBody ("@type":"MType") / rdfs:label ?mtype

- More annotations to support MCAR? TBD

Resource Example: https://bbp.epfl.ch/nexus/web/public/sscx/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fneuronmorphologies%2F91297885-2978-458e-b2a5-c8e77c6f44f4

[Neuron Morphology (protected)](https://docs.google.com/document/d/16CtjLsAihSHkv0PMJv_R65t3cOP4Q2LBfou7iJfkDK8/edit#heading=h.9ajt68y446wn)

### Out of scope

- Subject Age (full-text search or need to standardize to specific unitCode for range facet):  
  - OPTIONAL { nsg:subject / nsg:age / schema:value ?ageValue } + OPTIONAL { nsg:subject / nsg:age / schema:unitCode ?ageUnit } (OPTIONAL { nsg:subject / nsg:age / nsg:period ?agePeriod })
- Layer (facet, multi-select): nsg:brainLocation / nsg:layer / rdfs:label ?brainLayer

**Comment by adulbrich** [comment]
@MFSY @annakristinkaufmann Could you please confirm that the properties above are correct? We want to enable global search on them, starting with neuron morphologies. Do you see other annotations or facets that would be relevant for neuron morphologies?
