### ISSUE TITLE
Unsupported new grant types in keycloak

### ISSUE THREAD

**Issue by carolili** [BlueBrain/nexus#2580]
Delta only supports a fixed collection of grant type realm properties, which leads to failure to create a realm on recent Keycloak installations (tested with Keycloak 14).

Two new grant types have been introduced: 
- `urn:ietf:params:oauth:grant-type:device_code`
- `urn:openid:params:grant-type:ciba`

Proposed change: Introduce a new wildcard grant type that will allow decoding newly introduced grant types. Alternately, modify the well-known support to parse grant types as arbitrary strings.

**Comment by umbreak** [comment]
well-known uri to test: https://sandbox.bluebrainnexus.io/auth/realms/service-accounts/.well-known/openid-configuration
