### ISSUE TITLE
Enable jump to studio from the search bar

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2611]
### Acceptance Criteria

- the user types the name of the studio in the search bar
- the search bar lists the top three studio matches across all studios the user has access to
  - the user will see a text saying "Jump to Studio in `{org}/{proj}`"
  - the search takes into account the name of the studios
- the user can click on the dropdown item, which will open the correct studio

### Out of scope

Studios should be first-class citizens (at one point, not for now):

- better indexing support
- migration support
- should not be mixed up with domain-specific indexing

**Comment by smitfire** [comment]
@adulbrich @nicwells @imsdu @samuel-kerrien @Stafeeva @wwajerowicz Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2611?planning-poker)

**Comment by nicwells** [comment]
Use the all projects resources endpoint, https://bluebrainnexus.io/docs/delta/api/resources-api.html#within-all-projects

GET /v1/resources?from={from}
                 &size={size}
                 &deprecated={deprecated}
                 &rev={rev}
                 &type={type}
                 &createdBy={createdBy}
                 &updatedBy={updatedBy}
                 &schema={schema}
                 &q={search}
                 &sort={sort}

**Comment by nicwells** [comment]
Should look like this:

![Searchbar-studios.png](https://images.zenhubusercontent.com/60f166b8ed7312d557030820/b5354fbb-1df6-4f31-aa2a-614edda2a631)
