### ISSUE TITLE
Ability to filter search results based on known values

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2614]
**Acceptance Criteria**:

- The columns in the search results should include a dropdown icon, that when clicked it displays sorting and filtering options as a menu
- The column menu will include a filtering section
  - the filtering section starts with a header, `Filter`
  - the filtering section displays a user choice on how the filtering logic should be executed, in two variations, where the first option is automatically selected:
    - if the column is single-valued (array=false) the following filtering criteria will be proposed: `is any of`, `is none of`
    - if the column is multi-valued (array=true) the following filtering criteria will be proposed: `is any of`, `is none of`, `is all of`
  - the possible values for that field are displayed along with the counts and the ability to select each individual value
    - if the count is over 10,000, the filter section will only display 10K+
    - a select all value is included at the top, is selected by default and its count should reflect the count of applying the filtering criteria to all selected possible values (note: will differ for multi-valued columns and the filtering criteria)
    - a search box is presented at the top of the possible values, that allows filtering the candidate values based on a simple "string contains" logic; any keypress within the search box will automatically update the list of possible values, keeping only the ones that match the search box input
    - the filter menu should only display 5 entries (select all + 4 most common values - where common means count) and the list of possible values should present a scroll
  - upon changing the filtering criteria, the search result list displayed should be automatically updated (e.g. if I select another value, the counts presented in the menu should be updated along with the search result list)
  - any column that has a filter applied should present a visual indicator to inform the user that the result list is filtered

- changing any filtering criteria (add, remove, switch) should reset the pagination to 1; the results per page is not modified

**Comment by adulbrich** [comment]
When un-selecting every choice in the column dropdown filter. and clicking apply, the filter is still considered "active":

![image](https://user-images.githubusercontent.com/11705901/133202444-31061217-9b7d-499a-924e-a350a0127c3c.png)

**Comment by adulbrich** [comment]
Not all values are displayed in the filter. 

In the example below, if I search for "vd101102b_INT_idA", there is no result while it is clearly a valid name taken from the column.

![image](https://user-images.githubusercontent.com/11705901/133203355-e36ea27a-b469-4ab1-908a-059ba0048033.png)

![image](https://user-images.githubusercontent.com/11705901/133203486-7d671d42-73ea-4a08-a6ef-d3839fcd49fd.png)

**Comment by adulbrich** [comment]
Types cannot be filtered while it should be "multi-valued":

![image](https://user-images.githubusercontent.com/11705901/133204131-7a26f856-d386-4b15-92ba-6f2883d08297.png)

**Comment by adulbrich** [comment]
Brain region is considered multi-valued while it should be single-valued:

![image](https://user-images.githubusercontent.com/11705901/133204250-5666185a-5d8d-41b5-a63c-11dfffe14de8.png)

**Comment by adulbrich** [comment]
Failed acceptance criteria:

- changing any filtering criteria (add, remove, switch) should reset the pagination to 1; the results per page is not modified

In the example below, we navigate to a further page, then add a filter on the brain region. The search result table appears empty because the pagination is not reset.

https://user-images.githubusercontent.com/11705901/133204679-4972f98b-6464-456d-a008-4acb3f9eec04.mp4

**Comment by adulbrich** [comment]
Operator labels should be:

- "is none of"
- "is any of (OR)"
- "is all of (AND)"

Don't capitalize the "o" of "of".
