### ISSUE TITLE
Manage token lifecycle

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#262]
child of #228
Finish implementing Implicit flow.
When token has expired remove it.
When the token is about to expire, do a silent auth.
More details can be found here: https://auth0.com/docs/api-auth/tutorials/implicit-grant

**Comment by olinux** [comment]
Removing the token after it expired would be highly appreciated. If I do it myself (removing it from the cookies), I additionally expect the strange behavior that the login-button disappears. At some point it comes back (still investigating under which conditions).

**Comment by julienmachon** [comment]
Yes, I'm hoping to finalise my PR today. Token will be renewed silently if possible, otherwise user will be invited to login again.

Keep me up to date with the login button disappearing. As long as you have a ACL for `Anonynous` on `/` with the `realms/read` permission, it should display. I'll investigate on my side as well

**Comment by olinux** [comment]
It definitively comes back if I recreate the server... :) Caching issue?
