### ISSUE TITLE
Enable "missing" choice in the column filter

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2641]
Some fields might be optional in the query which will result in empty cells in the table.
Users might want to filter to only get the resources/rows that have missing values. 
Hence, we should be able to filter columns based on cells that are empty.

Acceptance Criteria:

- when there are missing values for a property/column, the users can select them through the operator dropdown
  - if nothing is missing, the "(Missing)" in the list will not show
  - the "is missing" operator will not show on columns that cannot have missing values (such as projects, types)
  - the "(Missing)" value will behave like any other value when filtering and might get greyed out
- selecting the "is missing" operator will display all rows in the table that have an empty cell for that column/property and the count of rows
  - the list of possible values will include a label "(Missing)" and the count of empty cells
  - the "(Missing)" value is then selected and the count shown

Notes:

- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-missing-aggregation.html
- add ability to mark fields as`optional` in the config

Tasks:

- [x] Modify search config in Delta
- [ ] Add behaviour in Fusion

![image.png](https://images.zenhubusercontent.com/60acdfe3916bb919fdfffe58/cfe909b5-a43f-4a84-af18-fc732b7e9508)

**Comment by smitfire** [comment]
@adulbrich @nicwells @imsdu @samuel-kerrien @Stafeeva @wwajerowicz Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2641?planning-poker)
