### ISSUE TITLE
Display values for which the count is null as greyed out (not selectable) in the column filter

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2642]
Use case 1: Ontologies
Ontology values might not be present in the data (e.g. brain regions) hence the count of resources will be null, but we want users to still be able to see all possible values.

Use case 2: Subfilters
When filtering on multiple columns, the count of resources will gradually go down. The counts need to update for other columns' values. A specific value might have a count of zero after filtering by another. For example, a specific project might only have a specific brain region indexed. Users want to see that other brains regions exist but are not available in the selected project.

Acceptance Criteria:

- the user filters column A on a specific value, as a result, a value in column B becomes unavailable
- when a value is unavailable, e.g. filtering on column B, the user sees that value greyed out, with count 0, and cannot select it

Not in scope:

- ontology support

![image.png](https://images.zenhubusercontent.com/60acdfe3916bb919fdfffe58/1623a915-82c4-454e-bedc-a133f427cc82)

**Comment by smitfire** [comment]
@samuel-kerrien @Stafeeva @wwajerowicz Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2642?planning-poker)

**Comment by smitfire** [comment]
@adulbrich @imsdu @nicwells Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2642?planning-poker)

**Comment by adulbrich** [comment]
Not working yet, re-opened. Please check https://app.zenhub.com/workspaces/blue-brain-nexus-60ace035034cae00105c9307/issues/bluebrain/nexus/2783 as well.

**Comment by nicwells** [comment]
Confirmed it was working in the commit but no longer working in epic branch so some merge must have broken it. Looking into to fix
