### ISSUE TITLE
Allow re-ordering of columns for presentation purposes

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2643]
Use Case 1: Data Types
Different data types might warrant different views of the listed resources. Some fields might want to be showcased, for example, the m-Type or e-Type for morphologies and electrophysiologic respectively.

Use Case 2: Publishing or Presentation
Similarly, when using the configured search results in another part of the app, for example in Studios, the users might want to re-order the columns for the targeted audience.

Acceptance Criteria:

- In the hidden/hide fields dropdown, the user can drag a specific column to change its location in the table, compared to other columns
  - Once the column has been dropped in the menu, the table is immediately updated as well
  - Hovering the drag icon will be noticeable by the user (see interactive demo below)
- Similarly, a user can drag the header of a column to change its location in the table, compared to other columns
  - The column is then moved immediately after being dropped: see for details https://codepen.io/raisezhang/pen/MoMoyz
- The ordering is saved for the user so that when he comes back to the search interface, the chosen column ordering is kept

Not in scope:

- non-search tables (studio, workflows, ...)

![image.png](https://images.zenhubusercontent.com/60acdfe3916bb919fdfffe58/c1ad69b1-f0db-4b21-92b2-5a47716b48aa)

See https://xd.adobe.com/view/50ef3eb0-46be-4b49-8e1a-6232cedf127e-05bc/ for interactive demo

**Comment by smitfire** [comment]
@adulbrich @dhaneshnm @imsdu @nicwells @Stafeeva @samuel-kerrien @umbreak @wwajerowicz Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2643?planning-poker)

**Comment by adulbrich** [comment]
Failed Acceptance Criteria:

- Hovering the drag icon (in the hide column menu) will be noticeable by the user (see interactive demo)
- Similarly, a user can drag the header of a column to change its location in the table, compared to other columns
The column is then moved immediately after being dropped: see for details
