### ISSUE TITLE
Allow users to switch between different default search table configurations (e.g. specific data types)

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2644]
Specifically, types such as Neuron Morphologies or Neuron Electrophysiologies might have different fields/columns that are not relevant for the other. The users would be able to switch between different configurations that have different: column ordering, hidden columns, filters, sorting.

At the deployment level, default configurations can be created and will be accessible to all users (anonymous as well).

A configuration saves the following parameters:

- column order
- hidden columns
- filters
- sort criteria

Expected behavior:

- A default deployment configuration will have a name and a description
- Multiple configurations can exist
- Configurations can be selected in the search app (i.e. through the configuration dropdown menu)
- Switching to a configuration will apply the corresponding above parameters to the interface 

Mocks:

![image](https://user-images.githubusercontent.com/11705901/142233965-d6b8d070-dc4a-44ee-8446-612758f502bd.png)

![-nexus-web-search – MINDS Configuration](https://user-images.githubusercontent.com/11705901/142234921-9fb29185-70ca-438a-87ca-c91e8d197077.png)

Out of scope:

- column width
- decimal digits
- row height
- searching on a config from the search bar
- merging filters and sort criteria on config switch
- temporary config save (user local storage)
- sharing link to config (incl. deployment ones)

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2644?planning-poker) with ZenHub @adulbrich @imsdu @nicwells @smitfire @wwajerowicz
