### ISSUE TITLE
Update nexus.js to support quota endpoints

### ISSUE THREAD

**Issue by Stafeeva** [BlueBrain/nexus#2656]
Part of BlueBrain/nexus#2525

`nexus.js` needs to be updated to support quota endpoints
- an API call will return the project quota on read (e.g. GET /v1/quotas/{org}/{proj})
- an API call will allow updating the project quota (e.g. PUT /v1/quotas/{org}/{proj})

**Comment by adulbrich** [comment]
moved to comment in #2525
