### ISSUE TITLE
Indexing storages via synchronous indexing does not properly encrypt the source

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#2658]

**Comment by adulbrich** [comment]
@dhaneshnm @imsdu @nicwells @Stafeeva @umbreak Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2658?planning-poker)

**Comment by umbreak** [comment]
The indexed version of storages in Elasticsearch & Blazegraph will contain the decrypted values. That's what has to be fixed
