### ISSUE TITLE
Redesign the resource details view to better fit the side panel

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2709]
Acceptance Criteria:

- The name/label/preflabel of the resource is displayed at the top
  - Clicking on it will open the resource detail view in a new tab
- The organization and project are displayed at the top
  - Clicking on the org name or project name open the organization, resp. the project, in a new tab
- The types of the resource should be listed
- A deprecation message is displayed if the resource is deprecated
- A "Write Access" message is displayed if user has write permissions on the resource
- The creator (to be moved from the admin plugin), creation date (to be moved from the admin plugin), and last updated date are displayed at the top for information
- The user can click on a dropdown menu to change the revision of the resource
  - If there is a tag on a specific revision, it is showed in the dropdown menu
  - The latest revision has a mention "latest" to make it clear to the user he or she is browsing the latest revision
  - A information message is displayed if the user is not browsing the latest version
- The user can click to change the kind of URL that he or she wants:
  - the resource URL (fusion)
  - the resource URL with revision (fusion, default when not latest)
  - the resource ID (forge)
  - the resource ID with revision (forge)
  - the Nexus address (bbp-workflow)
  - the Nexus address with revision (bbp-workflow)
- The user can click to save that resource to the cart (to be moved from the admin plugin)
- The user can click on the top-right close button to close the view (side panel)

Acceptance Criteria for Resource View (when the resource is open by itself with its address):

- The resource view needs to take min 40% of the screen and max 60% for desktop screens
- The resource view is centered in the middle of the screen (excluding side navigation)
- The resource view takes the whole vertical space (excluding app header)

Not in scope: 

- changing the style of plugin collapsible panels (only the header and admin plugin needs to be adapted)

Example of the new resource header:

![Resource View Side Panel - Trace - Write Permission](https://user-images.githubusercontent.com/11705901/130450725-1b438d57-fe80-4c29-896f-87c5f43092e8.png)

![Resource View Side Panel - Trace - Deprecated](https://user-images.githubusercontent.com/11705901/130450729-a299fbcb-375e-4f04-bc22-bc9d397dce2e.png)

![Resource View Side Panel - Trace - Not Latest](https://user-images.githubusercontent.com/11705901/130450732-82d2b85e-1f65-4091-a323-4fdd68581238.png)

Layout example of the resource view alone (mocks to be updated):

![image.png](https://images.zenhubusercontent.com/60acdfe3916bb919fdfffe58/430b9d8e-d784-4188-91ee-86380a1f87c5)

**Comment by samuel-kerrien** [comment]
@adulbrich @dhaneshnm @imsdu @nicwells @smitfire @Stafeeva @umbreak @wwajerowicz Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2709?planning-poker)
