### ISSUE TITLE
Studio: New Data Table from Search

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2712]
### Workflow:

1. The user accesses StudioX
2. The user adds a new page element to PageY: "Create Data Table (from Search)"
3. The user is redirected to the Search page
4. The search page shows the user that he or she comes from {org}/{proj}/StudioX/PageY
5. The user queries the data in Search and formats the table to his or her liking
6. By default, the primary action button shows "Save Table in your Studio"
7. When the user clicks the button, he or she is redirected to the previous page (StudioX, PageY) and the configured table shows up where the action was performed. (unclear for now how this will happen)

### Acceptance Criteria:

- When a user accesses search from the "Create Data Table (from Search)" page element creation, the Search page displays a message saying that the user is coming from {org}/{proj}/{studio name}/{page name}: "You can now create your data table. When saving it, you will be redirected to {org}/{proj}/{studio name}/{page name}, where you will see your newly configured table."
  - The primary action button on the Search interface will show "Save Table in your Studio"
- When clicked, the filters, sorting criteria, and other formatting options (column order, visibility) of the table are saved. The user is redirected to the initial studio page, where he or she sees his or her newly configured table where he or she had chosen to place it.

## Notes:

- Risk: changing the search config might break the studio table (e.g. removing a property)
- Risk: Because we save the query, different users might see different results. That's ok, we should not let the users know.
- Risk: even the data not shown in a table might be returned from the query 
- Q? How will the new studio work? Pages? Page elements/sections? Old dashboards?
- Q? How will we make the old query-based (sparql, es, compositeview) table work with the new one? Styles have to match.

## Not in scope:

- freeze the results in time so that the table does not change if a resource gets updated
- let users query the search as "anonymous/public"

**Comment by smitfire** [comment]
@Stafeeva @samuel-kerrien @wwajerowicz Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2712?planning-poker)

**Comment by smitfire** [comment]
@adulbrich @imsdu Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2712?planning-poker)
