### ISSUE TITLE
Delete Projects: Check if project is being used anywhere before allowing deletion

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2723]
If the project requested to be deleted is being used by an `AggregatedView` or by a `CompositeView` or by a `CrossProjectResource` we should reject, pointing out on the details that first the client should modify the `AggregatedView` or `CrossProjectResource` or `CompositeView` to exclude the pointer to the requested project.

Until this is not done, it wouldn't be safe to introduce the deletion feature into staging/production

**Comment by samuel-kerrien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2723?planning-poker) with ZenHub @adulbrich @imsdu @nicwells @smitfire @Stafeeva @wwajerowicz
