### ISSUE TITLE
Pagination improvements

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2732]
Acceptance Criteria (see attached comments for details and videos of the problems):

- The pagination should be located at the top right of the screen, at the end of the search page "header" (the component that contains the filters, sort criteria, pagination, number of results, reset button, views, ...).
  - That header should take the view width and never appear off the page. Even if the table extends.
  - Currently, the pagination can be out of view when the table is larger: https://github.com/BlueBrain/nexus/issues/2623#issuecomment-906176512 
- When there are no results, the count should say "No results" and the pagination should be greyed out (inactive) showing only one page
  - Right now, when the search returns no results, the table jumps because the pagination disappears (see video below). 
- The text next to the pagination should say "x results" with x the total number of returned documents.

![image.png](https://images.zenhubusercontent.com/60acdfe3916bb919fdfffe58/e235da15-cace-45b0-ae23-0358a0785a96)

https://user-images.githubusercontent.com/11705901/131097092-d4cb79a7-9608-45b4-81e8-08693cc4a1f5.mp4

Please re-test the acceptance criteria of the following tickets once this is fixed:

- https://github.com/BlueBrain/nexus/issues/2623
- https://github.com/BlueBrain/nexus/issues/2610

**Comment by dhaneshnm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2732?planning-poker) with ZenHub @adulbrich
