### ISSUE TITLE
Youtube video plugin crashes if payload is missing some properties

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2765]
Some properties are not used in the plugin, such as:

- `duration`
- `thumbnailUrl`
- `uploadDate`

They are annoying to set and don't bring any extra information to the user, that would not already be present in the metadata.

In particular, if `thumbnailUrl` is not defined, the plugin crashes.

Acceptance Criteria:

- the plugin should load even if only the `embedurl` is provided
- if available, only display the name and descriptions next to the thumbnail
- let the plugin load even if some properties such as `duration`, `thumbnailUrl`, `uploadDate`, `description` are missing
- display a meaningful error message if a required field is missing to avoid the page crashing (`embedurl`)
- keep thumbnail, optional name, and optional description in the card

Note:

- could we retrieve duration and other metadata from the youtube public URL?

![image](https://user-images.githubusercontent.com/11705901/132226250-6b439d70-7db6-4d7a-a0eb-fc2886673dd7.png)

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2765?planning-poker) with ZenHub @adulbrich @bogdanromanx @dhaneshnm @imsdu @nicwells @samuel-kerrien

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/945
