### ISSUE TITLE
Add message to warn user of scheduled project deletion

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2772]
Acceptance Criteria:

When the automated deletion plugin is enabled and the endpoint returns the duration:
- Show the following message in the project view as an infobox/banner:
  -  If fixed duration after creation: "Your project and data will be automatically deleted on {projectCreatedAt + duration}. After that date, a new empty project will be created for you if you connect to Nexus again."
  -  If fixed duration after the last update: "Your project and data will be automatically deleted on {projectLastUpdatedAt + duration} if you don't update any resources until then. After deletion, a new empty project will be created for you if you connect to Nexus again."
- The DateTime should include the timezone (some users are located in another time zone).
  - Either the system timezone or the user timezone (preferred).
- The mocks should be validated with Alex.
- Add the project deletion information to the tutorial.

Endpoints: 
- https://bluebrainnexus.io/snapshot/docs/delta/api/projects-api.html#fetch-statistics
- https://bluebrainnexus.io/snapshot/docs/delta/api/version.html

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2772?planning-poker) with ZenHub @adulbrich @bogdanromanx @dhaneshnm @imsdu @nicwells @samuel-kerrien
