### ISSUE TITLE
Introduce PR and Issue Templates

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2775]
Issues

- state the why (background, context)
- acceptance criteria
- notes
- not in scope
- wireframes

- [ ] nexus

PRs

- linked to the original issue
- unit tests
- integration tests
- documentation
- if any new issues are created for debt or uncovered work

- [x] nexus-web
- [ ] nexus

For reviews, reviewer should tests the acceptance criteria?

**Comment by samuel-kerrien** [comment]
I would say yes to the last question, the review only makes sense in the context of the acceptance criteria.
