### ISSUE TITLE
Columns re-ordering improvements

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2790]
Notes

- The problem is that right now there is no visual indication whatsoever to the user that he or she can re-order columns.

Acceptance Criteria:

- Hovering the drag icon (in the hide column menu) will be noticeable by the user (see interactive demo): if this is too costly to do, we should display a message in italic and light gray at the top "_To re-order columns in the table, please drag and drop fields in the list below._" 

_Originally posted by @adulbrich in https://github.com/BlueBrain/nexus/issues/2643#issuecomment-919719467_

Not in scope:

- Similarly, a user can drag the header of a column to change its location in the table, compared to other columns
  - The column is then moved immediately after being dropped
_This would take much more time than anticipated._

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2790?planning-poker) with ZenHub @adulbrich @bogdanromanx @dhaneshnm @imsdu @nicwells @wwajerowicz
