### ISSUE TITLE
Improve Admin project view navigation

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2807]
Motivation:

Navigating features in the Admin project view is fairly confusing. We'll introduce a streamlined tabbed header to navigate between project features. This will also allow to more easily park new features such as graph statistics.

Acceptance Criteria:

- When a user accesses the admin project view, he or she is presented with:
  - A header with the org name and project name
  - A tabs navigation to the following elements:
    - Browse
    - Query
    - Create and Upload
    - Studios (direct link to the list of studios for this project in the studio sub-app, opens in a new tab)
    - Workflows (direct link to the list of workflows for this project in the workflow sub-app, opens in a new tab)
    - Settings
- The "Browse" tab will collect all the default query (resource list) functionalities
- The "Query" tag will collect all the query functionalities (select a view, write the query, execute it, see results)
- The "Create and Upload" tab will allow users to create a new resource (incl. from templates) and upload one or more files
- The "Settings" tab will include all features that are currently in the "Settings" pane in the project listing views AND the project permissions
- If the project is deprecated:
  - You can still: Browse, Query, Settings (read-only), Studios, Workflows
  - Create and Upload should be unavailable (greyed out)
- Settings should be removed from the project listing
- Refactor integration tests

![-nexus-web-org-proj#browse.png](https://images.zenhubusercontent.com/60acdfe3916bb919fdfffe58/c139ab74-4b97-473f-befb-cbe0c0553d2d)

Notes:

- visually show that studios and workflows open/redirect to another part of the app
- indexing status

Not in scope:

- The "Statistics" tab will be addressed separately #2557
- Show the description of the project in the header (unsure about the design, please propose something if time allows), to be addressed separately
- Show if the user has read or write permission on the project (unsure about the design, please propose something if time allows), to be addressed separately

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2807?planning-poker) with ZenHub @adulbrich @bogdanromanx @dhaneshnm @imsdu @nicwells @wwajerowicz
