### ISSUE TITLE
When deleting a project, the related ACL should also be deleted

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#2815]

**Comment by samuel-kerrien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2815?planning-poker) with ZenHub @bogdanromanx @dhaneshnm @imsdu @nicwells @smitfire @Stafeeva @wwajerowicz
