### ISSUE TITLE
When deleting a project, information collected by the statistics plugin should also be deleted

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#2816]
When a project is deleted, we should:
- remove Elasticsearch indices
- stop indexing routines

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2816?planning-poker) with ZenHub @bogdanromanx @imsdu @nicwells @samuel-kerrien @smitfire @Stafeeva @wwajerowicz
