### ISSUE TITLE
Add statistics (graph-analytics) integration tests

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2817]

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2817?planning-poker) with ZenHub @bogdanromanx @imsdu @nicwells @samuel-kerrien @smitfire @Stafeeva @wwajerowicz
