### ISSUE TITLE
Rename statistics plugin to graph-analytics

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2818]
New plugin name: `graph-analytics`

- [ ] rename the module, packages, files, configuration
- [ ] rename the api endpoint
- [ ] rename the information in the documentation

**Comment by samuel-kerrien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2818?planning-poker) with ZenHub @bogdanromanx @dhaneshnm @imsdu @nicwells @smitfire @Stafeeva @wwajerowicz
