### ISSUE TITLE
Display the project deletion banner only when inclusion and exclusion filters match the current project

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2819]
The Delta API exposes the project deletion configuration as follows:

```
{
  "@context": "https://bluebrain.github.io/nexus/contexts/project-deletion.json",
  "@type": "ProjectDeletionConfig",
  "_idleIntervalInSeconds": 600,
  "_idleCheckPeriodInSeconds": 5,
  "_deleteDeprecatedProjects": true,
  "_includedProjects": [
    "some.+"
  ],
  "_excludedProjects": [
    ".+"
  ]
}
```

Notice the fields `_includedProjects` and `_excludedProjects`. These define a collection of regexes that select and filter out the projects that are to be automatically deleted.

Fusion should display the deletion banner only when the current project matches one of the entries in the `_includedProjects` list of regexes and doesn't match any of the `_excludedProjects` regex entries.

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2819?planning-poker) with ZenHub @bogdanromanx @imsdu @nicwells @samuel-kerrien @smitfire @Stafeeva @wwajerowicz
