### ISSUE TITLE
 When the user selected more rows than fits the available viewport, and scrolls down the table, the column header row should stay put (fixed) and not disappear

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#2822]
The search header (where the menus and pagination are located) should also stay fixed.

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2822?planning-poker) with ZenHub @bogdanromanx @adulbrich @imsdu @nicwells @samuel-kerrien @smitfire @Stafeeva @wwajerowicz
