### ISSUE TITLE
Plan migration for new data table in Studios

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2828]
For Studio migration:

1. DKE will provide a list of Studios to migrate
2. NISE will write a script to migrate these Studios
3. Run the script
4. Inform DKE
5. DKE then will change the view to ES and migrate their dashboards: they want the URLs to stay the same

Script:

- look for studios
- look for the workspaces and dashboards for given studio
- update payloads to the new model

Notes:

- to be performed with a service account so that we can identify the migration

**Comment by adulbrich** [comment]
@MFSY do you have an opinion on this one?

**Comment by MFSY** [comment]
Hi @adulbrich ,

What "new data table in Studios" means ?  Is it about migrating. the studios to use ES views ? If yes then DKE plan is to do the migration as we own them all.

In case of any other type of migration, I would like to know more about it.
