### ISSUE TITLE
Unable to create an ES view based studio

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus#2868]
**Describe the bug**
Unable to create an ES studio.

**What part of Nexus is affected**: Fusion

ES based Studio creation issues:

- The Workspace creation (does not contains dashboard selection) and edit (contains dashboard selection) forms are different
- Dashboard creation by default shows default SPARQL query without the possibility to say the ES or even SPARQL view to use

<img width="1161" alt="Screenshot 2021-10-12 at 13 17 42" src="https://user-images.githubusercontent.com/2990875/136959600-c70ac7aa-44de-4d26-bda8-9c6ff272a5e3.png">

- The link View query in Sparql Editor is leading to a 404 page
- I have to click upon save with a SPARQL query even though what I want is to say the ES view I want to use
- Editing the created Dashboard is not providing me with the possibility to set the ES view I want to use. 
- It is when updating the workspace again and once a dashboard was created that I'm proposed with the the choice of a view 

- When I choose the ES view I want I got:

<img width="1353" alt="Screenshot 2021-10-12 at 13 12 53" src="https://user-images.githubusercontent.com/2990875/136959860-f1323a70-2a7d-4127-88a7-44a036bd914b.png">

- It is only When creating a new dashboard that I'm given the opportunity to write an ES query I want

<img width="1680" alt="Screenshot 2021-10-12 at 13 14 32" src="https://user-images.githubusercontent.com/2990875/136959954-406a4425-0bd0-405b-8694-d23fb59ee2e9.png">

- I still can't modify the first dashboard I created which still only allow a SPARQL query which obviously will not work. Also this first dashboard now have an View query in Elastic Search Query Editor | Read Docs while the Read Docs still point to the SPARQL doc page 
- I have no obvious way from the UI to deprecate this dashboard.
- Now the dashboard with ES. Query is not working because of a double encoding that the UI is doing on the ES view _self:

<img width="1302" alt="Screenshot 2021-10-12 at 13 25 20" src="https://user-images.githubusercontent.com/2990875/136960000-22ea850a-a700-49f2-a602-55df8fc6a48a.png">

**Comment by adulbrich** [comment]
@MFSY This is fixed in the new studio version, but it is blocked until you give us a go on this ticket/comment: https://github.com/BlueBrain/nexus/issues/2828#issuecomment-947613768

**Comment by MFSY** [comment]
Hi @adulbrich ,

I'm not sure to follow the link between these twos issues. This ticket is about bugs to fix when creating a studio based on an ES view. Are they fixed (i.e Can I create a studio based on an ES view ) ? Looking at staging, it looks like (ES or SPARQL based) studio creation  is no longer available. Are you planing to remove that feature ?
