### ISSUE TITLE
Unsure what's happening with `Name` filter values

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2879]
**Describe the bug**

![image](https://user-images.githubusercontent.com/11705901/137315205-4a19efaf-3bd7-4de7-a0e7-de1e1b36d7a0.png)

**What part of Nexus is affected**: Fusion

**To Reproduce**

1. Go to the search web app in staging
2. Search for "morphology"
3. Click on the `Name` column dropdown
4. The list of values doesn't make sense (see screenshot)

**Expected behavior**

The most common values for the Name should be at the top in decreasing order.

**Comment by nicwells** [comment]
Issue opened to address this: https://github.com/BlueBrain/nexus/issues/2899
