### ISSUE TITLE
ACLs management

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#288]
Listing existing ACLs on an organisation or project. Update ACLs on a existing organisation or project, by removing existing entries or adding new permissions for groups or users. Adding ACLs when creating an organisation or a project. Shortcut action to make an organisation or project public. Adding groups and users names will be free-form since we don’t have a way to list them.

Parent of several issues TBC>

**Comment by julienmachon** [comment]
Right now, we display the ACLs (read only) at the project levels. Modifying ACLs is hard, as described here https://github.com/BlueBrain/nexus/issues/481#issuecomment-470134561

We will leave this in the backlog for now as it is not a priority

**Comment by julienmachon** [comment]
This will be handled by this epic #847
