### ISSUE TITLE
Support both single images and array/collection of images in the image plugin

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2893]
**Motivation**

Given this resource: https://staging.nexus.ocp.bbp.epfl.ch/bbp_test/studio_data_11/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F0ad06861-0c70-4e96-bf57-6ee488d204a1?rev=3

The image viewer plugin does not display.
I tried changing the property from `distribution` to `image` to no avail.

**Acceptance Criteria**

- When a user provides one or more images in the resource payload, either under the `schema:image` property or the `schema:distribution` property (only for Files with a mediaType starting with image), the plugins should render.
  - It could also be an ID that point to a File or DataDownload object.
- The behavior should be the same as described here: https://github.com/BlueBrain/nexus/issues/1696
- If the image(s) cannot load, please provide an appropriate error message:
  - Is the file not accessible from the storage?
  - Is there a property missing?
  - Is the file not actually an image?
  - ...
- Add a download button next to the "add to data cart" button for each images in list view
- Add a download all button at the top (that will use the archive to zip all images)

**Examples**:

- `schma:image` is used with Traces (even though we exclude the image plugin for Traces, we can use a Trace resource to test)
- https://staging.nexus.ocp.bbp.epfl.ch/bbp_test/studio_data_11/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F0ad06861-0c70-4e96-bf57-6ee488d204a1?rev=3 (should also work with revision 4)

**Comment by dhaneshnm** [comment]
![Screenshot 2021-11-01 at 09.51.02.png](https://images.zenhubusercontent.com/60acded989e827605bd8d908/c4d19020-2439-4c8a-8c97-dd6c26879f97)

**Comment by dhaneshnm** [comment]
@adulbrich  As per the manifest, image viewer will work only of 1) The type is File and 2) it has a field with _mediaType which has value starting with "image". In the example we have here, the type is "Data Download" and the there no " _mediaType " property, but only encoding format.

**Comment by adulbrich** [comment]
Let's support both single images and arrays and id in both:

```
{
  "image": {}
},
{
  "distribution": {
    "@type": "File",
    "_mediaType": [
      "image/*"
    ]
  }
}
```

**Comment by smitfire** [comment]
Adjusting the mapping solved the issue. If an array is used for the 'image' property then it must be added to mapping like so
`"mapping": [
    {
      "image": {}
    },
    {
      "image": []
    },
    {
      "distribution": {
        "@type": "File",
        "_mediaType": [
          "image/*"
        ]
      }
    },
    {
      "distribution": {
        "@type": "DataDownload",
        "encodingFormat": [
          "image/*"
        ]
      }
    }
  ],`

**Comment by smitfire** [comment]
@alex4200 this ticket is for accepting [] or {} under the image. For the image plugin to work please consult dhanesh's comments above. We also intentionally disable the 'preview' button for images within the "Preview" plugin. Reach out to me on slack if you have any other questions
