### ISSUE TITLE
Re-write the permission fixer to Scala with native image

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2915]
Get rid of the rust codebase in the `nexus` repository (to be moved and rewritten in scala in a private repo)

- Changes the permission mask recursively
- Changes the ownership recursively

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2915?planning-poker) with ZenHub @adulbrich @bogdanromanx @imsdu @nicwells @smitfire @wwajerowicz

**Comment by imsdu** [comment]
Nexus Storage will be decommissioned in 1.11
