### ISSUE TITLE
Unable to upload empty files using the RemoteDiskStorage

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2921]
**Describe the bug**
Attempting to create an empty file results in an error:

```
{
    "@context": "https://bluebrain.github.io/nexus/contexts/error.json",
    "@type": "UnexpectedSaveError",
    "details": "File cannot be saved on path '***/c/c/9/b/5/a/9/f/zero.json' for unexpected reasons. Details 'an HTTP response to endpoint 'http://storage.nexus.svc/v1/buckets/***/files/***/c/c/9/b/5/a/9/f/zero.json' with method 'HttpMethod(PUT)' that should have been successful failed: the request failed due to 'requirement failed: An HttpEntity.Chunk must have non-empty data''",
    "reason": "File 'https://bbp.epfl.ch/neurosciencegraph/data/a8b0465d-8760-4075-88df-7413328ec019' could not be saved using storage 'https://bbp.epfl.ch/neurosciencegraph/data/f73e185c-61ba-42cf-8d40-a42c454285d7'"
}
```

**What part of Nexus is affected**
- Delta

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Attempt to upload an empty file to a project configured with a RemoteDiskStorage

**Expected behavior**
An empty file should be created.

**Comment by jdcourcol** [comment]
@samuel-kerrien this bugs prevents bbp-workflow (with simulation) to run on GPFS enabled projects. 
As of today, scientists use projects that are not GPFS enabled to run their simulation. But as the goal is to have all the projects GPFS enabled (i.e managed by nexus), that is going to be a strong blocker.

Can you evaluate what would be the cost of fixing it ?
