### ISSUE TITLE
Issue when downloading large files from web browser

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#2925]
Let's try to squeeze this in 1.7.0, otherwise 1.7.1.

**Describe the bug**
as reported by @pgetta while developing scientific portals, the downloading of large files is problematic. Feedback of progress to the user isn't working in Fusion or his portal. Pavlo has attempted several workarounds without success.

We should have a meeting with @pgetta to review the issue and consider how we could address it.

**What part of Nexus is affected**
- [x] Fusion
- [x] Delta (to be confirmed)

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to Fusion and open an entity that has a large data file attachment
2. Click on Download, nothing appears to happen and after a while, the file appears downloaded, no intermediate feedback ti the user in between. It has been tested with files as big at 13GB in the ngv project and it took about 20' for the file to show up.

**Expected behavior**
The browser should be able to provide a view of the progress of the download while it is happening.

**Comment by pgetta** [comment]
Hi @samuel-kerrien, I've noticed that this issue is closed now.
Is there a feature/api we can use as a solution?

**Comment by bogdanromanx** [comment]
I believe this has been closed in favour of: #2215, but wasn't linked.

**Comment by pgetta** [comment]
Understood, thank you, @bogdanromanx
