### ISSUE TITLE
Enable compression when interacting with blazegraph

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#2927]
**Motivation**
Delta supports compression with both its clients but also with nearly every component it interacts with (Cassandra, Elasticsearch, ...)
Blazegraph remains an exception and the media types it supports can be quite verbose and therefore generate a lot of I/O.

This can cause some problems while indexing (where the payload can be too large and  be rejected by blazegraph like in the error @adeel-ansari reported today) but also while querying where responses can also be large.

Blazegraph does not support natively gzip compression through its api.
However, it does rely on a embedded jetty server and it is possible to override `web.xml` configuration files via environment variables to enable gzip compression  via a `GzipFilter`

See: https://github.com/blazegraph/database/blob/3127706f0b6504838daae226b9158840d2df1744/bigdata-core/bigdata-sails/src/java/com/bigdata/rdf/sail/webapp/NanoSparqlServer.java#L212

**Acceptance criteria**
1. When indexing from Delta, the payload must be properly compressed. 
2. When querying, the blazegraph response must also be compressed.

**Comment by dhaneshnm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2927?planning-poker) with ZenHub @imsdu

**Comment by dhaneshnm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2927?planning-poker) with ZenHub @samuel-kerrien
