### ISSUE TITLE
Support numerics in search table

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2938]
Background:

For entities such as neuron or bouton density, or brain layers, the metadata contains values such as density and thickness. These are numerical values with a specified unit.
It is useful for users to be able to filter for specific values. Note that there might be a unit mismatch (could be addressed by pipes later on, if they support composite views).

Mocks:

![Design Assets - Table Column Dropdown – Numerics Range –  Only one value](https://user-images.githubusercontent.com/11705901/142444253-49424f3a-454e-4bc9-883e-8e2eb6e6354c.png)
![Design Assets - Table Column Dropdown – Numerics Range – No missing](https://user-images.githubusercontent.com/11705901/142444255-0dd7454f-310d-469c-803c-57210cbcd412.png)
![Design Assets - Table Column Dropdown – Numerics Range –  Alt](https://user-images.githubusercontent.com/11705901/142444256-bd50c173-856f-42cb-ab89-409c9c148c9a.png)
![Design Assets - Table Column Dropdown – Numerics Range –  Alt Slided](https://user-images.githubusercontent.com/11705901/142444259-2926e087-a3b5-433e-9a55-dc94350a0e89.png)
![Design Assets - Table Column Dropdown – Numerics Range –  Missing selected](https://user-images.githubusercontent.com/11705901/142444249-ae6a3509-0056-4c6b-92ea-f8a0ef4314a3.png)

Acceptance Criteria:

- The user clicks on the column dropdown of a numeric property:
  - There are two fields, one for the min value, one for the max value, plus a slider.
  - By default, the min and max values are filled by the actual data min and max values.
  - The user can change the values to be within the min-max range in order to filter.
  - The user can reset the min and max value by clicking on the `Minimum` and `Maximum` buttons below the inputs.
  - If there is only one value (unique), the input is greyed out and cannot be edited. Both input fields contain the same value.
- Upon selecting an operator and filling the required limit, the table updates automatically.
- The user can also toggle the `missing values`. 
  -  Upon activating missing values, the input values are greyed out and cannot be edited.
  - The count of missing values is shown.

Notes:

- How to get the slider step value? maybe something like `abs(max-min)/100`
- https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/histogram.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html

Not in scope:

- conversion of units
- The user sees a summary of the distribution (min, max, mean, median, and a density plot) in place of the list of values (that we have for single- and multi-valued categorical fields)
- User can choose the number of decimals (to be seen in the cells)
  - by default, this should be 3 digits behind the comma
  - use US notation to display numerics: comma for thousands, dot for decimals

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1013

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1013
