### ISSUE TITLE
Search crashes when filtering

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2949]
Issue appears in dev

**Describe the bug**

1. Open project dropdown (or e-type, m-type, type)
2. Select (tick) one vlue
3. Save
4. The search returns a blank screen

**What part of Nexus is affected**: Fusion

**Expected behavior**

Filtering should work without crashing the app.

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1003
