### ISSUE TITLE
Update documentation to branch out 1.7.x (in addition to 1.4.x, 1.5.x, 1.6.x, snapshot)

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2959]
- create 1.7.x branch
- add git-submodule
- set 1.7.x as the main submodule

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2959?planning-poker) with ZenHub @adulbrich @imsdu @nicwells @smitfire @wwajerowicz @bogdanromanx

**Comment by dhaneshnm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2959?planning-poker) with ZenHub @samuel-kerrien
