### ISSUE TITLE
Tag Delta and provide commit list

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2964]

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2964?planning-poker) with ZenHub @adulbrich @imsdu @nicwells @smitfire @wwajerowicz
