### ISSUE TITLE
Review all Delta release changes and ensure that documentation is up to date

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2967]
- includes kubernetes/docker-compose manifests

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2967?planning-poker) with ZenHub @adulbrich @bogdanromanx @imsdu @nicwells @smitfire @wwajerowicz

**Comment by dhaneshnm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2967?planning-poker) with ZenHub @samuel-kerrien

**Comment by imsdu** [comment]
Done, apart the deletion of the nexus-cli/docker based cli, everything was up-to-date
