### ISSUE TITLE
When identity provider is not publicly accessible, the nexus web page hangs for more than 1 min trying to get the open-id configuration

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2970]
**Describe the bug**

The app tries to fetch the openID configuration. This takes over 1 min and the page stays blank until it fails in Chrome.

**What part of Nexus is affected**: Fusion

**To Reproduce**

1. go to https://bbp.epfl.ch/nexus/web
2. wait 1.3 min
3. page finally loads

**Expected behavior**

* Nexus web should load in under 2 sec in good network conditions even when the user is not on the VPN.
* Some of the data we have is public (incl. public studios) and we can't have visitors looking at a blank screen for 1.3 min.
* When user attempts to log-in but authentication provider is not accessible, rather than displaying "We could not log you in due to: Network Error...", provide a more specific error message such as: "Unable to reach the authentication provider. Check network connection"
* If user has previously authenticated so has a browser session but is now no longer on VPN or on-site (i.e. can't access authentication provider), Fusion will attempt to access the auth provider, in such cases fail silently - we should not bother user at this point. They are effectively not logged-in and will receive the error message above if/should they attempt to log-in

**Screenshots**

![image](https://user-images.githubusercontent.com/11705901/143461972-6b7b626f-bdd1-4fa8-9d1b-f36a3d010365.png)

**Comment by samuel-kerrien** [comment]
Looks more like an issue with our own infrastructure. @dhaneshnm will contact our admins. Likely no work needed in Fusion.

**Comment by nicwells** [comment]
Internal infrastructure issue resolved in Jira issue, HELP-15329.
