### ISSUE TITLE
Cannot collapse code in admin plugin anymore

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2988]
**Describe the bug**

In the JSON payload in the admin plugin, when trying the collapse a chunk of code, the resource view closes.
In staging, 1.7.0-M2

https://user-images.githubusercontent.com/11705901/144201610-08ea0093-bb9e-44ab-8c11-c8565c3699f5.mp4

**What part of Nexus is affected**: Fusion

**To Reproduce**

1. Go to the project view, browse tab
2. Click on any resource
3. Open the admin plugin
4. Collapse any chunk of code in the JSON payload
5. The resource view closes 

**Expected behavior**

1-4. same
5. the chunk is collapsed

**Comment by nicwells** [comment]
Bug fixed in 1.7.0-M3
