### ISSUE TITLE
Admin Plugin - Nothing happens when clicking  'Download Metadata'

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3019]

**Comment by samuel-kerrien** [comment]
Nexus Delta v1.6.1
  Nexus Fusion v.1.7.0-M3
  Browser: Chrome 95.0.4638.69
  OS: macOS 11.6
  env: staging

Clicking on the 'Download Metadata' and then choosing any of the 3 format options results in nothing happening.
There is an error in the dev console (see below)

![Screenshot 2022-01-18 at 10.40.45.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/69bc0300-cca2-42fc-afc7-558b76127cfa)

![Screenshot 2022-01-18 at 10.40.04.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/2a3903ec-6d2e-4bc4-a7a4-2c459e306ff0)

**Comment by dhaneshnm** [comment]
As a first step we need to show error notification when this fails.
