### ISSUE TITLE
Project > Browse - Time rendering discrepancies

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3020]

**Comment by samuel-kerrien** [comment]
Nexus Delta v1.6.1
  Nexus Fusion v.1.7.0-M3
  Browser: Chrome 95.0.4638.69
  OS: macOS 11.6
  env: staging

We are showing 2 different formatting of time in the same screen as can be seen highlighted below:
![Screenshot 2022-01-18 at 10.43.48.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/cbbe725d-177e-4b66-88fb-8c1f53aabcb4)

Columns of type date in Search should also be considered in this alignement.

Proposal to be discussed during Grooming:
- Show the simplified representation by default, examples/rules below
  - moments ago (if < 60s)
  - X minute(s) ago (if < 60 minutes)
  - X hour(s) ago (if less than 24h)
  - X day(s) ago (if less than 30 days ago)
  - X year(s) ago
  - note that the (s) on minutes, hours, days, years is subject to checking if value 1 or more
  - considering we are only showing integer value, we will round down.
- Show the full details of the date when mouse-over the text.

Ensure we show time in this fashion through the application.

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3020?planning-poker) with ZenHub @dhaneshnm @imsdu @nicwells

**Comment by dhaneshnm** [comment]
Also, add A tool tip to show the UTC time.
