### ISSUE TITLE
Project > Graph analytics - Do not show tab if the plugin is not listed

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3022]

**Comment by samuel-kerrien** [comment]
Nexus Delta v1.6.1
  Nexus Fusion v.1.7.0-M3
  Browser: Chrome 95.0.4638.69
  OS: macOS 11.6
  env: staging

Unsure why the screen is white. issues, not configured ?

![Screenshot 2022-01-18 at 10.55.27.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/9b84bcf0-8fbb-4160-a1a8-bbfb6929bd84)

**Comment by samuel-kerrien** [comment]
This is a follow-up of this closed but incomplete ticket: #2557

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3022?planning-poker) with ZenHub @dhaneshnm @nicwells @imsdu

**Comment by nicwells** [comment]
Statistics tab in screen capture above was blank for some reason but isn't in latest build now deployed to dev/staging. It is the separate graph analytics tab that is dependent on the graph analytics plugin being enabled which this issue is related to.
