### ISSUE TITLE
Investigate JIRA integration to support Discussions

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3025]
**Motivation**
We want to enable our scientists to have discussions around Knowledge Graph entities. As a starting point, to avoid redeveloping it from scratch and considering that current discussions are happening in JIRA already, we have chosen to leverage JIRA and integrate it with Fusion.

**Acceptance criteria**
1. investigate what JIRA can offer to support current mockups
   a. Authentication, reuse of token across Nexus and JIRA
   b. JIRA API and Permissions 
        i) API calls should cover: issue creation with project selection, search including full-text across all fields, list and add comments
   c. Correlation of access between Nexus and JIRA projects
   d. Data model in Nexus (Entity - issues & Project - issues)
2. update mockups as necessary
3. review with users

**Mockups**
https://docs.google.com/presentation/d/1SNaZnPK6Erh5z6COZv64j8wSDAXp91S4KfZWe92hCFc/

**Not in scope**

**Comment by imsdu** [comment]
# Nexus discussions via Jira

**Jira Server will be discontinued in 2024 and Core Services has no planning yet on when and what are the next steps.**

There are two options to migrate:
* Atlassian Cloud
* Atlassian Data Center (to still host on-premise)

Both Jira Server and the new options are on a v2 API (although the new ones also have a v3 in beta)

## Authentication

Jira Server only supports
* OAuth 1.0a
* Basic authentication

OAuth 2.0 is not supported in Jira Server (but it is in Atlassian Cloud/DC).

To use OAuth, some config is needed on the Jira side: https://developer.atlassian.com/server/jira/platform/oauth/

## Issue creation

Examples:
https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-an-issue-examples

## Issue search

There is a search dsl called jql that seems to be stable.

There is a feature called custom fields that allows to define extra fields for an issue,
this could be used for example to enter the nexus project, the brain region, an identifier

https://confluence.atlassian.com/adminjiraserver/adding-custom-fields-1047552713.html

These custom fields could be queried via jql to get issues related to a Nexus project, to a brain region, ...

These queries could be performed both in Jira and in Fusion so users could get the same experience in both.

Custom fields can not be made mandatory.
In the doc, they say no more than 1,000 custom fields

We could also define an issue type "Discussion" for discussions.
That would also allow to improve filtering both in fusion and in Jira.
