### ISSUE TITLE
Project > Graph Analytics - Align styling to current Fusion style

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3026]
**Motivation**
To aligne with the current application so that it looks like an integral part of the app.

**Acceptance criteria**
1. Make sure the presentation matches the Mockups as seen below
2. List of properties and relations are fully viewable (currently cut off at the bottom)
3. Add tooltip on information icon next to 'properties' title that explains the information showing in that section: 
proposed text: "These are the properties that are used to describe a resource of this type. It also include how many resources use them and overall coverage.". Initial proposal on how to present info tooltip in the mockups, open for discussions.
4. Add tooltip on information icon next to 'relationships' title that explains the information showing in that section: 
proposed text: "These are the known relations between resources of this type and other resources in this project. It also shows how many time these relations are observed."
5. Add tooltip to show the full URI of properties. Currently we are only showing suffix.
6. Add percentages of usage for each properties

**Mockups**
![Screenshot 2022-01-19 at 12.05.56.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/e68538a2-c4e0-499b-8e43-01fcc5914a0a)
https://xd.adobe.com/view/6ef9040c-bfda-4d7c-93ee-f7bcbcde4238-3baa/

**API changes**
none

**Not in scope**

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3026?planning-poker) with ZenHub @nicwells @smitfire @imsdu

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1037
