### ISSUE TITLE
Search - searching for fragment of a dataset's name yields not results

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3040]
Environment: dev
Browser: 97.0.4692.99
OS: MacOS 11.6
Nexus Delta v1.6.0+33-a6ad3930-SNAPSHOT
Nexus Fusion v1.7.0-M4

**How to reproduce**
- log into dev
- in the search bar, type 'AA0074', you will get a single NeuronMorphology
- Now edit your query to 'AA007', you get nothing.

**Comment by dhaneshnm** [comment]
![Screenshot 2022-02-09 at 09.56.48.png](https://images.zenhubusercontent.com/60acded989e827605bd8d908/75931937-e65d-4a07-aa83-ec1e1f876b33) .
This seems to be working in dev now.

**Comment by samuel-kerrien** [comment]
prefix and suffix search is tested to be working, however fragment inside a word does not, an other ticket will be created for that.
