### ISSUE TITLE
Trouble running nexus locally with docker

### ISSUE THREAD

**Issue by slarson** [BlueBrain/nexus#306]
I was following the [docs for running nexus locally with docker](https://bluebrain.github.io/nexus/docs/getting-started/running-nexus/docker.html) but could not get it running. I'm not sure what the underlying problem is.  Here's the output I got after grabbing the docker-compose.yaml and the ngnix.conf.  I waited more than a minute to check localhost.

```
Stephens-MacBook-Pro:nexus slarson$ docker swarm init
Swarm initialized: current node (o1wk6b43662xmvkjvh99b20y3) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-4r73oz72p5h3fg0wgct0b2xjpo57fv684t2ojg5ej1o0mvq7dx-83wtdmvlal8mv4pydfrlpk824 192.168.65.3:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

Stephens-MacBook-Pro:nexus slarson$ docker stack deploy nexus --compose-file=docker-compose.yaml
Creating network nexus_default
Creating config nexus_nginx
Creating service nexus_cassandra
Creating service nexus_admin
Creating service nexus_zookeeper
Creating service nexus_iam
Creating service nexus_router
Creating service nexus_blazegraph
Creating service nexus_elasticsearch
Creating service nexus_kafka
Creating service nexus_kg
Stephens-MacBook-Pro:nexus slarson$ curl http://localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
```

Going to http://localhost on my browser gave me:
```
502 Bad Gateway
nginx/1.14.1
```

My docker version is:

<img width="561" alt="screen shot 2018-11-28 at 1 24 17 pm" src="https://user-images.githubusercontent.com/1037756/49173165-f168be80-f310-11e8-958c-d27b877c7565.png">

**Comment by hygt** [comment]
Hi @slarson it might just take a little more time for everything to be up and running.

Can you share the output of `docker stack ps nexus` ?

**Comment by yiiifan** [comment]
Hi, I was also facing some issues when running nexus locally with docker. I have started the docker for more than 10 minutes and still got **curl: (52) Empty reply from server** when I run `$ curl http://localhost/kg`.
Here is my output of docker stack ps nexus:
`
ID                  NAME                                         IMAGE                                                 NODE                DESIRED STATE       CURRENT STATE                   ERROR                              PORTS
yrs5ac72l0e0        nexus_router.sezvcpvoygjx8vevykfqxihb1       nginx:stable                                          docker-desktop      Ready               Ready less than a second ago                                       
wnrmn8ssgl4r         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed less than a second ago   "task: non-zero exit (1)"          
eg27earjqg28         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed 6 seconds ago            "task: non-zero exit (1)"          
jzcu8oe7mose         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed 12 seconds ago           "task: non-zero exit (1)"          
jr6og88uquox         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed 18 seconds ago           "task: non-zero exit (1)"          
rn87tgee4cjj        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Ready               Ready 1 second ago                                                 
d373k7p8h0i5        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Ready               Ready 1 second ago                                                 
lkqpa0ure9z0        nexus_web.1                                  bluebrain/nexus-web:1.3.1                             docker-desktop      Ready               Rejected 1 second ago           "No such image: bluebrain/nexu…"   
8zc9tubydno6        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Ready               Ready 3 seconds ago                                                
uzgmqr4riqvm        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 1 second ago             "starting container failed: OC…"   
hd8hc1jkhzhu        nexus_web.1                                  bluebrain/nexus-web:1.3.1                             docker-desktop      Shutdown            Rejected 6 seconds ago          "No such image: bluebrain/nexu…"   
bxlgae4p4wbg        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 1 second ago             "starting container failed: OC…"   
xg843dh7fgs3        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 4 seconds ago            "starting container failed: OC…"   
vr3uocyu0kes        nexus_web.1                                  bluebrain/nexus-web:1.3.1                             docker-desktop      Shutdown            Rejected 11 seconds ago         "No such image: bluebrain/nexu…"   
oea27901eue3        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 7 seconds ago            "starting container failed: OC…"   
see7l6sonewf        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 7 seconds ago            "starting container failed: OC…"   
5q6712bjw3ys        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 9 seconds ago            "starting container failed: OC…"   
ksps5kz6phtd        nexus_web.1                                  bluebrain/nexus-web:1.3.1                             docker-desktop      Shutdown            Rejected 16 seconds ago         "No such image: bluebrain/nexu…"   
s5l3o3ezxcao        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 12 seconds ago           "starting container failed: OC…"   
yqjfpy1ohj4o        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 13 seconds ago           "starting container failed: OC…"   
10h49am7thx7        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 15 seconds ago           "starting container failed: OC…"   
y3ajzlx04bgf        nexus_web.1                                  bluebrain/nexus-web:1.3.1                             docker-desktop      Shutdown            Rejected 21 seconds ago         "No such image: bluebrain/nexu…"   
r3y7cmdkd8tt        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 18 seconds ago           "starting container failed: OC…"   
h5ec69d2iqu1        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 18 seconds ago           "starting container failed: OC…"   
6wywlzw016q3        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 21 seconds ago           "starting container failed: OC…"   
nb4d9fki2sub        nexus_blazegraph.1                           bluebrain/blazegraph-nexus:2.1.5                      docker-desktop      Running             Running 14 minutes ago                                             
tqmtde06m0xp        nexus_cassandra.1                            cassandra:3                                           docker-desktop      Running             Running 14 minutes ago                                             
vw767q06xxfu        nexus_elasticsearch.1                        docker.elastic.co/elasticsearch/elasticsearch:7.4.0   docker-desktop      Running             Running 14 minutes ago                 
`
My docker version is Docker version 19.03.8

**Comment by bogdanromanx** [comment]
Hi @yiiifan, thanks for your comment.

Could you please edit line 57 from the docker compose file (https://github.com/BlueBrain/nexus/blob/50083538a34e2151af44df587b4d25073e62e76f/docs/src/main/paradox/docs/getting-started/running-nexus/docker-swarm/docker-compose.yaml#L57) and change the nexus-web docker image version from `1.3.1` to `v1.3.3`? (notice the extra `v` character)

Let me know if this fixes it.

**Comment by yiiifan** [comment]
I've changed my docker-compose.yaml file to:
  web:
    image: bluebrain/nexus-web:v1.3.3
    environment:
      BASE_PATH: "/"
      HOST_NAME: "http://localhost"
      API_ENDPOINT: "http://localhost/v1"

nexus-web is up and running successfully now, but kg/iam/admin still not working ...
here is my docker stack px nexus:

ID                  NAME                                         IMAGE                                                 NODE                DESIRED STATE       CURRENT STATE                   ERROR                              PORTS
ypw0rz3bj0em        nexus_router.sezvcpvoygjx8vevykfqxihb1       nginx:stable                                          docker-desktop      Ready               Ready less than a second ago                                       
xtin05211ikb         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed less than a second ago   "task: non-zero exit (1)"          
sty1ulnkyb7j         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed 6 seconds ago            "task: non-zero exit (1)"          
z21vg8k86zz0         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed 12 seconds ago           "task: non-zero exit (1)"          
ew3h1npo9lvc         \_ nexus_router.sezvcpvoygjx8vevykfqxihb1   nginx:stable                                          docker-desktop      Shutdown            Failed 18 seconds ago           "task: non-zero exit (1)"          
k6ox1bq1k5zh        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Ready               Ready 2 seconds ago                                                
s6t1payzifa2        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Ready               Ready 3 seconds ago                                                
lwtrafh08xkv        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Ready               Ready 3 seconds ago                                                
pqllsurrcuoi        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 2 seconds ago            "starting container failed: OC…"   
uuq4piyxky34        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 3 seconds ago            "starting container failed: OC…"   
6wijunzwzdzq        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 4 seconds ago            "starting container failed: OC…"   
07ewwgdaa14z        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 8 seconds ago            "starting container failed: OC…"   
nhwkg631u5n0        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 9 seconds ago            "starting container failed: OC…"   
k6razyquaz0u        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 9 seconds ago            "starting container failed: OC…"   
p2fj5flls40h        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 14 seconds ago           "starting container failed: OC…"   
keztk8f7bdq0        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 15 seconds ago           "starting container failed: OC…"   
gikg8pr2ec9k        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 15 seconds ago           "starting container failed: OC…"   
4uopph3s40oz        nexus_kg.1                                   bluebrain/nexus-kg:1.3                                docker-desktop      Shutdown            Failed 20 seconds ago           "starting container failed: OC…"   
rqti9b86fugv        nexus_iam.1                                  bluebrain/nexus-iam:1.3                               docker-desktop      Shutdown            Failed 21 seconds ago           "starting container failed: OC…"   
q7q8hh8nwgrs        nexus_admin.1                                bluebrain/nexus-admin:1.3                             docker-desktop      Shutdown            Failed 21 seconds ago           "starting container failed: OC…"   
c4bldyfn1pay        nexus_web.1                                  bluebrain/nexus-web:v1.3.3                            docker-desktop      Running             Running 8 minutes ago                                              
29l3stxrgm0z        nexus_blazegraph.1                           bluebrain/blazegraph-nexus:2.1.5                      docker-desktop      Running             Running 8 minutes ago                                              
36jw5ss6itfk        nexus_cassandra.1                            cassandra:3                                           docker-desktop      Running             Running 8 minutes ago                                              
dimq3ksk0j6z        nexus_elasticsearch.1                        docker.elastic.co/elasticsearch/elasticsearch:7.4.0   docker-desktop      Running             Running 8 minutes ago                   [](url)

**Comment by yiiifan** [comment]
Here is the part of my YAML file related to bluebrain/nexus-kg, bluebrain/nexus-iam and bluebrain/nexus-admin:
`kg:
    image: bluebrain/nexus-kg:1.3
    entrypoint:
      ["wait-for-it.sh", "-s", "-t", "0", "admin:8080", "--", "./bin/kg"]
    environment:
      CASSANDRA_CONTACT_POINT1: "cassandra:9042"
      BIND_INTERFACE: "0.0.0.0"
      PUBLIC_URI: "http://localhost"
      IAM_INTERNAL_IRI: "http://iam:8080"
      IAM_PUBLIC_IRI: "http://localhost"
      ADMIN_INTERNAL_IRI: "http://admin:8080"
      ADMIN_PUBLIC_IRI: "http://localhost"
      SPARQL_BASE_URI: "http://blazegraph:9999/blazegraph"
      ELASTIC_SEARCH_BASE_URI: "http://elasticsearch:9200"
      JAVA_OPTS: "-XX:+UseStringDeduplication -Xms2G -Xmx4G"

  iam:
    image: bluebrain/nexus-iam:1.3
    entrypoint:
      ["wait-for-it.sh", "-s", "-t", "0", "cassandra:9042", "--", "./bin/iam"]
    environment:
      CASSANDRA_CONTACT_POINT1: "cassandra:9042"
      BIND_INTERFACE: "0.0.0.0"
      PUBLIC_URI: "http://localhost"
      SERVICE_DESCRIPTION_URI: "http://localhost/iam"
      JAVA_OPTS: "-Xms1G -Xmx2G"

  admin:
    image: bluebrain/nexus-admin:1.3
    entrypoint:
      ["wait-for-it.sh", "-s", "-t", "0", "iam:8080", "--", "./bin/admin"]
    environment:
      CASSANDRA_CONTACT_POINT1: "cassandra:9042"
      BIND_INTERFACE: "0.0.0.0"
      PUBLIC_URI: "http://localhost"
      IAM_INTERNAL_IRI: "http://iam:8080"
      IAM_PUBLIC_IRI: "http://localhost"
      JAVA_OPTS: "-Xms1G -Xmx1G"`

**Comment by bogdanromanx** [comment]
@wwajerowicz can you please take a look at @yiiifan's issue and help sort it out?

**Comment by wwajerowicz** [comment]
I'll look into it.

**Comment by wwajerowicz** [comment]
@yiiifan Can you download updated `docker-compose.yaml` and `nginx.conf` from here https://github.com/BlueBrain/nexus/tree/master/docs/src/main/paradox/docs/getting-started/running-nexus/docker-swarm and check if it fixes the problem?

**Comment by yiiifan** [comment]
Thanks very much, now all docker images are running successfully!
The only problem is that when I try to run curl against it, it responses:
```
$ curl http://localhost/kg
curl: (52) Empty reply from server

```

**Comment by wwajerowicz** [comment]
@yiiifan Can you try adding this `depends_on` block in the `router` container in `docker-compose.yaml`
```
router:
    image: nginx:stable
    depends_on:
      - iam
      - admin
      - kg
      - web
```

**Comment by yiiifan** [comment]
Still the same error message when curl...
Here is my current router code in YAML file:
```
 router:
    image: nginx:stable
    depends_on:
      - iam
      - admin
      - kg
      - web
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
```

**Comment by wwajerowicz** [comment]
@yiiifan one more thing to try: can you run `docker pull nginx:stable` before running `stack deploy`?

**Comment by yiiifan** [comment]
That works! Thanks a lot for helping!
