### ISSUE TITLE
Graph Analytics > Show edge directionality

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3097]
**Summary**
Currently edges appear non directed. However our relations are.
Cytoscape can show arrows as edges as can be seen in this demo:
https://ivis-at-bilkent.github.io/cytoscape.js-fcose/demo/demo-constraint.html
Also some explanation on how to style them here:
https://stackoverflow.com/questions/48550892/cytoscape-js-edge-and-arrow-style/48578519

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3097?planning-poker) with ZenHub @nicwells @imsdu
