### ISSUE TITLE
Resource List Sort Option disappears when search text is entered

### ISSUE THREAD

**Issue by nicwells** [BlueBrain/nexus#3108]
**Describe the bug**
The Sort A->Z button in the Resource list on the Project->Browse page disappears when some search text is typed in.

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to Nexus Fusion and log-in
2. Click on Admin, select an organization and project with some resources.
3. In the Browse tab on a Resource List (probably called Default Query), see how the sort A->Z button is visible.
4. Selecting a type or schema, observer how the button remains visible
5. Type something in the search box
6. See how the A->Z button disappears from the interface

**Expected behavior**
* Sort button should remain visible regardless of if search text entered.
* Sort button should correctly sort the search results in resource list in oldest->newest or newest->oldest order depending on the direction selected.

**API calls (requests/responses)**
If applicable, add the minimum requests/responses to help explain your problem.

**Screenshots**

**Additional context**

**Comment by dhaneshnm** [comment]
This is the  expected behavior due to reasons explained in this issue : https://github.com/BlueBrain/nexus/issues/1020.
