### ISSUE TITLE
Search Numerical column filter does not work in combination with a freetext search

### ISSUE THREAD

**Issue by nicwells** [BlueBrain/nexus#3110]
**Describe the bug**
When some search term has been searched for in Search the numerical column filter options do not work.

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to Nexus Fusion and log-in
2. Type something in the search bar, e.g. "ab" and hit Enter to search. Make sure we have some search results before proceeding.
3. Click the hidden columns option at the top-left of the Search table to open the Column Visibility options. Make any numerical column visible, e.g. Bouton Density. Close the Visibility options dialog.
4. Click on the numerical column header dropdown arrow to open the column options
5. See how all the filter values and statistics are blank or zero.

**Expected behavior**
TBC

* When search includes a freetext search the numerical column filters and statistics should continue to work.
* The minimum and maximum should be the minimum and maximum of the subset of results that match the search text
* The number of missing values in the "Show missing Values Only (XXXXX)" should reflect the number of missing values in the subset of results matching the searched text.
* The statistics should apply to the whole range of results

**API calls (requests/responses)**
If applicable, add the minimum requests/responses to help explain your problem.

**Screenshots**

**Additional context**

**Comment by dhaneshnm** [comment]
Created a new issue to improve the UX: https://app.zenhub.com/workspaces/blue-brain-nexus-60ace035034cae00105c9307/issues/bluebrain/nexus/3122
