### ISSUE TITLE
The Numerical column Missing filter option checkbox state is not retained

### ISSUE THREAD

**Issue by nicwells** [BlueBrain/nexus#3111]
**Describe the bug**
The state of the checkbox for "Show Missing Values Only (XXXXX)" in a numerical column heading's filter options is not maintained when the column options are opened again.

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to Nexus Fusion and log-in
2. Click on Search
3. Click the hidden columns option at the top-left of the Search table to open the Column Visibility options. Make any numerical column visible, e.g. Bouton Density. Close the Visibility options dialog.
4. Click on the numerical column header dropdown arrow to open the column options
5. Check the "Show Missing Values Only (XXXXX)" checkbox
6. Close the Column options and reopen them
7. See how the checkbox is unchecked.

**Expected behavior**
* The "Show Missing Values Only (XXXXX)" checkbox checked state is persisted

**API calls (requests/responses)**
If applicable, add the minimum requests/responses to help explain your problem.

**Screenshots**

**Additional context**

**Comment by dhaneshnm** [comment]
Closing in favor of : https://github.com/BlueBrain/nexus/issues/3106
