### ISSUE TITLE
Fetch original payload is not retrieving null values

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus#3112]
**Describe the bug**
Fetch original payload is not retrieving null values

**What part of Nexus is affected**
- [ ] Delta

**To Reproduce**
1. POST endpoint/resources/org/project/_/
{
    "@id":"https://myid.org",
    "type": "test_resource_td",
    "d": [{"name": "test_d1", "value": 3., "unitCode": ""},
          {"name": "test_d2", "value": null, "unitCode": ""}]
}

2. GET endpoint/resources/org/project/_/https%3A%2F%2Fmyid.org/source
{
    "@id":"https://myid.org",
    "type": "test_resource_td",
    "d": [{"name": "test_d1", "value": 3., "unitCode": ""},
          {"name": "test_d2", "unitCode": ""}]
}

**Expected behavior**

The JSON data exactly as I register it as per [doc](https://bluebrainnexus.io/docs/delta/api/resources-api.html#fetch-original-payload). Specially if the exact posted source is pushed correctly (i.e. with the null value) in the default defaultElasticSearchIndexES view .

GET endpoint/resources/org/project/_/https%3A%2F%2Fmyid.org/source
{
    "@id":"https://myid.org",
    "type": "test_resource_td",
    "d": [{"name": "test_d1", "value": 3., "unitCode": ""},
          {"name": "test_d2", "value": null, "unitCode": ""}]
}

**Comment by DrTaDa** [comment]
Hello! I wanted to know if there was progress on this issue?
