### ISSUE TITLE
Selected filter values should show at top of list in Search column options dialog

### ISSUE THREAD

**Issue by nicwells** [BlueBrain/nexus#3116]
**Motivation**
Selected filter values should display at top of list of filter values to make it easier for user to know which filter values have been selected.

**Acceptance criteria**
1. Selected filter value should display at top of list of filter values. Order of selected filters should be from highest to lowest count.
2. If user has entered some text in the search filter values text box, any selected filter values that match the search text should display at the top of the list of items. Any selected filter values that do not match are not displayed.
3. When user selects a filter value, filter value moves to top of list with a transition effect to indicate that it has moved. Scroll position of filter values should remain the same
4. Number of selected filter values is displayed at bottom of list of filter values

**Mockups**
![Screenshot 2022-02-16 at 12 41 12](https://user-images.githubusercontent.com/11296166/154257689-5fe23d1b-bef3-422f-81e6-116a92a5931d.png)

**Not in scope**
Other UI changes are in the scope of: https://github.com/BlueBrain/nexus/issues/3115

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1070
