### ISSUE TITLE
Youtube Video Plugin - plugin not rendering despite resource containing VideoObject

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3134]
**Describe the bug**
The issues has been noticed into the Thalamus public studio:
https://bbp.epfl.ch/nexus/web/public/thalamus/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fdensities%2F3ae5fcb0-c451-4352-8321-0eb49b555989

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Open the Studio
2. Open `Network Simulations`
3. Open anhy of the 5 videos, the YT plugin is not rendering despite the data model use appearing correct.

On this screenshot, one can see the plugin now showing and the JSON-LD payload where the video is defined.
![Screenshot 2022-03-01 at 14.07.23.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/8b1738ae-5e5f-43df-9cf5-41a0cc9d2818)

**Expected behavior**
The plugin should show and the video be presented.

**Comment by samuel-kerrien** [comment]
It appears that the plugin is showing correctly and the video playing when the user is logged in, but not when Anonymous (not logged in).

**Comment by smitfire** [comment]
Fixed in 1.7 M4
