### ISSUE TITLE
Download Plugin + Preview Plugin - Support 'distribution.url` for files not stored in Nexus

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3135]
**Description**
Currently, one can download files that are stored in Nexus if they are described using a `distribution` with a `@Location` and `contentUrl`. However, when only a `url` is used like in this entity [1], the download button does not make sense. In this specific case, the `url` points to a DOI (https://doi.org/10.5281/zenodo.6259750) that redirects to a Zenodo page (https://zenodo.org/record/6259750#.Yh4ht98o_0o), on which the user can download the 4GB ZIP file of the Thalamus Circuit.

[1] https://bbp.epfl.ch/nexus/web/public/thalamus/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fa3bb1dab-0493-4c4b-a345-7bd5902a3b47

**Recommendation**
When the distribution only has a URL, present an `Open` button that opens the link in a new tab. Both the Download and Preview plugin could implement  this behaviour. Please note that a consolidation work is planned between these two plugins in #2971, you might only need to implement it in one of them.

**Acceptance Criteria**
- plugin documentation should show examples of supported distributions
- when a Nexus stored file is described in a schema:distribution, a download button should be shows
- when a url is used to describe a schema:distribution, an Open button should open that url in a new tab
- Both copy and open url functionality should be supported.

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3135?planning-poker) with ZenHub @imsdu @samuel-kerrien @nicwells @smitfire @bogdanromanx
