### ISSUE TITLE
Studio - Redesign the Studio to be better aligned with the rest of Fusion (i.e Search, Admin)

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3141]
**Motivation**
Studio styling is different from other part of the Fusion such as Search and Admin.
We propose to put together an improved design to accommodate a collection of known issues listed below:

- General use of the style guide and colours
- Spacing between markdown and table
- Edit link in the Workspace/Dashboard could be streamlined (icon?)
- Some higher level titles in the markdown get shortened with elipsis when too long
- It was reported that the current layout of the Workspaces and Dashboards in Studio is not easy to convey their differences. In particular the way the horizontal boxes are showing the Workspaces and the vertically aligned boxes show the Dashboards (see capture below):
![Screenshot 2022-03-09 at 10.49.25.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/68d20633-98d4-4a23-99ec-4148ea65750c)

**Acceptance criteria**
1. A new design is defined and added to this ticket
2. The design is approved by stakeholder

**Mockups**
<coming later>

**Not included**
- the width of the resource panel appears to be better in 1.7, we need validation from stakeholder rather than implementing something new.

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3141?planning-poker) with ZenHub @bogdanromanx @imsdu @nicwells @samuel-kerrien @smitfire

**Comment by samuel-kerrien** [comment]
Duplicate of the following issues:
- #3162 
- #3174 
- #3176
