### ISSUE TITLE
Studio - Configuration of plugins at the Studio level

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3142]
**Motivation**
In the context of dissemination studios (e.g. upcoming Thalamus), it was requested that we would like to configure specific plugins to not be rendered and other to always be open. For example, in the case of Neuron Morphology, always show the morphology plugin and the download plugin. Other plugins should be hidden. No means of discovering other plugins should be provided.
It is to be considered that the current application offers configuration of plugins:
- at the deployment level
- open/close plugin can be persisted at browser level

A strategy that accommodates these various configuration options needs to be considered.

**Acceptance criteria**
1. By default, you do not need to configure plugins, the behaviour of plugins is inherited from Nexus deployment configuration.
2. The user that chooses to configure the studio should be able to choose which plugins can be shows in a specific dashboard. Plugins that are not selected would not be shown, irrespective of deployment level configuration
3. The configuration is done at the level of the Studio and would apply to all Workspaces and Dashboard
4. Configuration includes visibility of the plugin, its priority in the list and default open/close state
5. studio configuration should override whatever settings the user has at browser level (i.e. plugin open/close state)
6. Resource panel behaviour in the context of Global Search and Admin should remain unchanged
7. A Mock is put together to configure a Studio plugins' usage
8. The design is validated by stakeholder
9. The design is implemented and deployed for testing

**Mockups**
<coming soon>

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3142?planning-poker) with ZenHub @bogdanromanx @imsdu @nicwells @samuel-kerrien @smitfire
