### ISSUE TITLE
Studio - When clicking on Workspace and Dashboard the user may experience unexpected scrolling

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3144]
**Motivation**
When switching between workspaces and dashboard, the table loading potentially makes the page scroll.
As assessed by @dhaneshnm the containers shouldn't be reloaded, only the data in the components.

**Acceptance criteria**
1. The page shouldn't scroll around when loading workspaces/dashboards.

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3144?planning-poker) with ZenHub @bogdanromanx @imsdu @nicwells @samuel-kerrien @smitfire

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1074
