### ISSUE TITLE
Distribution retrieved when listing data given a schema id

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus#315]
Hi,

When listing data conformant to a given schema with the following call:

````
GET {{base}}/resources/org/project/schema_id
````

Each _results item is retrieved with a "http://www.w3.org/ns/dcat#distribution" object. Here are some suggestions and questions:

* Why just distribution is retrieved and not the other use provided metadata ?
* If distribution has to be retrieved then I suggest:

** to compact the uri "http://www.w3.org/ns/dcat#distribution" since it is aliased (by _distribution) in the [nexus resource context ](https://bluebrain.github.io/nexus/contexts/resource.json)

**  to retrieve all distribution of the entity not just the one resulting from an attachment in Nexus. The use may provide other distribution items.

**Comment by umbreak** [comment]
This is not relevant anymore since distribution and file metadata are no longer the same.
