### ISSUE TITLE
Global Search - Numerical Filter, slider minimum and maximum values are not stable

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3153]
**Describe the bug**
The slider filter gets reset when closing then reopening column filter.

**Steps to reproduce**
- I open Global Search
- I select datasets of type 'Neuron Density'
- I open the 'Neuron Density' column filter, the slider is set to the following extreme values:
  minimum: 1900 and maximum to 272400.
- I change the maximum using the slider to 99280. The data refreshes correctly in the background.
- I close the column filter, then re-open it again. The slider range is still the same. So far so good.
- I change the maximum slider value again, now to something higher: 210185. The data refreshes correctly in the background.
- I close the column filter, then re-open it again. The maximum value in the slider it now set to: 100000, a value I haven't set.
- It appears something worse happens with the minimum value. In that case both the minimum and the maximum get set to 100000 when closing and reopening the column filter.

Expected behaviour: when a user sets the minimum or maximum value using the slider or directly in the corresponding fields, these values should be maintained, unless the user resets search.

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3153?planning-poker) with ZenHub @bogdanromanx @imsdu @samuel-kerrien @smitfire

**Comment by dhaneshnm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3153?planning-poker) with ZenHub @nicwells
