### ISSUE TITLE
Redesign proposal of KG handling of files

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#316]
The current KG API for handling files is similar to [attachments](http://docs.couchdb.org/en/stable/api/document/attachments.html) in CouchDB in the sense that binaries can be attached to user defined resources.

While this is appealing for use cases where a file is used as an additional representation of the resource (ex: a logo) this doesn't work very well in other scenarios which may be more likely to occur. For example: when Nexus is used as a data management platform where files are the core artifacts and resources (in json-ld format) are used to provide a description of these files or when a client would like to ingest the file data first and add a description of these files later as an incremental approach to organize data.

An additional problem with the current API is the current imposed workflow if the json-ld (rdf) representation of the resource depends on the Nexus metadata, for example:
1. create empty resource
2. attach a file to the resource
3. fetch the new resource metadata
4. update the json-ld (rdf) resource to include information from the Nexus metadata using a different vocabulary (for example: `dcat:downloadURL`)

The proposal would be to break the resource/sub-resource relationship between arbitrary resources and attachments and allow files as first class resources.

## Create a file:

`POST /v1/resources/myorg/myproj/files`
(multipart/form-data file upload)
where `files` expands to `https://bluebrain.github.io/nexus/schemas/file.json`\

or

`POST /v1/files/myorg/myproj`
(multipart/form-data file upload)

or
`PUT /v1/resources/myorg/myproj/files/a928dcb5-5e73-4668-9f9a-6ca92e8b1eff`
(multipart/form-data file upload)
where `files` expands to `https://bluebrain.github.io/nexus/schemas/file.json`

or
`PUT /v1/files/myorg/myproj/a928dcb5-5e73-4668-9f9a-6ca92e8b1eff`
(multipart/form-data file upload)

201 Created
```
{
  "@context": "https://the/context",
  "@id": "base:a928dcb5-5e73-4668-9f9a-6ca92e8b1eff",
  "_self": "https://nexus.example.com/v1/resources/myorg/myproj/file/base:a928dcb5-5e73-4668-9f9a-6ca92e8b1eff",
  "_mediaType": "image/jpeg",
  "_originalFileName": "myfile.jpg",
  "_bytes": 48144,
  "_digest": {
    "_algorithm": "SHA-256",
    "_value": "721d03056b82a22c54f30fd3c68b41dfe5f53828911984e47182d82cfbac9f36"
  },
  "_createdAt": "2018-09-17T14:54:42.939Z",
  "_createdBy": "https://nexus.example.com/v1/realms/myrealm/users/john",
  "_updatedAt": "2018-09-17T14:58:42.939Z",
  "_updatedBy": "https://nexus.example.com/v1/realms/myrealm/users/john",
}
```

## Discriminating between the file and the metadata

Content negotiation **could** be used to discriminate between the metadata and the file, for example:
```
GET https://nexus.example.com/v1/resources/myorg/myproj/file/base:a928dcb5-5e73-4668-9f9a-6ca92e8b1eff
Accept: application/ld+json
```
and
```
GET https://nexus.example.com/v1/resources/myorg/myproj/file/base:a928dcb5-5e73-4668-9f9a-6ca92e8b1eff
Accept: */*
```

## No need for multiple attachments

If files become a first class resource there's no need to support multiple attachments to a resource and discriminate using the recorded filename. Each file has its own lifecycle, tag subresources etc.

## Prevent conflating nexus generated metadata with application level vocabularies

Attachments are currently described using the `dcat` vocabulary just to avoid a client having to describe the attachment within the parent resource after uploading the file. This is bad for many different reasons, but most important: clients just reuse the same vocabulary and it's difficult to understand which metadata is generated by Nexus and which is user provided.

The proposal allows implementing the following workflow:
1. upload a file into the system (create a resource with the `file` schema)
2. create an additional resource to describe the file

## Conclusion

With this proposal there are a few benefits over the current implementation:
- the current relationship between files and their description can still be achieved in the same number of API calls
- files could be tagged
- files won't need to be discriminated through their filename
- use of arbitrary vocabularies to describe files
- remove unnecessary nesting of metadata (no need for `_distribution: {...}` anymore)
- simplify indexing (no need to store the attachment metadata in a separate named graph)
- we open the door to control replicas as subresources of file resources (as part of multiple storage backends)

**Comment by mdupont** [comment]
Seems like a good idea. A few comments:

- you're mentioning identifying metadata that is user provided and metadata that is generated by Nexus. How would this new design allow that?
- How would user be able to have multiple files sharing the same metadata (when you have the same file in 2 formats, or a preview of another file) in a way that is straightforward enough?
- I would **not** use content negociation to discriminate between a binary and its metadata. What if you want to send a link to download the resource (or see its metadata) to someone else who is non-technical and will just open a browser tab? Requiring content negociation should be kept for alternative / advanced use cases.

**Comment by bogdanromanx** [comment]
> you're mentioning identifying metadata that is user provided and metadata that is generated by Nexus. How would this new design allow that?
A client is free to describe a binary (user provided metadata) as a separate resource, for example:
```
{
  "@context": "https://the/context",
  "@id": "base:75857c5f-05af-43b0-8b0e-daf09bf30c42",
  "schema:name": "My uber dataset",
  "schema:license": "https://www.apache.org/licenses/LICENSE-2.0",
  "dcat:distribution": [
    {
      "dcat:downloadURL": "https://nexus.example.com/v1/resources/myorg/myproj/binary/a928dcb5-5e73-4668-9f9a-6ca92e8b1eff",
      "dcat:mediaType": "image/jpeg",
      "dcat:byteSize": 4096
    },
    {
      "dcat:downloadURL": "https://nexus.example.com/v1/resources/myorg/myproj/binary/48c0c50d-30b2-4ab7-9048-10d98c754f29",
      "dcat:mediaType": "image/png",
      "dcat:byteSize": 32768
    },
  ]
}
```
> How would a user be able to have multiple files sharing the same metadata (when you have the same file in 2 formats, or a preview of another file) in a way that is straightforward enough to make sense of? Use case: I query the API from the CLI, give me all the "files for this resource", including different formats, thumbnails / previews

The example above shows exactly that.

> I would not use content negociation to discriminate between a binary and its metadata. What if you want to send a link to download the resource (or see its metadata) to someone else who is non-technical and will just open a browser tab? Requiring content negociation should be kept for alternative / advanced use cases.

Interesting point. I would argue that if you send a link, the link would be to a web application that knows how to manage that and the link would encode the resource access id. I'm not sure it's useful to provide different addresses for metadata and binary as part of the API.

**Comment by MFSY** [comment]
It is not obvious how to provide two links: one for metadata and one for the binary with the binary data representation above. Can you provide an example ?

I still think content negotiation is a better and cleaner way to do this. Non technical users should be provided with a web page describing a given resource (in human readable way) rather than a direct link towards the REST API.

**Comment by pafonta** [comment]
> I would **not** use content negociation to discriminate between a binary and its metadata. What if you want to send a link to download the resource (or see its metadata) to someone else who is non-technical and will just open a browser tab? Requiring content negociation should be kept for alternative / advanced use cases.

I would agree with @mdupont for the data extraction from literature use case where the binary would be an Hypothesis JSON file.

To give some insights on what they do: they provide 3 links for 3 usages (key names are self-explanatory):
```
  "links": {
    "json": "https://hypothes.is/api/annotations/CIv0COvkEeiHiOtsffvkDQ",
    "html": "https://hypothes.is/a/CIv0COvkEeiHiOtsffvkDQ",
    "incontext": "https://hyp.is/CIv0COvkEeiHiOtsffvkDQ/www.ncbi.nlm.nih.gov/pmc/articles/PMC1225009/pdf/biophysj00053-0493.pdf"
  }
```
