### ISSUE TITLE
Studio - improve design to clarify the difference between Workspace and Dashboards

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3162]
**Motivation**
It has been reported that the current design can be confusing. We would need to make them visually more distinct. Designs proposal to be put together and review prior to implementation.

**Acceptance criteria**
1. Visual design conveys clearly the difference between Workspace and Dashboard
2. we do not change the UI component layout (i.e. it is purely styling)

**Mockups**
To be added when defined.

**Comment by bogdanromanx** [comment]
Closed in favour of #3183
