### ISSUE TITLE
Studio - unable to edit Studio markdown description through editor

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3168]
**Describe the bug**
As a user with Write access to a project, and thus, studio. I am not able easily edit a studio markdown description. 

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Open this [studio](https://bbp.epfl.ch/nexus/web/studios/public/thalamus/studios/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fe9ceee28-b2c2-4c4d-bff9-d16f43c3eb0f?workspaceId=https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F52e9c443-534b-4b2f-bd6a-ad340ae10d00)
2. While I can edit workspaces and dashboard, I am not able to edit the markdown description. 

Work around:
- open the project, 
- find the Studio resource, 
- open the resource panel
- open the Advanced View plugin
- open the Description tab to get access to the Markdown editor. This is the Markdown editor we would like to make much more accessible when viewing a Studio as a user with Write access.

**Expected behavior**
Expose a way to edit the description and present the Markdown editor from the Studio page.

**Comment by nicwells** [comment]
Aren't you able to access @samuel-kerrien  via the Edit Studio link (see below)? Or am I missing something? 

https://images.zenhubusercontent.com/103263633/7aa6ccb2-71bd-45bc-9793-c931e48906e6/studio_readme_edit.mp4
