### ISSUE TITLE
Docker instance does not list newly created domains

### ISSUE THREAD

**Issue by ehsanmaag** [BlueBrain/nexus#317]
Hello,
I am using a docker installation of Nexus to create a new domain.
The function Domain.create_new(...) returns the address of the new domain (e.g. <pyxus.resources.entity.Domain at 0x22edb0eb4a8>) however client.domains.read(...) returns None.
Any thoughts on where the issue might be? Any help is greatly appreciated!

**Comment by MFSY** [comment]
The discussion started [here](https://github.com/INCF/neuroshapes/issues/274)

**Comment by MFSY** [comment]
Resolved as mentioned [here](https://github.com/INCF/neuroshapes/issues/274)
