### ISSUE TITLE
Studio header/Description  should be editable

### ISSUE THREAD

**Issue by dhaneshnm** [BlueBrain/nexus#3175]
**Describe the bug**
Studio description should be editable in studio page. Currently, it can be edited only from resource view/description tab. It should have the same behavior as resource view description tab.  

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**

**Expected behavior**

**API calls (requests/responses)**
If applicable, add the minimum requests/responses to help explain your problem.

**Screenshots**

**Additional context**

**Comment by samuel-kerrien** [comment]
duplicate of #3168
