### ISSUE TITLE
Cannot Publish Schema

### ISSUE THREAD

**Issue by ehsanmaag** [BlueBrain/nexus#318]
Hi,

I am trying to publish a schema that I just created on Nexus v0, but I receive a "IncorrectRevisionProvided" error.

The schema is published both under 0.1.0 and 0.1.1. I used the following three methods to publish with no success:

```
#1.
client.schemas.publish(entity=schema,publish=True)

#2.
client.schemas.publish(entity=schema,publish=True,revision=1)

#3.
url_schem = "http://sprshnexus01.camhres.ca:8080/v0/schemas/kcni/redcap/questionnaire/v1.0.0"
url_schem_publish = "{}/config?rev=1".format(url_schem)
response = requests.patch(json={"published":True},url=url_schem_publish)
print(response.text)
```

Schema create and publish works using the same variables on Nexus sandbox.

Thanks in advance!

**Comment by MFSY** [comment]
This error usually occurs when the provided revision number is not the latest one. Can you get the schema:

````
GET http://sprshnexus01.camhres.ca:8080/v0/schemas/kcni/redcap/questionnaire/v1.0.0
````

and look at the nxv:rev value. That revision value should be the one used when publishing.

**Comment by ehsanmaag** [comment]
Thank you, that resolved the issue.
