### ISSUE TITLE
Studio - Improve Workspace / Dashboard layout

### ISSUE THREAD

**Issue by smitfire** [BlueBrain/nexus#3183]
**Motivation**
It has been reported that the current design can be confusing. We would need to make them visually more distinct and improve the user experience of leveraging the content of Studios.

**Agreed course of action**
Use ant design components to switch from current workspace dashboard layout to new dropdown tab navigation.

Move from tab based layout as seen below and currently in use to image 2:
![Screenshot 2022-04-06 at 13.13.14.png](https://images.zenhubusercontent.com/60f17c1bb2009493eade0339/e68be3c3-3fa7-4ce9-bf95-db05490e75af)

![Screenshot 2022-04-06 at 13.13.52.png](https://images.zenhubusercontent.com/60f17c1bb2009493eade0339/a7228725-12af-45e9-bd3c-7e9a21c6c4d3)
Source: https://ant.design/components/menu/#header

**Acceptance criteria**
1. Dashboards appear in dropdown below the tab based layout seen in image 2. 
2. Data table occupies full width below.
3. Notify user which dashboard is active from dropdown
4. Add a visual indicator to the right of the workspace to inform that the tab is also a dropdown with additional selections
5. Configuration of the Workspace / Dashboard should be intuitive and include creation, removal and hiding both Workspaces and Dashboards.

**Comment by samuel-kerrien** [comment]
This work supersedes #3162.

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1082

**Comment by samuel-kerrien** [comment]
As discussed today with @smitfire, we need to make sure we have the ability to add/remove Workspaces and Dashboards.

**Comment by samuel-kerrien** [comment]
Dhanesh tool over on Monday 2nd since Nick is away.
