### ISSUE TITLE
ACL documentation incorrectly shows "subject" instead of "sub"

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#319]
Example: `{
      "permissions": [
        "acls/read",
        "acls/write"
      ],
      "identity": {
        "realm": "realm",
        "subject": "alice"
      }
    }`

Should be: `{
      "permissions": [
        "acls/read",
        "acls/write"
      ],
      "identity": {
        "realm": "realm",
        "sub": "alice"
      }
    }`

According to the current behavior.

**Comment by bogdanromanx** [comment]
The new IAM v1 API that's being implemented will use `subject` instead of `sub`. The documentation reflects the new implementation.
