### ISSUE TITLE
Resource Panel - Copy URL isn't a valid Fusion URL

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3190]
**Environment**
Fusion 1.7.0
Delta 1.7.0
Chrome 100.0.4896.88 
MacOS 12.3

**Steps to reproduce**
1. open a [public studio](https://bbp.epfl.ch/nexus/web/studios/public/thalamus/studios/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fe9ceee28-b2c2-4c4d-bff9-d16f43c3eb0f?workspaceId=https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F52e9c443-534b-4b2f-bd6a-ad340ae10d00)
2. open [an entity](https://bbp.epfl.ch/nexus/web/public/thalamus/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fa3bb1dab-0493-4c4b-a345-7bd5902a3b47)
3a. Click Copy > URL : https://bbp.epfl.ch/public/thalamus/resources/https%253A%252F%252Fbbp.epfl.ch%252Fneurosciencegraph%252Fdata%252Fa3bb1dab-0493-4c4b-a345-7bd5902a3b47
3b. Copy > URL (with revision) : https://bbp.epfl.ch/public/thalamus/resources/https%253A%252F%252Fbbp.epfl.ch%252Fneurosciencegraph%252Fdata%252Fa3bb1dab-0493-4c4b-a345-7bd5902a3b47?rev=10

Both options lack the webapp path after the server: /nexus/web/

Possible issues:
- deployment configuration ?

**Comment by samuel-kerrien** [comment]
Behaviour is now different but still appears to fail.

Steps:
- open this entity (BBP only)
- open the menu and click Copy ID
- paste it again in a new browser window, it looks like https://staging.nise.bbp.epfl.ch/nexus%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20/bbp_test/akk_snap_test1/resources/https%253A%252F%252Fbbp.epfl.ch%252Fneurosciencegraph%252Fdata%252Fcircuits%252Fadc4155f-8865-48e4-9dd3-818d5a04ba2f

If I remove the superfluous spaces it appears to load the resource as expected.

I now see the /nexus after the host that was previously missing. But now I also see some %20 (encoded space).

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1106
