### ISSUE TITLE
Clarify requirements of Analysis Plugin

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3206]
**Description**
Provide the ability to manage grouped collections of images associated to a KG resource (e.g. a dataset)

**Acceptance criteria**

- [x] Dev team has reviewed mocks, identified points to clarify
- [x] Clarifications have been settled with Samuel and Jean-Denis
- [x] Mocks have been updated
- [x] Data Model has been defined
- [x] Implementation tickets has been created

**References**
- [Initial mocks](https://docs.google.com/presentation/d/14ZdGuJ8Zj5y1MqmGcN_qeil3ITEy9wwkC-DrK-bdhe8/edit#slide=id.p)

**Notes**
- when defining the data model, consider the existing data models in prod (e.g. Analysis, CampaignAnalysis, AnalysisReport, AnalysisResult etc.)

**Questions**

- Is this a public or BBP specific plugin?
  - BBP specific
- What is the full scope of the plugin?
  - image management for Datasets
- Is the real-estate of the plugin is sufficient for browsing/editing?
  - for the time-being, yes
- Are the operations supported for a section or for an image in the section (such as select/delete).
  - all operations on both
- restrictions on image size and format (eg: only jpeg and png under 5MB?).
  - only jpeg and png under 5MB
- What are the data models for which the analysis plugin should show.
  - Dataset
- Do we want to support the ability to download all the images or images per section?
  - no
- Are there captions for images? (title/text).
  - yes
- Does the caption belong to a section or individual images?
  - individual images
- How does the plugin behave when the user does not have a permission for write or read action on the storage where images are stored
  - the edit view should not be available if the user doesn't have resources/write on the origin project
  - the images should be displayed with a default placeholder "you do not have access to view this image" for which the user doesn't have access
  - a "you do not have access to upload an image" should be presented if the user doesn't have access to any of the origin project storages
- are we going to support thumbnails?
  - no
- are we going support an image carousel for the user to browse through the images?
  - yes
- are we going to support linking existing images? (for example from data cart)
  - no
- are we going to support PDFs or other file types similar to that? 
  - not at the moment

**Comment by smitfire** [comment]
Tickets 3317, 3318, 3319, and 3320 are tickets associated with this plugin so far.
