### ISSUE TITLE
Image Plugin: Add ability to download an image

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3214]
**Description**
Currently we can only list images in both List and Grid view. Each image can be opened to be viewed. But downloading is not offered. For that, you need to lookup the JSON-LD payload, get the ID of the corresponding File, open the Project Browse and search by ID. Too complicated.
Can we have a way to download a file from the listing and/or when in the image viewer mode.

On hover over image in all three sections show a download icon which triggers image download

Current plugin:

1. List View
![Screenshot 2022-04-28 at 16.17.43.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/19cbfdfa-c4d3-4135-b624-57e2cf5cd88c)

2. Grid View
![Screenshot 2022-04-28 at 16.24.17.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/21dd9db3-4f5e-4538-b7da-28b8f006e202)

3. Image Viewer
![Screenshot 2022-04-28 at 16.24.32.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/c6e71948-8b17-4602-8499-1a77318898dc)

**Comment by smitfire** [comment]
On hover over image in all three sections show a download icon which triggers image download
