### ISSUE TITLE
Project > Browse: page crashes when hovering mouse over an entity of type `Project`

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3243]
**Describe the bug**
Page crash when hovering with the mouse above an entity

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to Staging, 'Admin -> Project bbp -> nmc'
2. In that page there should be a "Project" entity named "nmc" on the left
3. Just hover over it

**Expected behavior**

No page crash, lol

**Screenshots**
![May-09-2022 10-38-52](https://user-images.githubusercontent.com/12729291/167401520-8b0e20a1-e0f5-4fa6-89be-7cbd43a12f29.gif)

**Additional context**
Env: Staging
User: adietz

**Comment by samuel-kerrien** [comment]
Happens in DEV too.

Nexus Delta v1.7.0+23-163b2734-SNAPSHOT
Nexus Fusion v1.7.0-25-gcf2fab81
