### ISSUE TITLE
Search: row selection checkboxes on search app not central

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3260]
**Describe the bug**

When I go to the search and I select only very few columns to show (like 1 or 2), and then I go over the row numbers the checkboxes are not shown centrally, they appear left of where the row number is displayed. See gif

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to 'Search'
2. Deselect most columns
3. Mouse over on row numbers

**Expected behavior**
The ceckboxes should appear centrally (as in the case when you have selected many columns)
**Screenshots**
![May-12-2022 10-41-54.gif](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/678003b5-aeb4-4791-80f9-3dc14397a065)

**Additional context**
Env: staging
User: adietz

**Comment by samuel-kerrien** [comment]
Hi @alex4200 
Can you give us info when submitting issues about the specific version of Fusion/Delta you are testing ? See the (i) icon in the header on the top right.
Also if you could mention the specific browser and version. Here is looks like it might be a browser specific issue...
Thanks !

**Comment by samuel-kerrien** [comment]
Cannot reproduce in Chrome and Firefox against Nexus Fusion v1.8.0-M15
