### ISSUE TITLE
Studio - plugin configuration is not saved

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3275]
Nexus Delta v1.8.0-M2
Nexus Fusion 1.7.1
Chrome 101.0.4951.41
Staging environment

**Description**
Steps to reproduce:
- Open a [sample studio](https://staging.nise.bbp.epfl.ch/nexus/studios/bbp_test/studio/studios/https%3A%2F%2Fbluebrainnexus.io%2Fstudio%2Fbbp-studio?workspaceId=https%3A%2F%2Fbluebrainnexus.io%2Fstudio%2Fbbp-studio---nmc-portal--workspace&dashboardId=https%3A%2F%2Fbluebrainnexus.io%2Fstudio%2Fbbp-studio---nmc-portal-studio--nwb-dashboard) (BBP only)
- enable plugin config and enable a few plugins
- click save button, note the message that the studio was updated
- re-open the config and note the plugin config is back to disabled.

Note that this was working in DEV before.

![Studio_pluginConfigNotSaved.gif](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/09411d01-b8ff-4663-858f-41a70a51773e)

**Comment by nicwells** [comment]
This is related to old studio that wasn't migrated properly and therefore doesn't have the correct studio context that includes "plugins".
