### ISSUE TITLE
No default workspace indicated when opening studio

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3301]
**Describe the bug**

When adding a dashboard to a workspace it is unclear to which workspace I add the dashboard to.

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to a studio which has some workspaces
2. Click on 'Add' for dashboard

**Expected behavior**

I expect some workspace selected by default, e.g. the first workspace.

**Screenshots**

![Screenshot 2022-05-27 at 10.45.23.png](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/fe94cd5a-0140-4459-bbda-0a2a6b84eeea)

**Additional context**
env: stage Nexus Fusion v.1.8.0-M3-5-g7c346d1e
user: adietz

**Comment by samuel-kerrien** [comment]
fixed in 1.8.0-M3
