### ISSUE TITLE
Studio: Inconsistent workspace highlighting

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3302]
**Describe the bug**

Workspaces are highlighted inconsistently. One Workspace is with white text, while the other is highlighted with blue. 

Both highlights are not very prominent, i.e. it is hard to see what workspace is highlighted/selected. 

Suggestion: White text in bold or larger font

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to 'Studios'
2. Select a Studio with multiple workspaces and dashboards

**Expected behavior**
Same highlighting, clearly indicating the selected workspace. 

**Screenshots**

![Screenshot 2022-05-27 at 11.13.07.png](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/bfc35aef-1201-4c10-a8da-0d010099c35c)
![Screenshot 2022-05-27 at 11.13.00.png](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/9149203f-2d99-4079-83d2-db274ace493b

**Additional context**
env: stage Nexus Fusion v.1.8.0-M3-5-g7c346d1e
user: adietz

**Comment by samuel-kerrien** [comment]
This issue with blue workspaces only seem to happen if these workspaces are empty (no dashboard created in them). If a workspace contains a dashboard, when clicked, it get highlighted white.
