### ISSUE TITLE
Studio: Unable to maintain ordering of dashboards in a workspace

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3321]
**Description**
In the [public thalamus studio](https://bbp.epfl.ch/portals/thalamoreticular), dashboards are prefixed with a number. The list of dashboard isn't going in ascending order.
To fix that, I have tried to edit the corresponding workspace, removed all dashboards and re-add them in the correct order. Upon saving, the order is somewhat randomised.

Several things that don't seem to work:
- attempting to re-order existing dashboard is tricky. Adding a dashboad is done at the top of the list. if you want to add them from 1 to 5, you have to add 5, then 4, then 3, then 2, then 1.
- Saving a list of dashboard appears to be randomized in the UI
- the JSON-LD payload isn't shaped to maintain the order of elements (currently the context define these elements as `@set`)

**Potential elements of solution to be tested**
- test the use of [@list](https://json-ld.org/spec/latest/json-ld/#example-52-specifying-that-a-collection-is-ordered-in-the-context) in the JSON-LD payloads and/or Context to maintain the order of the elements:
  - workspaces in the studio
  -  dashboards in a workspace

![Screenshot 2022-05-30 at 13.52.53.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/cc1a94ec-c8f0-40ff-85f2-8fd1e8bef0d4)

**Comment by bogdanromanx** [comment]
The root cause of the problem is that loading the individual tables is done asynchronously without retaining the order.
