### ISSUE TITLE
notification "cannot connect to JIRA" on public resources

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/nexus#3324]
**Describe the bug**
When opening the link  https://bbp.epfl.ch/nexus/web/public/hippocampus-hub/resources/a42f0923-2bfa-43fe-aff4-670155d286ee
from https://www.hippocampushub.eu/build/data/electrophysiology

I get this notification

![image](https://user-images.githubusercontent.com/5441880/171140640-ca1ee053-8ced-4a08-920e-5800a0d7d494.png)

**What part of Nexus is affected**
- [X] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to https://www.hippocampushub.eu/build/data/electrophysiology
2. Click on 'Download' for the first trace. (name is 95810006)
3. the Fusion GUI is open but a notification "cannot connect to JIRA" is displayed.

**Expected behavior**
No error notification

**API calls (requests/responses)**
If applicable, add the minimum requests/responses to help explain your problem.

**Screenshots**
screenshot provided

**Additional context**

**Comment by alex4200** [comment]
Related: #3259 , #3264

**Comment by bogdanromanx** [comment]
Agreed solution:
- introduce a new JIRA env variable that specifies a realm
- when this variable is present, display (enable) the JIRA plugin only if the current user is authenticated against the specified realm
- when the variable is absent maintain the current behaviour

**Comment by alex4200** [comment]
This issue seems to be fixed
