### ISSUE TITLE
Usability: Downloading a resource very confusing

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3333]
**Is your feature request related to a problem? Please describe.**

Supposing a user is looking at the page https://www.hippocampushub.eu/build/data/electrophysiology and wants to download a resource, for example the data for the first trace. (name is 95810006). 

Upon clicking the Download button no download is started, and the user is confronted with a Fusion entity page without any clearly labeled Download button. Unless the user is familiar with Fusion, the user will have Confusion. 

**Describe the solution you'd like**

Maybe a more prominently placed Download button when the entity contains downloadable content

**Comment by samuel-kerrien** [comment]
I suppose the issue reported here is a UX related issue in the [HippocampusHub](https://www.hippocampushub.eu). @alex4200 I recommend this be opened in the relevant project if you want the developer to address it. I propose it to be close in the Nexus project.

**Comment by alex4200** [comment]
Ok agreed
