### ISSUE TITLE
Project > Query > SPARQL: unable to edit query

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3343]
Affects Nexus Fusion v1.8.0-M3-1-g03ab697.

**How to reproduce**
1. open a project
2. open Query tab
3. Open SPARQL
4. Attempt to edit query, you can position the cursor, but you cannot modify the text. 
5. Click `Execute SPAQRL query`. The text editor now updates with what you typed. 

Notes:
- Elasticsearch queries do not appear to be affected.

**Comment by bogdanromanx** [comment]
Fixed in https://github.com/BlueBrain/nexus-web/pull/1125.
