### ISSUE TITLE
Studio: If the query of an Elasticsearch dashboard does not have a self, user cannot open resource panel

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3363]
Reported by @annakristinkaufmann 

**Description**

On a dashboard based on an ElasticSearch view in Nexus staging, I was no longer able to open a resource by clicking on a given row in the fusion table. This seemed still possible for resources on a dashboard based on a Sparql view

See the studio dashboard [here](https://staging.nise.bbp.epfl.ch/nexus/studios/neurosciencegraph/datamodels/studios/https%3A%2F%2Fbbp-nexus.epfl.ch%2Fstaging%2Fv1%2Fresources%2Fneurosciencegraph%2Fdatamodels%2F_%2F11426556-b37b-4cea-bec7-07d31c187bae?workspaceId=https%3A%2F%2Fbbp-nexus.epfl.ch%2Fstaging%2Fv1%2Fresources%2Fneurosciencegraph%2Fdatamodels%2F_%2F8ad23978-9185-4f8a-84e3-722f4021f0df&dashboardId=https%3A%2F%2Fbbp-nexus.epfl.ch%2Fstaging%2Fv1%2Fresources%2Fneurosciencegraph%2Fdatamodels%2F_%2F72206aa5-b1f9-4019-82ae-d86c25b0771b).

This is how a resource opens on a dashboard based on an Sparql query:
![Screenshot 2022-06-15 at 10.40.27.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/16e88bda-3085-4e38-879a-e5252b726384)

Clicking on a row on a dashboard based on an ES query does not open a resource:
![Screenshot 2022-06-15 at 10.26.51.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/35b0b10f-f186-44a0-abd6-cfe3b2e778c1)

**Proposal**
- Fusion could show a warning to the user upon saving a query that is missing

**Comment by dhaneshnm** [comment]
This is because the result did not include the "self" of the resource. If the "self" is induced,  the resource panel will open fine for both sparql and es.

I have modified the query to include self like below for the given dashboard and now the resource panel is opening  fine. I think the issue should be kept open because we  may want o make it work with out self (?).


```
{
  "from": 0,
  "size": 100,
  "_source": {
    "includes": [
      "*"
    ],
    "excludes": [
      "_schemaProject",
      "_outgoing",
      "_incoming",
      "_rev",
      "_deprecated",
      "_updatedBy",
      "_updatedAt",
      "_createdBy",
      "_createdAt",
      "_constrainedBy",
      "_project"
    ]
  },
  "fields": ["*"],
 "query": {
     "bool": {
      "filter": [
        {
          "bool": {
            "should": [
              {
                "term": {
                  "_deprecated": false
                }
              }
            ]
          }
        },
        {
          "bool": {
            "should": [
              {
                "term": {
                  "@type": "ProbabilityAnnotation"
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```
