### ISSUE TITLE
Report Plugin: Ability to group analysis by type

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3387]
**Motivation**
The report plugin can be presented on selected resource types, for instance nsg:DetailedCircuit or nsg:Simulation.

The users should be able to filter reports through these two filtering levels.
In the new report creation flow, users should be able to assign a category and a report type to their report.

**Acceptance criteria**
1. When a user views the report plugin of a dataset, a list of reports should be presented
2. When selecting a category, only display report entries that fall into that category.
3. If no type is selected, display all reports entries
4. Multiple categories and report types can be selected, in which case the union? of the report entries that fall into at least one of the selected categories should be displayed.
5. A report may have multiple categories and report types at the same time; category and report type should be handled as labels
6. The set of possible values for a category or a report type is defined as static configuration
7. The categories and report types presented while visualizing existing reports should be hidden if the available types is zero or one.
8. If there are reports that have a single or category report type, they should be displayed by default.
9. Proposed list of categories values (may be changed at a later date):

    If we are in a **circuit**, then we will have these categories of reports:
    - Anatomical,
    - Connectivity,
    - Volumetric,
    - Morphometric,
    - Synape.
  
   However, if we are in a **simulation**, we will have these categories of reports:
    - Spiking,
    - Soma voltage,
    - LFP,
    - VSD,
    - Plasticity.

10. Proposed list of report type values (may be changed at a later date):

   - **Validation** _(A report that compares a property against a target value that is derived from experimental data.)_
   - **Prediction**, _(A report that currently has no corresponding experimental data point but can be validated in the future.)_
   - **Analysis**, _(Any other report that is neither "Validation" not "Prediction".)_
11. When creating or editing a report, the possible categories and report types values are displayed such that the user can select zero or more values
12. The report list should be displayed as an accordion as depicted in the mockups below.

**Mockups**
[Screenshots or XD export if applicable.
](https://www.figma.com/file/lnhIF3FNFllLLzWdP0d3g4/BBP-%3E-Prototypes?node-id=313%3A104885)

**Not in scope**
1. Ability for users to define their own type values

### Mockups
1) Report section closed
![BBP_ReportPlugin_Step-01](https://user-images.githubusercontent.com/108661118/180953133-cf793f91-fde0-4dbb-b82c-124f42e1deaf.jpg)

2) Report section open - the first step
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/821d12a5-0ac5-4f19-85d6-e4d1857b4a0b)

2) Report section open - one category selected
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/6c02a415-d14c-498d-8dc5-f0138ef40578)

3) Report section open - one report type selected
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/1b3999ed-8ae6-4cd6-bbd3-f2904da4fc4f)

4) Report section open - report creation
![BBP_ReportPlugin_Creation.jpg](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/8678d630-0f8b-4da7-bea6-a05af19d7b54)

**Comment by loris-olivier** [comment]
@nicwells @smitfire 
`Scale` should be now called `categories`

**Comment by samuel-kerrien** [comment]
I see this ticket is still In Progress. Also that the mockups attached are using the old terminology `Scale`, @smitfire can you make sure to call it `Category` as agreed on more recent tickets ?
