### ISSUE TITLE
Analysis Plugin: Add a label to the image zoom slider

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3389]
### Description
Currently, the image zoom slider sits on the top right of the Analysis plugin. 
However it is not clear for a user what it's purpose it. 
Adding a label (e.g. Image size), could make this clearer.

**Comment by alex4200** [comment]
I do not see a label close to the image zoom slider.
![ksnip_20220720-081142](https://user-images.githubusercontent.com/12729291/179909495-d4d3aef0-b7a1-4629-a57a-5c1fd4d50e49.png)

**Comment by nicwells** [comment]
@alex4200 the zoom in/out icons were added along with helper text that will show up on hover to indicate what the slider does. I believe this is preferable to displaying textual labels which will clutter the display. However, when there are is no analysis report selected and no image thumbnails displayed it would be better if the slider didn't show. If we change it such that the slider is only shown when there are thumbnails present do you think that would be sufficient to convey the function of the slider?

**Comment by alex4200** [comment]
@nicwells  Yes I think that makes sense.
