### ISSUE TITLE
Studio: project listing of studios has broken links

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3396]
Reported by @annakristinkaufmann today.

In 1.8.0-M4, the links to studios in the project page are broken.

PR already available: https://github.com/BlueBrain/nexus-web/pull/1133

**Comment by alex4200** [comment]
This issue does not seem to be resolved. Original screen recording from Anna: 

https://user-images.githubusercontent.com/12729291/179964293-1bcbe615-c32b-4082-8040-f5dfc4545e57.mov

seems you have to go to "Admin" -> "neurosciencegraph" -> "datamodels" and click on "Studio" and then on "Knowledge Graph Ontologies and schemas" (as shown in the recording). 

User: adietz
Versions: 
Nexus Delta v1.8.0-M2
Nexus Fusion 1.8.0-M6

**Comment by alex4200** [comment]
This issue seems to have been fixed in stage.
