### ISSUE TITLE
Report Plugin: Support for Asset revision

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3400]
### Description
Often, scientists will iterate on the creation of a plot (correction, font tweaking, ...).
It would be useful to add an image as a revision of an other.

### Acceptance criteria
- users can only upload a new revision is they have resources/write (icon would not show if acl is missing)
- When replacing the asset, we are creating a new revision of the same underlying `File`
- The File URL in the JSON-LD payload should not point a revision to ensure we are always getting the latest.

## Not in Scope
- checking of the files/storages ACLs

### Workaround
For now, it was agreed that removing a plot and adding an other one would suffice.

## Mockups
*Asset visualization (default)*
![Report (plugin) - Revision step 1.jpg](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/e89e6fb3-6818-42c2-a13c-ec3b57156c0b)

*Replace the asset button on the right of the info box*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/7c2eca9d-5174-4ea2-9b58-637f6f3f09a4)

*After clicking on the replace asset*
![Report (plugin) - Revision step 2.jpg](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/12cd12a5-f2f4-422b-a913-667febca28a3)

*If the user doesn't have the proper right to modify the asset*
![image](https://user-images.githubusercontent.com/108661118/185924124-ba4d6e6f-7705-4038-9e3c-9a0e0614a0b8.png)

*Tool tip on hover for the user without editor access*
![image](https://user-images.githubusercontent.com/108661118/185924236-1a02ce33-7274-4a40-8e34-52f2b9253e05.png)

**Comment by smitfire** [comment]
Not sure if this requires much change to the data model, seems like we already support revisions for images / files and it would just be a matter of exposing that in the UI and editing the upload, edit UI to suit revisions. If my assumptions are correct then I estimate 3

**Comment by smitfire** [comment]
need to rebase and fix conflict
