### ISSUE TITLE
Analysis Plugin - Support multiple Analysis Groups

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#3420]
**Motivation**
Analysis reports may be categorised with a higher level axis that describes the underlying analysis kind. Example values for this axis could be:
- Analysis
- Validation
- Prediction
Users should have a quick way to view/edit Analysis reports that fall under one of the categories described by this additional axis.

**Acceptance criteria**
1. ...

**Mockups**
Screenshots or XD export if applicable.

**Not in scope**
1. ...

**Comment by samuel-kerrien** [comment]
was a duplicate of #3387
