### ISSUE TITLE
SPARQL query does not show editions

### ISSUE THREAD

**Issue by crisely09** [BlueBrain/nexus#3430]
**The bug**
The Query Browser with SPARQL does not show any changes in the editor after typing.

**Affects Nexus Fusion**

**To Reproduce**

1. Go to 'https://bbp.epfl.ch/nexus/web/'
2. Click on 'Admin'
3. Select an Organization, for example 'bbp'
4. Select a project, for example 'neocurator'
5. Click on 'Query'
6. Select 'SPARLQ' from the options displayed on the left
7. Try editing the query
8. See the error

**Expected behavior**
Trying to edit the query, the editor for the query does not change, it seems like nothing was added, but all the changes appear only when the `Execute SPARQL query` bottom is used.

**Comment by imsdu** [comment]
Fixed in https://github.com/BlueBrain/nexus-web/pull/1125
