### ISSUE TITLE
Global: Top bar & toolbox

### ISSUE THREAD

**Issue by loris-olivier** [BlueBrain/nexus#3435]
## Motivation
Refine the top bar in order to build a clearer structure on the different action globally possible. The goal is to regroup central actions in a lateral bar which group the search function, the studio and workflow access in addition to the documentation.
The top bar now contain the logo and the user dropdown. This one contains the the login access, the copy token function, the about section (about Fusion) and, if logged in, the logout function.

## Acceptance criteria
- The user should see is name in the dropdown on the top bar.
- When the user click on his name content appear below in a dropdown way.
- The content is made of the copy token function, an about button which trigger an overlay with the information on the current app version, and finally the logout button.
- The side tool bar is made of four buttons.
- The first button of the tool bar trigger the search function
- The second button leads to the list of the existing studios
- The third button leads to the list of the existing workflows
- The fourth button leads to the documentation

#### New Toolbar
![BBP_Fusion_Topbar.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/f74b9d5f-158e-4c1c-8c20-f9e84407d382)

### User dropdown (closed)
![(USER) button closed.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/5943126d-dbc9-4f47-b11f-f1c73b4092a3)

### User dropdown (open)
![(USER) button open.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/360dca1e-5fe4-4e58-ba5d-075123ba00df)

### Side toolbox
![New toolbox.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/a5467e2e-00a5-4e81-ad0a-7dffc2853967)

**Comment by samuel-kerrien** [comment]
Will close this ticket as this has been split in 2 tickets
