### ISSUE TITLE
Search: new interface and behaviour

### ISSUE THREAD

**Issue by loris-olivier** [BlueBrain/nexus#3436]
## Motivation
Giving the user a more immersive, simple and clean search experience. The goal is to start with this version and then enrich it with filters based on the BBP workflow.

## Acceptance criteria
- Open the search input when clicking on the lateral toolbox 
- Have a pre-search filter in order to determine what kind of results is expecting
- In this version 1, only resources, projects and studios are available to be filtered as category.

## Mockups
![BBP_Search_Default](https://user-images.githubusercontent.com/108661118/182365553-9b6a20f8-488f-4339-b8d5-d47b9dcacd22.jpg)

## Figma 
https://www.figma.com/file/lnhIF3FNFllLLzWdP0d3g4/BBP-%3E-Prototypes?node-id=420%3A119441

## Not in scope
- highlighting will be defined in a separate ticket.
- for now do not show the Resources list

**Comment by samuel-kerrien** [comment]
As discussed with @loris-olivier, closing this ticket as a new one will be created with the result of ongoing user research.
