### ISSUE TITLE
Side Panel (design): new visual

### ISSUE THREAD

**Issue by loris-olivier** [BlueBrain/nexus#3439]
## Motivation
Give some focus on the side panel when open. The goal is to create a clearly different instance for a dataset and its associated plugins

## Acceptance criteria
- Clearly define what belongs to overall informations (the header) and what belongs to the different plugins.
- Give access to a resize handle on the side to have more or less space inside the panel.

## TODO
☑️ show a message when resource is deprecated
☑️ a resource can have multiple types
☑️Complete the Copy button
  ☑️ show the URL, ID, Address with revision
  - how to deal with tags?
☑️ Missing 'add to cart'
☑️ When an older revision is selected, we are missing a message warning the user. In addition when this message is displayed, provide a link to the `latest`.
![Screenshot 2022-08-08 at 13.45.43.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/67b42ad9-51db-42bb-adcf-8d38e46ae33a) 
☑️ Missing links to Organization and Project

## Not in Scope
- editing the name of the resource
- Brain region in the head informations

## Figma
https://www.figma.com/file/lnhIF3FNFllLLzWdP0d3g4/BBP-%3E-Prototypes?node-id=57%3A28436

## Mockups
**Global Side Panel**
![BBP_SlidePanel_Global](https://user-images.githubusercontent.com/108661118/183443302-a1520969-a1b5-48b3-a41c-907f8749667d.jpg)

**Three size states**
*Narrow*
![BBP_SidePannel_Narrow](https://user-images.githubusercontent.com/108661118/183443769-b732e4d2-ab66-445a-a785-5cbb32fb588d.jpg)

*Extended*
![BBP_SidePannel_Extended](https://user-images.githubusercontent.com/108661118/183443825-78c4002e-e27c-44b0-ba31-a5ef3d2f8499.jpg)

**Measurement**
<img width="1716" alt="BBP_Sidepannel_Guide_01" src="https://user-images.githubusercontent.com/108661118/183444231-473a5d2f-fc6d-48d8-be0f-c5a8509fd2f4.png">

**Dropdown drawer**
![BBP_Plugins_drawer-information.jpg](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/b7bd3e92-5655-4b58-9c6c-fdcc75e8fe9f)

**Dropdawn**
![BBP_Plugins Content.jpg](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/7e644464-b98c-4160-a228-5e0bfd90f793)

**Comment by samuel-kerrien** [comment]
Closing now, will be restructured as an other set of tickets.
