### ISSUE TITLE
Blocker: Unable to login to Fusion stage to test from home

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3443]
**Describe the bug**

Unable to log in to stage environment. When I try to log in on the stage environment via BBP as user "adietz" and click "Sign in" I get a 502 error. 

See network error also below. 

Same issue also happens for Nexus prod.

**What part of Nexus is affected**
- [x] Fusion

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to the staging environment
2. Click on 'login'/'BBP'
3. Enter username and password, click "Sign in"

**Additional context**
- Environment: staging
- Different browsers user (private window, cache cleared)
- Via VPN

**Comment by imsdu** [comment]
Fixed.

Cause: The token was too large for a proxy because it contained many groups
