### ISSUE TITLE
Report Plugin: Support ability to capture and present Tool that generated report

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3453]
## Description
The scientists would like to capture how the assets were generated in the report. 
To do so, they will need to capture :
- where the code is located (link to git repo with hash/tag), 
- how they ran the code to generate the asset.
There might be multiple tools described with their own git link and description.

## Acceptance Criteria
- The user should be able to easily link his code (in git) to the report
- The user should be able to describe the process that generated the code to enable reproducibility
- The users should be able to update both the link and the description
- The report view should present the tools (git link and desc.)
- We should support the ability to have more than one SoftwareAgent attached to the Report.

TODO discussion to be had to finalise data model.
  - how to capture the SoftwareAgent (inside the report of as a separate resource)
TODO remove the version section (i.e. revision, person and date)
TODO @samuel-kerrien revise the phrasing of the button to add a tool
TODO revise text describing `tools`

## Mockups
**Two tools registered in the report**
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/9a0b7ae3-1583-4a1c-b1fd-44c4e662d845)

**Report creation: capture tool(s) that generated report (default view)**
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/f4e1ef2d-b868-413a-a3fb-fc9f53fb80f3)

**Report creation: capture tool(s) that generated report (adding one tool)**
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/747acb97-405a-41b5-89cc-b308436c0f42)

**Report creation: capture tool(s) that generated report (tool added)**
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/293138d4-b9e2-4bc9-816b-6ca8dc0beb49)

**Comment by smitfire** [comment]
Looks like we are just adding more fields to the Report data model and building the UI. I take it we are not going to verify that the links are pointing at an appropriate file or anything like that. Still quite a bit of work to do so my estimate is (5)

**Comment by loris-olivier** [comment]
@nicwells 
When you say "What would the screen look like if there aren't any reports added? "
Do you mean if the user fills all the fields except the 6. report generation?
