### ISSUE TITLE
Report Plugin: Ability to define and present definitions of categories and report types

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3454]
## Description
The scientists have described the need to customise the list of report categories on a per `type` basis (e.g. DetailedCircuit, Simulation).
Each of these categories should have a `definition` and this should be made visible in the user interface.

## Acceptance Criteria
- Fusion can be configured to trigger rendering of the report plugin for specific resource types.
- For each supported types, there should be a list of categories to be presented to the user.
- For each category, there should be a definition.
- The user interface should show both the relevants categories and their respective definition.
- The report categories are the same across all supported types.
- Both DetailedCircuit and Simulation should work with the report plugin.
- The definition for the categories and types comes from configuration (not from source code).

## Categories definitions

**CIRCUIT**

**"Anatomical"**: A report relating to the cellular contents and placement of the circuit. For example, to neurons and the locations of their somata or dendrites.

**"Connectivity"**: A report relating to the structure and topology of synaptic connections, analyzing the underlying directed connectivity graph.

**"Volumetric"** A report that explicitly considers the volume and/or shape of the modeled space. For example, the density of dendrites of synapses within a cubic volume.

**"Morphometric":** A report relating to the shape or morphology of the cells in the circuit. For example, counting the number of dendrite bifurcations.

**"Synapse":** A report relating to properties of synaptic connections. Unlike "Connectivity" it does not reduce them to a graph and instead considers properties of individual synapses, such as their dendritic locations or physiological parameters.

--

**SIMULATION**

**"Spiking":** An analysis report based on the spiking activity of the simulated neurons.

**"Soma voltage":** An analysis report based on the (subthreshold) soma voltage traces of the simulated neurons.

**"LFP":** An analysis report based on traces of extracellular potential calculated from the simulations.

**"VSD":** An analysis report based on predicted VSD images calculated from the simulations.
"Plasticity": An analysis report based on the temporal evolution of plasticity-related synapse parameters.

** REPORT TYPE**
**"Validation":** A report that compares a property against a target value that is derived from experimental data.

**"Prediction":** A report that currently has no corresponding experimental data point but can be validated in the future.

**"Analysis":** Any other report that is neither "Validation" not "Prediction".

## Mockups
*1. Circuit*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/df6e8182-6337-46a1-9662-dd395d6afbbf)

*2. Simulation*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/0389d8d6-7ffe-4db9-9985-d5fd69ec761a)

## Not in scope
- Loading of categories from ontology

**Comment by smitfire** [comment]
I think these types get set quite early on in the process so not sure if a UI to expose and edit them is currently an option. Not with our current implementation anyway. I don't feel comfortable estimating since I'm not sure of the solution nor what the mocks look like.
