### ISSUE TITLE
Topbar

### ISSUE THREAD

**Issue by loris-olivier** [BlueBrain/nexus#3496]
## Motivation
Minimise the elements on the top bar and unite some current functionalities inside the user dropdown.

## Criteria of Acceptance
- User should be able to have a status of the connected profile on the closed dropdown 
- The Name of the user (from decoded JWT token) should be shown when logged in, otherwise "Login" should be shown.
- User should be able to login by clicking on the button and choose between BlueBrain and github
- User should be able to copy token from the user dropdown
- User should be able to jump to documentation through a link in the dropdown
- User should be able to trigger a modal by clicking on a link in the dropdown called `About`

@loris-olivier How to show the additional configured links (Protege, BMO voc, Atlas)

## Prototype (Figma)
https://www.figma.com/file/lnhIF3FNFllLLzWdP0d3g4/BBP-%3E-Prototypes?node-id=58%3A37022

**Comment by samuel-kerrien** [comment]
Just echoing a discussion we had last week, can we think about how to integrate configurable external documentation in this design ?
