### ISSUE TITLE
Plugin Report: arrangement

### ISSUE THREAD

**Issue by loris-olivier** [BlueBrain/nexus#3498]
## Global fonts
Do we have that in the global styling for the entire html?

```
text-rendering: optimizeLegibility;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

## Optimisation
- [x] We need the active report indicator above the report drawers
- [x] There should be only two category type: Analysis and validation
- [x] Have a divider and margin 12px 0 between the Categories and report type

## Styling
- [x] Fields being edited should have a light blue background (#E6F7FF)
- [x] Label of categories and report type should be lighter (Titillium Web semi-bold)
- [x] Name of report should be in Titillium Web Bold 30px
- [x] Every report dropdown should have a padding of 40px 30px
- [x] Label of category type on the report should be lower down to semi-bold
- [x] In edit mode: section title (such as categories, report type, tools) should be in 16px, in semi-bold, all uppercase
- [x] Button add tool should have a padding of: 16px 20px
- [ ] Button edit and discussion should have this padding: 12px
- [x] Remove border around button "Read more" and add border-radius: 4px
- [x] Remove border around the boxes Report Category and Report type (only one border-right except last-child)

## Context
*Active reports information*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/2b6e883e-a12f-4d99-988f-213cb418bb86)

*Label of categories*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/5f53deb1-7507-49a1-b89b-d607acc0121e) 

*In edit mode, blue background on editable fields*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/643d38bc-78c4-4e3d-894b-3755b05288d5)

*Divider and margin between categories and report type*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/d79c6935-19da-40ce-8a89-edc63ef9cabf)

*Name of report*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/300ff84a-9607-4f21-985d-e1b114a91d02)

*Padding on the report dropdown*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/651caccf-c7ea-46d6-a70c-10eafb881447)

*Lowering down the weight*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/512d14a5-390a-4a8a-b0a0-d57b3dee620a)

*Section title in uppercase, semibold and 16px*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/0ae4c4a1-68d7-4707-a8eb-b4a834ad7367)

*Button add tool, add more padding: 16px 20px*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/333433e5-3216-40cf-9f5c-2146c682f5c6)

*Remove prediction*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/08b83592-5b45-4786-a7a9-609c439da651)

*Button edit and discussion with more padding (12px)*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/922f74be-c9bb-4c0e-8483-c03923e31b8e)

*Remove border around the read more button*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/116e2b7a-078b-4924-9b57-69bbd680bd90)

*Remove border around the boxes Report Category and Report type (only get a border-right, except on last-child*
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/64ab5138-206e-4f00-a79a-fdf447d1fb0f)

-> Like this for the box
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/af9f3549-150a-4dee-a5bf-bf0237e36c21)

**Comment by smitfire** [comment]
@loris-olivier one of the things on the ticket was undone because it messed up some of the styles were messed up as a result. please follow up when back from holiday :)
