### ISSUE TITLE
Report Plugin: Edit form shows empty category when no category found in the underlying data

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3499]
## Description
In the case where a Report does not contain a Category, when editing the report, a Category with empty text is rendered. The user has to remove it before added one of the default choices offered. This happened so far on some old report on which no Category has been defined (JSON-LD property was missing).

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1164
