### ISSUE TITLE
Retrieve Nexus metadata when fetching  resource original payload

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus#3512]
**Motivation**
Currently [fetching a resource original payload](https://bluebrainnexus.io/docs/delta/api/resources-api.html#fetch-original-payload) is not retrieving the nexus metadata (ie. _rev, _self, ...). Clients that need to get resources as they were submitted and the Nexus metadata at the same time have to make two http calls slowing down their workflow. It would be good to retrieve at the same time and in one http call the original payload of a resource and the resource nexus metadata

https://bluebrainnexus.io/docs/delta/api/resources-api.html#fetch-original-payload

**Acceptance criteria**
1. When performing this api call GET /v1/resources/{org_label}/{project_label}/{schema_id}/{resource_id}/source?rev={rev}&tag={tag}
then the resource original payload should be retrieved along with the corresponding metadata
2. Only applies to resources (ignore param if on other types)
3. include [documentation](https://bluebrainnexus.io/docs/delta/api/resources-api.html#fetch-original-payload)
4. includes Unit tests
5. includes integration tests

**Comment by imsdu** [comment]
Not to break compatibility, I would enable this via a new parameter `annotated` (any better name is ok) that would allow to add the metadata to the original payload.
Just to avoid any misunderstanding, the result would have that shape:
```json
{
 "name": "...",
 "description": "...",
 "_createdAt": "...",
 "_rev": 5.
  "_self": "..."
}
```

**Comment by MFSY** [comment]
Hi @imsdu ,
Thank you for looking into this. I guess here name and description are user data as registered in the first place. If yes than I'm okay with this.
