### ISSUE TITLE
Report Plugin - styling of discussion button

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3524]
## Description

The styling of the button has gone wrong compared to previous versions. See capture below.
Specifically:
- mis-aligned with edit button
- discussion icon off center

![Screenshot 2022-10-20 at 10.06.36.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/a61ce2a6-bde3-4f23-807e-f8a652c76730)

**Comment by imsdu** [comment]
Fixed #3534
