### ISSUE TITLE
Report Plugin: Ensure assets attached to a report can be retrieved using the _self of the underlying File

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3548]
## Description
When the report plugin creates an asset upon upload of an image of PDF file, the resulting data model looks like so:
```
{
  "@context": [
    "https://bluebrain.github.io/nexus/contexts/metadata.json",
    {
      "@vocab": "https://neuroshapes.org/",
      "derivation": "http://www.w3.org/ns/prov#derivation",
      "nxv": "https://bluebrain.github.io/nexus/vocabulary/"
    }
  ],
  "@type": "AnalysisReport",
  "types": [
    "Analysis"
  ],
  "categories": [
    "Synapse"
  ],
  "name": "my_snapshot_test",
  "description": "Example Report on a Simulation",
  "derivation": {
    "entity": {
      "@id": "<ID of the resource>",
      "@type": "SimulationCampaignConfiguration"
    }
  },
  "hasPart": {
    "distribution": {
      "@type": "DataDownload",
      "contentSize": {
        "unitCode": "bytes",
        "value": 622605
      },
      "contentUrl": {
        "@id": "<ID of an image File>"
      },
      "digest": {
        "algorithm": "SHA-256",
        "value": "b437759f5939bc03a6bb5267bfa5dd6ebddc0c7388a74bfc5b71a24459d58ba2"
      },
      "encodingFormat": "image/png",
      "name": "snapshot.png"
    }
  }
}
```

We came to realise that when users use Nexus Forge to shape up this payload, the `distribution`'s `contentUrl` points to the underlying `File`'s `_self` instead of its `@id`. In this case, the plugin is not able to render the image File. Changing it back to a @id, the plugin is able to render the image.

## Acceptance Criteria
- When we upload an asset (image or PDF), either when creating or updating a report, we need to make sure that the `contentUrl` of the `distribution` points to the `_self` of the underlying `File` instead of its `@id`.
- When presenting a report, we need to make sure that we can read the preview of an image or PDF file when the `_self` is used. 
- in order to make the plugin more resilient, we should support either `@id` or `_self`.

TODO
- creation and editing should generate the right data model (use _self)
- improve management of data with @id and convert into _self to make the plugin more resilient
- Handle the case when fetching the file returns a HTTP 403 or 404 -> show clear error message
  - Try to get the metadata of the File using _self with the Accept-Header `application/ld+json` to get the metadata
  - Reference: https://bluebrainnexus.io/docs/delta/api/files-api.html#fetch
  - Once we know if the entity exist we can choose to show an error message or an image if you get an HTTP 200

**Comment by smitfire** [comment]
https://github.com/BlueBrain/nexus-web/pull/1175
