### ISSUE TITLE
linking a file on GPFS should require "content-type"/_mediaType to be set.

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/nexus#3620]
**Motivation**
The current behaviour is to "autoguess" the content type based on the file extension. This leads to inconsistent behaviour where some files have different content-type than others.
For instance, ".asc" will get an "application/pgp-signature" content-type, which is not the expected value.

**Acceptance criteria**
When linking an file, the _mediaType/content-type should be mandatory in the request body.

**Comment by jdcourcol** [comment]
@samuel-kerrien Can you give any update here ?

**Comment by jdcourcol** [comment]
@samuel-kerrien +1

**Comment by imsdu** [comment]
Done with #4312
