### ISSUE TITLE
Log slow queries submitted to Blazegraph

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#3716]
**Motivation**
Users run sometimes complex queries that can timeout and in some cases crash the Blazegraph instance.
It would be a good thing to log for these queries:
* The project and view
* The query itself
* How much time it took (or the timeout)
* When it happened
* Who submitted it

**Acceptance criteria**
1. When a query timeouts or exceeds a configured execution time
2. We log it in a dedicated table
3. The queries older than a given ttl will be automatically deleted

**Comment by samuel-kerrien** [comment]
A logical follow-up of that is to expose it in Fusion, in a specific project and maybe also across all projects.
I would make that an other ticket once we are there with this one.
