### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by bilalesi** [BlueBrain/nexus#3762]

**Comment by bilalesi** [comment]
# Requirement

**I. Resolvers section**

1. List
    1. Type
    2. Priority
2. Create Resolver (payload)

**II. Quota Section**

1. Data Volume:
    1. Total Resources (It exist only the count)
    2. Total Quota (It exist only the count)
2. Storage:
    1. Storage name
    2. Max file Size (GB)
    3. Total Files
    4. Space Used
    5. Capacity

**III. Danger Zone Section**

1. Un-deprecate Project
2. Delete Project

**V. Storage Section**

1. Fetch List
    1. Location
    2. is Default
    3. Endpoint
    4. Max File Size
    5. Read
    6. Write
2. Create Storage (payload)
3. Edit the configuration of an existing Storage.

**Comment by samuel-kerrien** [comment]
Content of this ticket migration to relevant existing tickets.
