### ISSUE TITLE
Endpoint to aggregate Types across all projects - filter by created/updated user

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3775]
## Description
In order to build the new Fusion landing page, and the My Data panel specifically (#3774) that allows user to see their data across project and to filter by Type, we need a new Delta endpoint allowing:
- Aggregation by type across all user readable projects
- Ability to filter by creation/update user (in this case, the user that is currently using Fusion)
- Ability to filter by project

Task 1 - propose a technical plan

There will be an other ticket later for the implementation.

**Comment by imsdu** [comment]
Done in #3944
