### ISSUE TITLE
Project > Settings > Views – expose indexing errors

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3818]
## Description
Now that we have the ability to list views in the Settings, let's add visibility on:
- the count of indexing errors recorded in Delta,
- the actual errors recorded so the user can inform themselves.

The recorded errors have configurable TTL.
The count of errors is not subject to that TTL.

Ideas to integrate in the design:
- Have a way to view the detailed errors
- For a given error, have a way to navigate to the resource.
- Fixing the indexing error will not remove the logged errors. Can we try to give a warning to the user.

**Comment by bilalesi** [comment]
- Views Api documentation need to be updated to list the response when an error occurred
