### ISSUE TITLE
Unable to access /orgs and /projects when not logged in

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3997]
## Description
Currently in Fusion, when not logged in and navigating manually to /orgs or /projects, I am being redirected to the login page. However, in the case where a deployment of Nexus has data available to Anonymous users (i.e. not logged in), it might make sense to let them explore organizations and projects that have ACLs enabling them to read. 

This is currently preventing some users to a local deployment of Nexus while not having a Keycloak deployed.

**Comment by olivergrabinski** [comment]
Might be related to this, but in the prod deployment when I am looking at a studio as anonymous, I am unable to click on a resource and get the side panel for that resource.
