### ISSUE TITLE
ACL endpoint appear to not be listing exhaustive ACLs on organization and project

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#4003]
## Description
While investigating ACLs through the API using Postman with @bilalesi and @olivergrabinski, it appeared that  when fetching the ACLs for a specific project in production (e.g. public/thalamus), we could see ACLs defined on `/` but not on the organization or the project. The path entries were there, but the acl array was returned empty. Checking in the primary store, we could see the acls (permission+identity).

The investigation was done with a service account that had acls/read on `/` and the `ancestors` parameter was set to `true`.

**Comment by olivergrabinski** [comment]
Marked this as closed due to the `self` query parameter solving the question.
