### ISSUE TITLE
ES Indexing problem, expanded field uris for fields specified in the ES view mapping

### ISSUE THREAD

**Issue by ssssarah** [BlueBrain/nexus#4006]
**Describe the bug**
When I query an elastic search view that has a mapping, I get the appropriate results from the view, but the mapped fields are present twice, once with the expanded uri, once without the expansion. I have another query that fails applied to this very same view, that needs this mapping to define a field as a dense_vector

**What part of Nexus is affected**
- [ ] Fusion
- [x] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:

1. Query the view https://bbp.epfl.ch/nexus/web/public/thalamus/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fviews%2Fes%2Fneurite_features_similarity_view
2. Derivation, embedding, and generation fields are present twice, once normally, once with the extended uri https://neuroshapes.org/___"

These 3 fields happen to be the only ones that are present in the mapping. 

**Expected behavior**
I would expect the field to be present once, without being expanded.

**API calls (requests/responses)**

POST 
url: https://bbp.epfl.ch/nexus/v1/views/public/thalamus/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fviews%2Fes%2Fneurite_features_similarity_view/_search
body: 
```
{
  "query": {
    "term": {
      "_deprecated": false
    }
  }
}
```

**Additional context**
I noticed this problem started to happen at a similar time as a querying problem that I have which is: 

POST 
url: https://bbp.epfl.ch/nexus/v1/views/public/thalamus/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fviews%2Fes%2Fneurite_features_similarity_view/_search
body: 

```
{
  "from": 0,
  "size": 10000,
  "query": {
    "script_score": {
      "query": {
        "bool": {
          "must_not": {
            "term": {
              "@id": "https://bbp.epfl.ch/neurosciencegraph/data/embeddings/19276114-caaa-4b0e-a9e2-70deb39983a2"
            }
          },
          "must": {
            "exists": {
              "field": "embedding"
            }
          }
        }
      },
      "script": {
        "source": "if (doc['embedding'].size() == 0) { return 0; } double d = l2norm(params.query_vector, doc.embedding); return (1 / (1 + d))",
        "params": {
          "query_vector": [
            -0.08260509371757507,
            -0.08260509371757507,
            -0.08920200914144516,
            -0.07583354413509369,
            -0.07291055470705032,
            -0.06836287677288055,
            -0.06377685070037842,
            -0.06357715278863907,
            -0.06084422767162323,
            -0.06160489469766617,
            0.1739482581615448,
            0.1739482581615448,
            -0.09933186322450638,
            -0.09933186322450638,
            0.034694548696279526,
            0.034694548696279526,
            0.028268376365303993,
            0.028268376365303993,
            0.04288502782583237,
            0.04288502782583237,
            0.020606422796845436,
            0.020606422796845436,
            -0.02916070818901062,
            -0.02916070818901062,
            -0.044178251177072525,
            -0.044178251177072525,
            -0.04115918278694153,
            -0.06349165737628937,
            -0.011873705312609673,
            -0.06435810029506683,
            -0.06141848489642143,
            -0.06166774407029152,
            -0.04553811252117157,
            0.014931158162653446,
            -0.04241690784692764,
            0.02023460529744625,
            -0.04855116084218025,
            0.02579980157315731,
            -0.07622093707323074,
            -0.08066285401582718,
            -0.009105970151722431,
            0.08463781327009201,
            0.005502933636307716,
            0.07585471123456955,
            -0.0870722308754921,
            -0.08159056305885315,
            -0.09245093166828156,
            -0.02511134184896946,
            -0.03884533792734146,
            -0.03554901108145714,
            -0.03346136957406998,
            -0.019801082089543343,
            -0.07444776594638824,
            -0.07599923014640808,
            -0.07427100092172623,
            -0.07645842432975769,
            -0.07219020277261734,
            -0.07093288749456406,
            -0.07786533236503601,
            -0.07931996881961823,
            -0.05971261113882065,
            -0.07173869013786316,
            -0.05890446528792381,
            -0.07718859612941742,
            0.04353219270706177,
            0.000733999942895025,
            -0.008859426714479923,
            0.020699823275208473,
            0.05576733499765396,
            0.05576733499765396,
            0.06826351583003998,
            0.06826351583003998,
            -0.09947890043258667,
            -0.09947890043258667,
            -0.09549856185913086,
            -0.09549856185913086,
            0.0,
            0.0,
            -0.09547697752714157,
            -0.09547697752714157,
            -0.08476231247186661,
            -0.08476231247186661,
            -0.07903534173965454,
            -0.07903534173965454,
            -0.0763164535164833,
            -0.0763164535164833,
            0.2143465280532837,
            0.0,
            0.2163686901330948,
            0.0,
            0.0,
            0.0,
            -4.335720451128143e-17,
            0.0,
            -9.476214184631987e-17,
            0.0,
            4.262625478247037e-17,
            -7.56397642571232e-17,
            -0.09334449470043182,
            0.0,
            0.026570839807391167,
            0.0,
            1.5078107609456685e-16,
            -1.6208158087190289e-16,
            -1.463564803805758e-16,
            0.0,
            0.0,
            -3.1348694671837576e-16,
            -1.435399734082246e-17,
            0.0,
            -1.9893198747021764e-16,
            0.0,
            -0.09278623759746552,
            -2.0932559789373014e-17,
            -0.09344613552093506,
            -2.0650343962343397e-17,
            0.0,
            -2.169402917406483e-17,
            -0.0940978080034256,
            1.758549420904662e-17,
            -0.0724826231598854,
            0.0,
            -0.023566843941807747,
            0.0,
            -0.03018305078148842,
            -2.1623525261734484e-17,
            -0.17308054864406586,
            9.727900760485742e-17,
            -0.15120118856430054,
            -0.04303601756691933,
            4.887112760883336e-17,
            0.0
          ]
        }
      }
    }
  }
}
```

leading to the following error message: 
"cannot implicitly cast def [org.elasticsearch.index.mapper.vectors.DenseVectorScriptDocValues] to java.lang.String"

The query had been working for a while now, and when I started to notice the indexing problem, it started to fail. 
(The query would also fail similarly if I didn't specify "embedding" to be of type dense_vector)

**Comment by ssssarah** [comment]
https://www.elastic.co/guide/en/elasticsearch/painless/7.17/painless-api-reference-score.html  

https://www.elastic.co/guide/en/elasticsearch/painless/8.7/painless-api-reference-score.html

There does seem to be a change in the scripting method signatures, forget about the additional context section (although maybe this problem is also a consequence of the version update 🤔)

**Comment by olivergrabinski** [comment]
From the list of [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.0.html) it does seem like this was change in ES 8.0 (cf. `Vector functions using (query, doc['field']) are no longer supported.`).

For the main issue we will be taking a look into it

**Comment by olivergrabinski** [comment]
@ssssarah An initial look into the issue with @samuel-kerrien suggests that you can work around it by using the legacy view definition (the one without the `pipeline` field). I think in your case you should be able to convert what you have into the legacy format.

And on our end we will be looking into the root cause of this difference to be able to fix it.

**Comment by imsdu** [comment]
With the new definition, there is a change that should have been better documented but using the new elasticsearch views api, you have to explicitly to add one of the defaultLabelPredicates / selectPredicates/ dataConstructQuery pipe:
https://bluebrainnexus.io/docs/delta/api/views/pipes.html
