### ISSUE TITLE
project creation failed with 500

### ISSUE THREAD

**Issue by bilalesi** [BlueBrain/nexus#4015]
when try to create a new project in staging 
1. specify a name 
2. specify the vocab and the base

the project will be created but we got a response as
![Screenshot 2023-07-03 at 11.11.51.png](https://images.zenhubusercontent.com/63ff6f67213b2c97ca732f08/ea29fd08-bc92-4de6-a5bd-f5bd07ad8b98) 500

**Comment by imsdu** [comment]
Closing as the incident in staging due to the storage update has been resolved
