### ISSUE TITLE
As a user, I want clarity in the presentation of the predicate so that I can understand

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#4037]
## Acceptance Criteria
- [ ] hide predicate if path is not selected
- [ ] improve the UI elements for the select menu
   - [ ] Show contains and does not contain in more legible blue fonts
   - [ ] The input element for the value should be bordered and more obvious, with a better placeholder

**Comment by Dinika** [comment]
Done as part of [4023](https://app.zenhub.com/workspaces/blue-brain-nexus-60ace035034cae00105c9307/issues/gh/bluebrain/nexus/4023)
