### ISSUE TITLE
The user can execute a predicate and get the results from the backend

### ISSUE THREAD

**Issue by bilalesi** [BlueBrain/nexus#4083]
The user can select filters (org/project)  and build a predicate 
The predicate will be executed in the backend using the new API endpoint GA ES query 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGRDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d876e32289147b121d0ebfe697e6c07f106f7057/Screenshot%202023-08-28%20at%2012.47.35.png)

**Comment by Dinika** [comment]
NOTE - Right now only the "EXISTS" and "DOES_NOT_EXIST" predicates can run on the backend. [This slack thread](https://bluebrainproject.slack.com/archives/G013PKBUHT2/p1693921688217919) contains details.
