### ISSUE TITLE
JSON viewer - Easier opening of resource in History

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#4088]
## Description
During user test with a brand new user, it wasn't obvious how to navigate into the left/right history of the graph traversal.
The user was driven to click on the label of the resource or in the rectangle and did not realise that the `expand` icon was intended for that. 

possible improvement: remove the icon and make the whole area clickable. As discussed with Bilal this might come at the cost of not being able to copy/paste the resource name from the history, which we agreed might be ok. The icon could also stay as long as the rest of the area is clickable.

This might require a UX discussion with @loris-olivier 

## Acceptance Criteria
- [ ] Relevant area of the history item is clickable to navigate back to this resource

**Comment by loris-olivier** [comment]
I agree with @bilalesi , but if it simplifies it we can have the whole collapsed panel clickable
