### ISSUE TITLE
Improving Fullscreen Toggle Visibility in JSON Viewer

### ISSUE THREAD

**Issue by bilalesi** [BlueBrain/nexus#4089]
## Description
 I want the fullscreen toggle button to have clear and distinguishable states, so I can easily know if I'm in regular mode or fullscreen mode.
**Regular Mode**
![Screenshot 2023-07-21 at 09.52.09.png](https://images.zenhubusercontent.com/63ff6f67213b2c97ca732f08/4de604cd-0766-45a8-ba08-518ed7dd1657)
**FullScreen Mode**
![Screenshot 2023-07-21 at 09.52.23.png](https://images.zenhubusercontent.com/63ff6f67213b2c97ca732f08/c5d46c01-f9c3-4b2e-8603-51d66edc4b8f)
## Acceptance Criteria
- [ ] The fullscreen toggle button should have two visually distinct states to represent regular mode and fullscreen mode clearly.

**Comment by loris-olivier** [comment]
Hello @bilalesi , 
Here is my proposal:
https://www.figma.com/file/QWdVnO3fzUWu32GlFJMsz1/BBP-%3E-Fusion?type=design&node-id=1636-1844&mode=design&t=XbRBbdvjp2iSdupK-4

![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/12f3b37f-eb13-4105-82ae-d88fa969a6d8)
