### ISSUE TITLE
Do not compact `_self`, `_incoming` and `outgoing` links

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#4103]
**Motivation**
The `_self` but the also the links to incoming and outgoing resources are shortened using the project base and the api mappings defined at the project level.
For example, when the prefix of the @id of a  resources matches the project base, the `_self` is shortened as:
`https://bbp.epfl.ch/v1/resources/org/proj/_/[id_suffix]` where `id_suffix` is generally an uuid
For the others, the `_self` remains:
`https://bbp.epfl.ch/v1/resources/org/proj/_/[full_encoded_id]` where `full_encoded_id` is the full id url-encoded

When the project base or the api mappings change, the `_self` can not be shortened anymore and Delta is not able to resolve those former shortened `_self`.

Whenever this happens,  the new `_self` needs to be propagated to the indices and namespaces of the views of the projects indexing metadata (as the `_self` is part of this metadata) but also to update resources that may include the short form of the `_self` (for example, via distributions).

So the idea is not to shorten them anymore so that they remain stable even if the project configuration changes to avoid this burden.

**Acceptance criteria**
1. When fetching a resource, the `_self`, `_incoming` and `outgoing` links are not compacted anymore
2. The schema segment part is always `_`
3. In the different namespaces and indices, those links are not compacted anymore

**Comment by crisely09** [comment]
As you commented on slack, the schema part is missing, that should also be fully expanded in my opinion. That is, no more `_`, instead having the full id of `unconstrained` schema.
