### ISSUE TITLE
Migrate integration tests to use Cats Effect

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#4327]

**Comment by dantb** [comment]
@imsdu I'm doing some of this as part of #4255 - in particular `SupervisorSetup` needs to work with CE and ideally munit  CE

**Comment by imsdu** [comment]
> @imsdu I'm doing some of this as part of #4255 - in particular `SupervisorSetup` needs to work with CE and ideally munit CE

I meant the integration tests living in tests for this one :)
