### ISSUE TITLE
Scheduled Cypress test

### ISSUE THREAD

**Issue by bilalesi** [BlueBrain/nexus#4342]
In order to continuously check the health status of public studios, we can do some e2e testing using cypress, the tests consist of the following tasks:

1. Test the accessibility of each part of the studio (dashboard, workspace)
2. Test the API result format, as we run a `spark-ql` query for each studio, we can run a api-test using cypress.
3. Expose the results of the test 
    - using the  slack API to share it in `nise-team/fusion channel` channel when we have errors (SECRETS must be added to the `github-action` settings).
4. Add scheduled `github-action` to run in a specific time (to determine, may midnight will a good option)

**Comment by danburonline** [comment]
@Dinika Hasn't this been implemented already? https://github.com/BlueBrain/nexus-web/blob/main/.github/workflows/monitor-studios.yml
