### ISSUE TITLE
Improve full text search for default views

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#4350]
**Motivation**
Performing full text search in the Fusion project page does not bring satisfying results due to the way data is indexed. We search only one field, `allFields` - [here](https://github.com/BlueBrain/nexus/blob/master/delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/client/QueryBuilder.scala#L76) in the QueryBuilder. This contains all data so fields that have more weight such as id/name/description gets diluted by everything else.

A simple example of the problem is that passing a resource Id in the search query can produce mixed results, such as other resources linked to it. It should instead return that resource as the top result. The same goes for querying the name of a resource.

In the API this is supported by the `q` parameter on list operations [here](https://bluebrainnexus.io/docs/delta/api/resources-api.html#within-a-project). In Fusion it's in the default resource listing here: https://bbp.epfl.ch/nexus/web/orgs/public/sscx

The code change should be very simple - just modifying the `QueryBuilder`. Most of the work will be experimenting with indexing and querying of elastic search based on different tokenizers / analyzers, such as:
- For iris - https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-uaxurlemail-tokenizer.html
- For natural language fields like description - https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html
- For querying across multiple fields - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html

**Acceptance criteria**
1. Description is indexed as an independent field.
2. The tokenizer/analyzer is changed so as to better index the resource Id, for example.
3. The full text search part of the listing operation (`q` param) is changed to target several fields (already done in Global search)

**Comment by dantb** [comment]
@imsdu might pick up this next, although it might be more suited to someone with domain knowledge... Would it be ok to allow feeding the weightings through an endpoint with a small UI? Otherwise the feedback loop is long and it'll be hard to iterate towards a "better" search

Also who uses the search feature? I.e. who can verify that the results are better

**Comment by imsdu** [comment]
The idea is not to break retro-compatibility and not to introduce any weighting for now but to change the full-text search part of the listing operation (the q param) so that it does not target only the `allFields` fields but also the other fields like the id, the name, the type that are defined in the default mapping.
That will be a first good step as the default TF/IDF algorithm should already help a lot.
For the id/types/_location and the other ones that are Iris/Uris, it would be nice to define a multifield with a subfield for full-text search and have a separate tokenizer that correctly handles Iris (this one would be a good candidate: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-uaxurlemail-tokenizer.html)
For the other ones like `name`, `description` and other than `all_fields`, we could use this one: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html
`all_fields`can stay as it is.

**Comment by imsdu** [comment]
The idea is not to break retro-compatibility and not to introduce any weighting for now but to change the full-text search part of the listing operation (the q param) so that it does not target only the `allFields` fields but also the other fields like the id, the name, the type that are defined in the default mapping.
That will be a first good step as the default TF/IDF algorithm should already help a lot.
For the id/types/_location and the other ones that are Iris/Uris, it would be nice to define a multifield with a subfield for full-text search and have a separate tokenizer that correctly handles Iris (this one would be a good candidate: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-uaxurlemail-tokenizer.html)
For the other ones like `name`, `description` and other than `all_fields`, we could use this one: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html
`all_fields`can stay as it is.

**Comment by imsdu** [comment]
For the query part, this can be a good candidate: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html
With * in the fields part

**Comment by imsdu** [comment]
Also we can remove the nested for the different fieds
