### ISSUE TITLE
Add a copy operation to files

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#4400]
**Motivation**
When moving a project from the private scope to the public scope, it is needed to make a copy (both of the file metadata and the physical file) from one project to another.

So far, they need to download the file to upload it again so it is slow and error prone.

**Acceptance criteria**
1. The selected file to copy can be a latest, revisioned and tagged version of a file
2. The copy is only possible from local to local or remote to remote
3. By default, the file is copied to the default storage of the target project but the user can also provide
4. The same constraints as the other write operations on files (write permission, enough space on the target storage)
5. The file metadata (digest/size/...) is preserved excluding the auditing ones (createdAt, createdBy, ...)
6. Only to be implemented for local and remote storages
7. The file can be optionally tagged like in the create/link operations

**Comment by dantb** [comment]
Hey @crisely09 , this is mostly implemented but wanted to run the API design by you. It basically works like linking - WIP docs are [here](https://github.com/dantb/nexus/blob/copy-files/docs/src/main/paradox/docs/delta/api/files-api.md#create-copy-using-post-or-put). 

Based on our slack convo about your use case I'm wondering if this would push some unnecessary complexity to you. For reference, the ideal solutions were:
"1) either migrate an entire bucket, ob 2) to be able to select a list of resources, either by types or ids."

AFAICT having a bulk operation would be more useful and a single file would just be a special case of that? E.g.
```
POST /v1/files/{org_label}/{project_label}?storage={storageId}&tag={tagName}
{
	"sourceProjectRef": "{sourceOrg}/{sourceProj}",
	"files": [
		{
                        "destinationFileId": "{destFileId}",
			"destinationFilename": "{destinationFilename}",
			"sourceFileId": "{sourceFileId}",
			"sourceTag": "{sourceTagName}",
			"sourceRev": "{sourceRev}"
		}
		...etc
	]
}
```

Also a question on the migrate entire bucket idea - is a bucket a storage? So would this be an operation on a destination storage, passing in a source storage / maybe a path? @imsdu  can correct me if I'm missing something, but this seems simple enough. We would just have to check there's enough space on the destination storage for every incoming file, to avoid a halfway state.

Sorry for the essay, just didn't want to release an endpoint that doesn't quite solve your problem and we'd have to maintain, etc...

**Comment by crisely09** [comment]
First of all, yes, the bulk operation would be the main one and the single-file copying can be a special case.
Now, a bucket is the "full path", the combination of `{org_label}/{proj_label}` in your endpoint, so I am not sure how is the "target" `{org_label}/{proj_label}` is defined, or if the endpoint should not be bucket-related, but a general one that receives a payload with the destinationBucket, sourceBucket?
