### ISSUE TITLE
Make NotFound route return a HTTP 404 code

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#444]
Currently returns a HTTP 200. See https://reacttraining.com/react-router/web/guides/server-rendering/404-401-or-any-other-status to be able to return a 404. Accessing a resource for which we need to login should return a 403 as well.

**Comment by julienmachon** [comment]
This seems to be a deployment issue as it works on certain environment (no on stag or prod)

**Comment by julienmachon** [comment]
We got rid of SSR for the time being as it adds way more technical complexity than benefits. So this is not relevant anymore.
