### ISSUE TITLE
Creation of new organization fails saying it exists already (staging)

### ISSUE THREAD

**Issue by crisely09** [BlueBrain/nexus#4500]
**Description**
I tried to create a new organization *on staging*, called demo, but it said the name already existed, however I searched before and it was not listed.

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion on staging environment:
1. Go to Organizations
2. Click on 'Create Organization'
3. Use `demo` label
4. Click `Save`
5. See error

**Screenshots**
![Screenshot 2023-11-15 at 11 40 10](https://github.com/BlueBrain/nexus/assets/3536415/08a1b702-0518-435a-b149-5cf6d8297076)
![Screenshot 2023-11-15 at 11 40 22](https://github.com/BlueBrain/nexus/assets/3536415/341f4fd6-c0dc-457e-9758-7bb315d7d861)
![Screenshot 2023-11-15 at 11 40 31](https://github.com/BlueBrain/nexus/assets/3536415/febf35bd-313b-48e6-8f01-3c017b401430)

**Comment by olivergrabinski** [comment]
This was an operational error and is now fixed. I was deleting old empty organizations and deprecated this one instead of deleting it. You should now be able to recreate it when you need it.

**Comment by crisely09** [comment]
I confirm, I could create the `demo` organisation, thank you @olivergrabinski !
