### ISSUE TITLE
Using query parameters `prune=true&rev={rev}` should not deprecate an org

### ISSUE THREAD

**Issue by olivergrabinski** [BlueBrain/nexus#4502]
**Motivation**
`pure=true` is supposed to indicate that the org is to be deleted. However, if a rev is present it will hit the deprecation endpoint instead even if `pure=true` is there.

**Comment by dantb** [comment]
@olivergrabinski I think this ordering was intentional to avoid accidentally doing something irreversible. But you're right, it's weird, maybe it's best to reject if both are present?

**Comment by olivergrabinski** [comment]
IMO deprecation is worse than deletion because if I remember correctly you can deprecate an non-empty org, but there is currently no undeprecation. With deletion we have the guarantee that it can only delete an empty org, so at worse the user can just recreate it. For me it's ok to reject if both a present
