### ISSUE TITLE
Expose the view process progress through the API

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#470]
KG indexing is asynchronous in nature and in some circumstances (e.g. loading large amounts of data within a short time window or when the target index is unavailable or slow) the clients don't have any way of understanding when the data is fully indexed.

This ticket proposes an API and implementation details for how this matter can be addressed.

Create a continuous event log replay that keeps track of all the information in the event log:
*   For the entire system:
    *   total event count
    *   event counts by type
    *   last event timestamp
*   For every organization in the system:
    *   total event count
    *   event counts by type
    *   last event timestamp
*   For every project in the system:
    *   total event count
    *   event counts by type
    *   last event timestamp

Since this event log replay would not write the events to an index it will run much faster than the rest of the replays. Replaying the entire log is a fairly expensive operation, it shouldn't be done at every service restart. With that in mind, it should use the ProjectionStorage to record its progress such that it can be resumed on service restart. The progress doesn't need to be written frequently, maybe once every 10,000 events or an hour (whichever comes first).

The ProjectStorage is to be updated to allow storing the collected metrics along with the last known timestamp.

The event log replay needs to be run within a ClusterSingleton actor such that clustered configurations will not execute the replay redundantly.

In order to expose the progress through the API and Grafana, all the event log replay processes in the system (including this additional proposed one) will have be be queryable through a message protocol, increment a Kamon counter for each event and update a Kamon gauge for each event.

The API for querying the progress of a view would be presented as a sub-resource to the view itself:
```
GET /v1/views/{org}/{proj}/{view_id}/statistics
GET /v1/resources/{org}/{proj}/{view_schema}/{view_id}/statistics
GET /v1/resources/{org}/{proj}/_/{view_id}/statistics
200 OK
{
  "@context": "https://bluebrain.github.io/nexus/contexts/view.json",
  // total number of events in the stream
  "totalEvents": 1000000,
  // number of events in the stream that have been considered by the view
  "processedEvents": 999000,
  // number of events in the stream that remain to be considered by the view
  "remainingEvents": 1000,
  // number of events in the stream that have been used to update an index
  "evaluatedEvents": 9000,
  // number of events in the stream that have been discarded (were not evaluated due to filters)
  "discardedEvents": 990000,
  // instant of the last known event in the stream
  "lastEventDateTime": "2018-09-18T10:30:00.801Z",
  // instant of the last processed event in the stream
  "lastProcessedEventDateTime": "2018-09-18T10:00:00.801Z",
  // instant of the last evaluated event in the stream (used to update an index)
  "lastEvaluatedEventDateTime": "2018-09-18T10:00:00.801Z",
  // instant of the last discarded event in the stream (was not evaluated due to filters)
  "lastDiscardedEventDateTime": "2018-09-18T10:00:00.801Z",
  // time interval between the last processed event instant and the last known event instant
  "delay": "00:30:00.0"
}
```

The metrics presented in the statistics are to be computed based on the known global information and the current metrics of the selected view.

**Comment by wwajerowicz** [comment]
I'm not sure all the fields here are actually useful, i.e. `lastDiscardedEventDateTime` and `lastEvaluatedEventDateTime`
I'd also display `delay` in seconds rather than as string. Probably, in this case we should rename it to `delayInSeconds`?

**Comment by julienmachon** [comment]
Are we planning on sending an event when an indexing is triggered as well?

Also, I'm trying to think about an actual use case which erupts a few questions. Basically, when a user is looking at a resource/view, they want to know if:
- it is currently indexing
- when's last time it was indexed
- what the progress or remaining time until is it fully indexed

So i'm thinking that maybe, it would be handy to have a boolean like `indexing: true/false` rather that making the difference between the `totalEvents` and `processedEvents`.

And maybe add the progress as a percentage too? I know we can calculate it, same way we can calculate the `remainingEvents` propose in the current draft.

Other comments, I'm not quite clear about the definition of `evaluatedEvents` and `discardedEvents`.

**Comment by bogdanromanx** [comment]
Depending on how a user views a resource (from the index or from the primary store) it can be consistent or not. It's a client concern to choose the right view.

I think a resource oriented approach to see the indexing progress can be very confusing because a resource can be indexed several times across multiple indices or multiple types of indices. Since we don't index something unless it is required, the concept of the last indexed is a bit misleading. Last indexed where, which revision?

Indexing is continuous by constantly polling the event stream for updates, but you can always look at the view statistics to figure out how many events are left. Remaining == 0 then there are no events to index at the moment.

> Other comments, I'm not quite clear about the definition of evaluatedEvents and discardedEvents.
Evaluated + Discarded = Processed
Processed + Remaining = Total
