### ISSUE TITLE
Align styling with BBP style guide

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#472]
Colors and typography should follow the BlueBrain web style guide, which is slightly different from what we currently use. BBP Search and Nexus Web should be adapted.

**Comment by mdupont** [comment]
@samuel-kerrien let's discuss this one and see where it should apply

**Comment by julienmachon** [comment]
We need to follow the Nexus style guide, not BBP style guide. A reference to EPFL and Blue Brain Project has been added from the info dropdown
