### ISSUE TITLE
Allow reading the external config from S3

### ISSUE THREAD

**Issue by olivergrabinski** [BlueBrain/nexus#4867]
**Motivation**
In order to checkout the delta config together with the deployment, it would be necessary to put the config as an object in S3. Delta needs to be able to read the external config from the provided S3 bucket and key, passed (potentially) as a env variable.

**Comment by imsdu** [comment]
Closing as we took this approach to deploy the config: https://www.honeybadger.io/blog/configure-docker-on-ecs/ 

Linking the aws ticket opened 6 years ago requesting to make things simpler: https://github.com/aws/containers-roadmap/issues/56
