### ISSUE TITLE
Nexus ship: patch projects in aggregated views

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#4875]
**Motivation**
Nexus ship gives the possibility to rename projects.
This should be propagated to the aggregated views for Elasticsearch and Blazegraph

**Acceptance criteria**
1. When an aggregated view points to a view belonging to a project who got renamed, the reference to this view should be updated

**Comment by dantb** [comment]
BG views done in https://github.com/BlueBrain/nexus/pull/4907

Putting this down just now to work on higher priority ship issues
