### ISSUE TITLE
Review the way types are displayed

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#488]
We had feedback from Sean that the way resource types are currently displayed in not very clear or useful for users. Investigate what to do regarding types, get feedback from more users and how do they interact with types.

- Do we need to extract a "main" type and display only one?
- Do we need to display them at all? 
- Are the automated "avatars" confusing?
- Should we fall back to a broader resource type category (only Resolver, View, Schema or Resource)?

**Comment by julienmachon** [comment]
I think only:
- Do we need to display them at all?
- Are the automated "avatars" confusing?

are valid as the other are not actually possible (types are not an ordered list, there is no way to figure out which one is the main one, and we don't have a ontology service to query)
