### ISSUE TITLE
Investigate sentry for error reporting

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#489]
A service like Sentry could provide a good way to get error reporting from the production deployment. Let's determine if it would be worthwhile to use it.

**Comment by julienmachon** [comment]
At the moment, I'm looking at how to self host our own Sentry. It's quite well documented here: https://hub.docker.com/_/sentry/

But I'm also looking at using Promethus, as I'm keen on re-using the tools already deployed and also be in line with the backend teams. My lead so far took me to:
https://github.com/weaveworks/promjs
https://github.com/weaveworks/prom-aggregation-gateway
https://hub.docker.com/r/weaveworks/prom-aggregation-gateway/
https://www.weave.works/blog/weave-cloud-ui-alerts-metrics/

Documentation is very limited however.

**Comment by julienmachon** [comment]
We've decided that tracking and logging errors is more important right now than extracting metrics. Using promethus client side isn't the most documented anyway and the backend team is actually quite keen on using sentry to for their error logs as well. So it's win-win. 

I have deploy Sentry on staging in Open Shift and I will integrate Nexus-web next sprint.
