### ISSUE TITLE
Polish and document S3 link endpoint

### ISSUE THREAD

**Issue by dantb** [BlueBrain/nexus#4914]
This was done quickly to get nexus ship unblocked. Potential improvements:
1. Do we need a creation endpoint where we generate an Id, or is just one with the Id passed fine in this case? Yes
2. Endpoint names could be improved, depending on who will call them. (All changes must be reflected in ship)
3. Better name for `FileAttributesOrigin.External`? => Link
4. Write documentation (if it's needed outside our team, if it's only used by nexus ship then docs are unlikely to be worth writing): Yes for the DKE team

**Comment by imsdu** [comment]
New tickets #4971 and #4974
