### ISSUE TITLE
Studio-related resources are not constrained by any schema

### ISSUE THREAD

**Issue by crisely09** [BlueBrain/nexus#4981]
**Description**
When creating a new studio in a project with the configuration set up so all new events check if resources are constrained by a schema, the creation fails, because all resources from studios are not constrained, they don't have schemas.

**What part of Nexus is affected**
- [x] Fusion
- [x] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
For Fusion:
1. Go to 'dke/kgforge' or any project that has a restriction to only allow resources constrained by a schema (this could be any of your projects)
2. Click on `Studios`
3. Click on `Create Studios`
4. Give a name and save it.

![Screenshot 2024-05-15 at 16 35 53](https://github.com/BlueBrain/nexus/assets/3536415/c5ca8727-a559-435a-ae55-ef1e61dd4036)

**Expected behavior**
A new studio should be created.

**Additional context**
This is needs to be fixed before we change the configuration of the projects to impose schema constraints.

**Comment by imsdu** [comment]
Fixed with #5075
