### ISSUE TITLE
Cannot install tutorial requirements

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/nexus#50]
Hi,

I'd just started the tutorial basic_operations_nexus_v0.ipynb but due to recent changes in pip I can not run the first cell:

`!pip install git+https://github.com/HumanBrainProject/pyxus@v0.1.3 pyyaml requests`

The workaround would be to update the setup.py to something like that in pyxus@v0.1.3

```python
try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements
```

**Comment by MFSY** [comment]
Try to use:
!pip install git+https://github.com/HumanBrainProject/pyxus@v0.5.1#egg=pyxus

You'll get the latest tagged version of pyxus. Please see the [issue](https://github.com/HumanBrainProject/pyxus/issues/27) open in pyxus.
