### ISSUE TITLE
Remove Nexus metadata from payloads during the import

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#5035]
**Motivation**
Some resource still contain Nexus metadata in their original payloads before fields starting with `_` were forbidden.
The import tool can take care of cleaning up those fields

**Acceptance criteria**
1. During an import, all fields starting by `_` at the root level are removed from the original payload before the resource is evaluated

**Comment by shinyhappydan** [comment]
What is an example of a problem that would be avoided by this?

**Comment by imsdu** [comment]
See: https://github.com/BlueBrain/nexus/issues/3935
