### ISSUE TITLE
Error loading data from the server AuthorizationFailed No views are accessible.

### ISSUE THREAD

**Issue by ArseniiOnuchin** [BlueBrain/nexus#5061]
Just after I've logged in, I've seen this messege
How can I fix it? 

Best regards,

**Comment by imsdu** [comment]
Hello,
What is the context of the error ?
Any url to share ?
Thanks

**Comment by ArseniiOnuchin** [comment]
> Hello, What is the context of the error ? Any url to share ? Thanks
![2024-07-09_20-06-27](https://github.com/BlueBrain/nexus/assets/43319548/7ad5209a-409b-4df7-9b59-fe0f808ad5ba)
I've only login by my github and that is all

Thank you

**Comment by imsdu** [comment]
If you click on the project link at the center and then click on the Fusion logo again, does it solve the issue ?

**Comment by ArseniiOnuchin** [comment]
> If you click on the project link at the center and then click on the Fusion logo again, does it solve the issue ?
![2024-07-10_14-28-24](https://github.com/BlueBrain/nexus/assets/43319548/44ea4e69-e3e3-44fe-86da-f7a57e12cb20)
after that site was down totally..

**Comment by imsdu** [comment]
It appears that you did it right when I restarted the app :). 
A project at your name has been created:
![image](https://github.com/BlueBrain/nexus/assets/10530477/edb57cfb-c3b3-4087-864d-a969f80381ea)

**Comment by ArseniiOnuchin** [comment]
> It appears that you did it right when I restarted the app :). A project at your name has been created though: ![image](https://private-user-images.githubusercontent.com/10530477/347384037-edb57cfb-c3b3-4087-864d-a969f80381ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTE5NTcsIm5iZiI6MTcyMDYxMTY1NywicGF0aCI6Ii8xMDUzMDQ3Ny8zNDczODQwMzctZWRiNTdjZmItYzNiMy00MDg3LTg2NGQtYTk2OWY4MDM4MWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDExNDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjllZDA3ZWIxYThjYzk2ZTc3NzA2N2RmNWRlNDliYzFlODRkMDg3NTQ2Mzk3MGQ0MmNmMGM5OWYyMjcyYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gbHfpPomy-dLOQcOE0KVmNpeIrCNwhfn5chGfwwbIdI)

thank you, now it works))

**Comment by imsdu** [comment]
Perfect 👍, I will close the issue then.
