### ISSUE TITLE
Problem creating Nexus Client

### ISSUE THREAD

**Issue by dkeller9** [BlueBrain/nexus#53]
What might be causing an error when running the following code? I am trying to use a token, which is a string of letters and numbers.

```
client = NexusClient(scheme="https", 
                     host="bbp-nexus.epfl.ch", 
                     prefix="staging/v0", 
                     alternative_namespace="https://bbp-nexus.epfl.ch", 
                     auth_client=token)
organization_name = "ngv"
your_organization = client.organizations.read(organization_name)
print(your_organization.data["@id"])

```
gives the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-6f55eeb6dd3b> in <module>()
      5                      auth_client=token)
      6 organization_name = "ngv"
----> 7 your_organization = client.organizations.read(organization_name)
      8 print(your_organization.data["@id"])

C:\Users\dakeller\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyxus\resources\repository.py in read(self, name, revision)
    188 
    189     def read(self, name, revision=None):
--> 190         data = self._read(name, revision)
    191         return Organization(name, data, self.path) if data is not None else None
    192 

C:\Users\dakeller\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyxus\resources\repository.py in _read(self, identifier, revision)
     78             path = "{}/{}?rev={}".format(self.path, identifier, revision)
     79         # try:
---> 80         return self._http_client.get(path)
     81         # except HTTPError as e:
     82         #     if e.response.status_code==401:

C:\Users\dakeller\AppData\Local\Continuum\Anaconda3\lib\site-packages\openid_http_client\http_client.py in get(self, *args, **kwargs)
    139     def get(self, *args, **kwargs):
    140         # return NexusPayload(response.content)?
--> 141         return self._request('get', *args, **kwargs)
    142 
    143     def post(self, *args, **kwargs):

C:\Users\dakeller\AppData\Local\Continuum\Anaconda3\lib\site-packages\openid_http_client\http_client.py in _request(self, method_name, endpoint_url, data, headers, can_retry)
     88         headers = headers or {}
     89         if self.auth_client is not None:
---> 90             headers.update(self.auth_client.get_headers())
     91         req = Request(method_name, full_url, data=data, headers=headers)
     92         prepped_request = self.req_session.prepare_request(req)

AttributeError: 'str' object has no attribute 'get_headers'

**Comment by MFSY** [comment]
Hi,
Thank you for the report. 
pyxus 0.5.1 requires an AccessTokenClient now and not a token string.

**Comment by dkeller9** [comment]
Great, how can I make an AccessTokenClient?

**Comment by MFSY** [comment]
I made a [new version](https://github.com/BlueBrain/nexus/pull/55) of the notebook. Please try agin one it gets merged.
