### ISSUE TITLE
Bulk addition of API mappings

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#531]
**Use case:** Data integrators creating projects often need to add many API mappings

The UI to create projects currently allows to add API mappings one by one. To save time, data integrators would like to be able to paste a whole collection of mappings in one go (JSON format or other)

**Comment by adulbrich** [comment]
@annakristinkaufmann @MFSY would that issue help you? If yes, how do you want it?

**Comment by annakristinkaufmann** [comment]
Hi @adulbrich ! Since we mostly create projects programmatically where we can add the API mappings as "bulk", this is not a priority for me.
