### ISSUE TITLE
Data confidentiality / security: Make the workflow very clear

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#532]
Especially with MINDS data, make sure that only public data will ever be aggregated or made publicly accessible. When users upload private data, it has to remain private and we have to set up the necessary measures to guarantee it.

**Comment by kenjinp** [comment]
please view the readme of the minds-web branch for an explanation. https://github.com/BlueBrain/nexus-search-webapp/tree/minds-web
