### ISSUE TITLE
Schemas details page support

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#538]
Displaying schemas in the metadata card should be a link to their instance in nexus, if one exists

**Comment by julienmachon** [comment]
Nexus web gives you an error when you click on a schema rather than displaying the schema

**Comment by julienmachon** [comment]
This is because nexus web uses the `/resources` endpoint to display content of a resource but schema are not resources and it should use the `/schema` endpoint instead

**Comment by julienmachon** [comment]
This has now been fixed as part of the Refactor.
