### ISSUE TITLE
Resource list does not refresh after creating new resource

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#565]
To reproduce:
- Create a new resource with the modal form in a project
- Save the resource
- Close the modal
- The new resource will not appear in the list, even after a full page refresh or clicking the "refresh list" button, sometimes need to click the "clear filters" button

**Comment by julienmachon** [comment]
We can use the ES endpoint, as we are polling every second or two.

**Comment by julienmachon** [comment]
We should trigger a `poll statistic` after resource creation and refresh the resource list once index is finished and kill the poll.
