### ISSUE TITLE
broken links at https://bbp-nexus.epfl.ch/dev/datamodel/

### ISSUE THREAD

**Issue by colingoldberg** [BlueBrain/nexus#57]
As a new visitor, I have found a number of broken links at https://bbp-nexus.epfl.ch/dev/datamodel/.

One pattern seems to be that content exists at 'staging' where it is missing for 'dev'.
eg.
Not found: http://bbp-nexus.epfl.ch/dev/v0/schemas/bbp/
Found: http://bbp-nexus.epfl.ch/staging/v0/schemas/bbp/

I am trying to understand Nexus - I have no familiarity with neuroscience, but as an independent researcher I believe there is lots of potential here - given that there would be sufficient and clear documentation.

Thanks.

**Comment by MFSY** [comment]
Hi @colingoldberg ,
Thank you for reporting the broken link. I've switched the link from dev to staging as you pointed. We're working on a new SHACL documentation and we will publish it soon.
