### ISSUE TITLE
Nexus-web: ACL view depending on user account

### ISSUE THREAD

**Issue by olinux** [BlueBrain/nexus#570]
We were a little confused by the representation of the "View projects permission"  section: It seems to make a difference if my user was the creator of the organization / project or not: If I create a organization "foo" and a project "bar", I can see the root "foo". If I create the same project in somebody else's organization (e.g. "foobar"), I can see "foobar/bar" to be the root. If I don't have created anything I don't see the root screen at all. 
We would have expected to see the ACLs based on our access groups (if I have the same access group as the creator, I should see the same thing) instead of by user. 

But maybe (most probably), we didn't exactly understand the idea of this screen.

**Comment by adulbrich** [comment]
to be addressed in 1.6 through https://github.com/BlueBrain/nexus/issues/847
