### ISSUE TITLE
Nexus-web: Filter deprecated instances

### ISSUE THREAD

**Issue by olinux** [BlueBrain/nexus#571]
It would be nice to have the (ideally persistent) option to filter deprecated instances on the UI

**Comment by Stafeeva** [comment]
Thank you for your feedback. :)
You can find a button to show deprecated resources only in the Resource list panel.

![Screenshot 2020-01-20 at 11 05 11](https://user-images.githubusercontent.com/23080476/72717746-ee640980-3b74-11ea-8236-f50564c50a2c.png)
