### ISSUE TITLE
Nexus-web: Pagination incosistent between initial load and paginating.

### ISSUE THREAD

**Issue by olinux** [BlueBrain/nexus#573]
When I open an organization which contains 6 projects, I see all 6 but also a second page. If I click on the "next" button, I get the last item. Clicking again on "previous", I get the other 5. 

It therefore seems like pagination is not properly reflected at initial load (although it's nice to have more than 5 items on the screen ;) ).

**Comment by Stafeeva** [comment]
The Project list was updated, so the mentioned issue is not happening anymore.
