### ISSUE TITLE
Creating resolver on Staging: HTTP 405, POST method not allowed

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#577]
When trying to create a resolver on Staging, I got an HTTP 405 error since it tries to use POST, and the *Allow* header only whitelists GET, DELETE and PUT.

**Comment by umbreak** [comment]
Which endpoint are you using?

**Comment by mdupont** [comment]
Found the reason, the URL prefix was the wrong one (`projects/` instead of `resolvers`), resulting in a URL that does not make sense for the API. So there was a legitimate error, although the specific error should have been an HTTP 400
