### ISSUE TITLE
Nexus staging gives "The context resolution did not succeed"

### ISSUE THREAD

**Issue by genric** [BlueBrain/nexus#58]
Hi,
    Using the recent context from neuroshapes master "@context": "https://bbp-nexus.epfl.ch/staging/v0/contexts/neurosciencegraph/core/data/v1.0.2" on queries endpoint gives: {"@context":"https://bbp-nexus.epfl.ch/staging/v0/contexts/nexus/core/error/v0.1.0","code":"IllegalPayload","message":"The context resolution did not succeed"} I would expect that something merged to master as available on staging/prod. Thanks.

**Comment by umbreak** [comment]
Probably because Cassandra was unaccessible at that time. Can you try again, please?

**Comment by genric** [comment]
Yep, now it works. Thanks!
