### ISSUE TITLE
Cannot retrieve any PatchedCells from BBP's staging deployment of Nexus

### ISSUE THREAD

**Issue by genric** [BlueBrain/nexus#59]
Hi,
    When I use the following filter `filter:='{"value": [{"path": "rdf:type", "value": "nsg:PatchedCell", "op": "eq"}], "op": "and"}'` on queries endpoint in staging I get empty result set. I know there should be at least 5 cells there. Could you have a look what is going on there? Thanks.

**Comment by bogdanromanx** [comment]
@annakristinkaufmann could you please confirm this issue?

**Comment by genric** [comment]
Thanks @annakristinkaufmann for help! You can close this now.

**Comment by umbreak** [comment]
For the record, the filter worked and the payload was this:
```json
{
    "@context": "https://bbp-nexus.epfl.ch/staging/v0/contexts/neurosciencegraph/core/data/v1.0.2",
    "filter": {
    "op": "and",
    "value": [
      {
        "path": "rdf:type",
        "op": "eq",
        "value": "nsg:PatchedCell"
      }
    ]
  }  
}
```
