### ISSUE TITLE
Nexus-web: show group and user name in the ACL view

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#596]
Currently, NexusWeb only shows `Group` and `User` and I have to mouse-over the icon so that the tooltip will show me the name of the group or user. I think it would make more sense to print the group or user name beside the icon.

<img width="1177" alt="Screen Shot 2019-04-29 at 15 46 24" src="https://user-images.githubusercontent.com/3679766/56900504-4bbfa400-6a96-11e9-9ea7-5cc927379897.png">

**Comment by julienmachon** [comment]
This has been fixed
