### ISSUE TITLE
Read resources in a project using Resolvers logic

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#602]
Right now we use resolvers to resolve **context** and **owl:imports**.

We could think about providing a mechanism to resolve any arbitrary resource for the fetch API.
## Scenario
resource A (id1) --> org/project1
resource B (id2) --> org/project2

`org/project2` has a cross project resolver pointing to `org/project1`. So basically, through `org/project2` we are able to see everything in project `org/project1`.

## Implementation
We should be able to retrieve id1 through project2 even though it belongs to project1. The regular fetch API should work: `/v1/resources/org/project2/_/id1`

**Note that this should only work for reads. We shouldn't be able to perform any other operation accessing a resource indirectly.**

This feature was requested by @MFSY  and @genric

**Comment by bogdanromanx** [comment]
I think the behaviour needs to be controlled by a query param... otherwise I agree with the rest.

**Comment by umbreak** [comment]
Why to be explicit? That means the client has to know a priori if the resource is in project2 or project1 (and he doesn't care at that stage). Since the resolvers have a way to resolve things in order (based in priority field) I don't see what a query param is useful for.

Besides that, in the response the client will know to which project the resource belongs to, thanks to the `_project` metadata field.

**Comment by bogdanromanx** [comment]
While the resolution is deterministic, I think it's good to be able to control whether you want to include resources from referenced projects or just the local project. The default behaviour could also be controlled by a flag in the project config.

Something we haven't considered, how do we want to handle id collisions (resources with the same id exist in multiple projects)?

**Comment by umbreak** [comment]
The same way we handle collisions now? Sorting the resolvers by priority, the first on finding the resource is the one delivered.

I don't see why this is different than resolving imports or resolving context

**Comment by bogdanromanx** [comment]
I think the difference stems from the fact that getting a resource by its id is part of the "management" API; there could be corner cases like when the InProject resolver has a lower priority than other resolvers and in case of collision you wouldn't be able to access the current project resource.

Also, I think including the `rev=???` or `tag=???` to the query should only target the current project.

**Comment by umbreak** [comment]
We can easily enforce that `InProject` has always the lowest priority and it is handled first. Problem solved.

Why rev or tag should target the current project? From the resolution process that does not make sense either.

**Comment by genric** [comment]
Thanks @umbreak for logging this issue. I think it would be quite useful especially now, when we do a lot of testing. It would allow us to establish default write `org/proj` but still have read access to other project resources(and not pollute them with test data). I hope resource listings would also take into account resources available through the resolvers?

**Comment by umbreak** [comment]
@genric resource listings are another matter, because the resolution process is not related to indexing.

It would be possible to do that, but it isn't as trivial as to do it on the Fetch API. We have to see if we can do something in that respect.

**Comment by genric** [comment]
@umbreak ok, in the time being we probably can do cross project query to get the id's. But fetching by id, I think, should take into account only the available resolvers and no additional flags that you want to do cross project, otherwise we will set them all the time :). If you don't want cross project => delete the resolver, at least this is my take on it now.

**Comment by umbreak** [comment]
We propose this endpoint resolving resources using the resolution logic:

- `/v1/resolvers/{org}/{project}/_/{resourceId}`
- `/v1/resolvers/{org}/{project}/{resolverId}/{resourceId}`

@genric and @MFSY are you fine with that?
