### ISSUE TITLE
V1.1 features in Python SDK

### ISSUE THREAD

**Issue by wwajerowicz** [BlueBrain/nexus#627]
- [ ] Server Sent Events (SSE)
  - [x] KG global events
  - [x] KG project events
  - [x] KG organization events
  - [ ] IAM global events
  - [x] IAM ACLs  events
  - [x] IAM realms events
  - [x] IAM permissions events
  - [ ] admin global events
  - [x] admin organization events
  - [x] admin  project events
- [x] Views
  - [x] Customisable Sparql views
    - [x] Filter by resourceTypes
    - [x] Filter by resourceSchemas
    - [x] Filter by resourceTag
    - [x] Filter by includeMetadata
    - [x] Filter by includeDeprecated
  - [x] Customisable ES views
    - [x] Filter by resourceTypes
    - [x] Filter by includeDeprecated
  - [x] Aggregate ES views
  - [x] Aggregate SPARQL views
  - [x] Statistics
  - [x] View Sparql Query
  - [x] View ES Query
- [x] Storage backends
  - [x] Create/update storages
  - [x] Disk storage
    - [x] Upload files
    - [x] Download files
  - [x] S3 storage
    - [x] Upload files
    - [x] Download files
    - [x] Link files
  - [x] ExternalDiskStorage
    - [x] Upload files
    - [x] Download files / directories
    - [x] Link files / directories
- [x] CrossProject resolvers
- [x] Identities (listing)
- [x] ACLs
- [x] Permissions
  - [x] listing
  - [x] adding
  - [x] subtracting 
- [ ] standardize the SDK API for each resource type
  - [ ] tags
  - [ ] deprecate
  - [ ] update

**Comment by samuel-kerrien** [comment]
Python SDK isn't developed anymore.
