### ISSUE TITLE
Resource not indexed in ES when non ASCII chars in the @id

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#631]
**To reproduce:**

- In Nexus Web, in a project where you have the access rights to do so, try to create a resource with a non-ASCII character in the id (for instance a `é`, let's say we use `café` as the resource id).
- Under the hood it will make a `PUT` request to create a resource, with the id correctly URL encoded (`caf%C3%A9`). **This request claims to succeed with HTTP 201**.
- On the UI side however, it displays an error notification with `An unknown error happened: e is undefined`
- More troubling, the newly created resource *will not not appear in the ElasticSearch view results**, however it is possible to find it **in the Sparql view results**.

**Comment by umbreak** [comment]
I cannot reproduce it. I can create PUT resources as follows:
1. PUT `v1/resources/{org}/{proj}/_/café`
2. POST `v1/resources/{org}/{proj}`
```
{
   "@id": "http://example.com/café",
   ...
}
```

Probably it was due to some previous error on our nexus-rdf library which has already been fixed
