### ISSUE TITLE
Cannot logout from Nexus Web on Linux workstations

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#640]
In Nexus Web, after logging in, click on the logout link. You will appear as logged out, although if you click on "login" again, you'll be automatically logged in again with the previous user, without being asked for username and password.

It means **it's not possible to switch users**, and **it's also a security risk**, as logging out on a machine doesn't prevent someone else to use it after yourself and login with your user without having to enter any password.

**Comment by julienmachon** [comment]
This is because of the way the kerberos token is handled on linux machine. There is nothing we can do about that
