### ISSUE TITLE
Nexus Web file upload does not handle File Too large case (HTTP 413).

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#641]
When uploading a file that is too large, the request will fail with a 413 error code, however Nexus Web does not display any helpful error message or any message at all, it will act as if the upload succeeded.

**Comment by mdupont** [comment]
@kenjinp somewhere between the SDK and the reducer, the call to `createFile()` is not awaited on, and the returned in-progress Promise is considered as a positive proof of success of the operation.

**Comment by julienmachon** [comment]
This has now been fixed as part of the refactor and new SDK implementation.
