### ISSUE TITLE
URL encoding issue when trying to navigate to a resource from Query Lists

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#650]
This issue only occurs in FIREFOX and is created from the fetch resource action in the RESOURCE VIEW (not the URL location change)

**Comment by kenjinp** [comment]
this turns out not to be an encoding issue (Firefox displays all urls as decoded in the devtools)

instead its related to a 500 graph error on the nexus server-side https://github.com/BlueBrain/nexus/issues/652

**Comment by kenjinp** [comment]
proof cuRL: 
```sh
{"@context":"https://bluebrain.github.io/nexus/contexts/error.json","@type":"InternalError","reason":"The system experienced an unexpected error, please try again later."}🌺¸ pirman@bluebrain370 ~ $ curl 'https://sandbox.bluebrainid.ac%2Finstitutes%2Fgrid.1007.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0' -H 'Accept: text/vnd.graphviz' -H 'Accept-Language: en-GB,en;q=0.5' --compressed -H 'Referer: https://sandbox.bluebrainnexus.io/web/demo/kenjinp/resources/http%3A%2F%2Fwww.grid.ac%2Finstitutes%2Fgrid.1007.6'
```

**Comment by umbreak** [comment]
The payload contains some empty objects, like:
```json
{
   "field": ""
}
```
This causes the DOT format of the resource to crash (`Id was empty`). DOT does not support empty objects.
