### ISSUE TITLE
Resources list may crash upon infinite scroll

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#658]
![Screenshot 2019-06-11 at 15 32 28](https://user-images.githubusercontent.com/651209/59276510-b8fe5180-8c5e-11e9-8e6a-d98d8ee5b90a.png)

When scrolling past the end of the list of resources in a project, the list of resources is replaced by the error message `e is undefined`. The interesting bit is that no error is logged in the console nor there are any HTTP request error, so we do not know exactly where the error comes from.

You can reproduce it with the NSG project.

**Comment by mdupont** [comment]
Improvements made in a recent release. The list works, yet there are still flashes of the "e is undefined" message from time to time while additional stuff is loading.

**Comment by julienmachon** [comment]
This is partially fixed but there are still some issues with "flashes" of `e is undefined` showing but less that a seconds sometimes. Also the `load more` action is very jumpy and the loading animation is over the  list of resources, rather that being at the very bottom of the list.

Moving to 1.2 milestone

**Comment by julienmachon** [comment]
This has now been fixed as part of Nexus Web refactor
