### ISSUE TITLE
Allow users to specify dedicated apps for resources 

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#677]
We must give the ability for users to specify (per project to start with) dedicated apps that can be open from Nexus web.

For example, we could associate a `.swc` morphology file with a web app that lives at `http://morphology.viewer` and open a new tab to it with the nexus resource ID as parameter `http://morphology.vewer/:org/:project/:resource` or `http://morphology.viewer?id=http://resource.self.ul`.

The idea is to store the config of associated apps in a resource with the ID `nxv:associatedApplications` and a type `['NexusWebConfig', 'AssociatedApplications']`. The payload could be something like:

```json
{
  "@id": "nxv:associatedApplications",
  "@type": [ "NexusWebConfig", "AssociatedApplications"],
  "associations": [
    {
      "extension": ".swc", 
      "applications": [ { "label": "morpho viewer", "url": "http://morphology.viewer" } ]
    }
  ]
}
```

**Comment by kenjinp** [comment]
this is cool 👌

**Comment by kenjinp** [comment]
I think it's better to specify url params, not force them to use the /:org/:project/:resource path structure

**Comment by julienmachon** [comment]
Yeh, agreed. I think it will also depends on how the external app is handling it

**Comment by mdupont** [comment]
Yep, maybe there could be placeholders for :org, :project and :resource so that the URL structure provided can be made flexible:

```json
{
  "url": "https://morphology.viewer/{org}/{project}?id={resource}"
}
```

Also, what about being able to attach it to a mime-type and no only an extension? One and/or the other could be specified.

**Comment by julienmachon** [comment]
nice feedback guys :kissing_cat:

**Comment by julienmachon** [comment]
I'm thinking of creating a new component in `react-nexus` that would look like:

```tsx
<AssociatedApplications
  orgLabel="my-org"
  projectLabel="my-project"
  resourceId="my:resource"
  noAssociationComponent={<p>no associated apps. Add one +</p>}
  loadingComponent={<p>searching for apps</p>}
>
  {(associations: Association[]) => {
    return <AssociatedAppsComponents associations={associations} />
  }}
</AssociatedApplications>
```

Or with a self URL:

```tsx
<AssociatedApplications
  reosourceSelfUrl="http://nexus.com/my-org/my-project/my:resource"
  noAssociationComponent={<p>no associated apps. Add one +</p>}
  loadingComponent={<p>searching for apps</p>}
>
  {(associations: Association[]) => {
    return <AssociatedAppsComponents associations={associations} />
  }}
</AssociatedApplications>
```

What do you think?

**Comment by mdupont** [comment]
So the component would load the corresponding app for the resource? Would these app need a React component shim?

**Comment by julienmachon** [comment]
no, the component would return the association data defined in this https://github.com/BlueBrain/nexus/issues/677#issue-460809546

So if you want to know if your current resource is associated to an external app, you use this component, and render whatever you fancy in the body (a list of buttons, a description table, etc...)

**Comment by julienmachon** [comment]
The major issue I have right now is the lack of concrete examples. I don't think anyone has made an app that reads data from nexus yet.

I have 2 major assumptions:
 - we want an app to open a particular resource (like a morpho viewer needs an swc)
 - we want an app to open a collection of resources (like the atlas viewer needs an entire project data)

That means that triggering external apps does not happen from the resource level only, but also from the project level.

Furthermore, there are so many different ways this can be done:
- url + query params, like org/project label and resource id, or resource self URL, etc...
- url + encoded JSON config also stored in nexus, like open this morpho with this atlas, and this filter, etc...
- post buffer to external app, so there is no need for authentication
- etc...

based on that, I'll keep this issue open for conversation, but I don't think we're ready to implement yet, et all.

**Comment by julienmachon** [comment]
There is some movement on this front. I think @pgetta is linking to some external apps from their BBP Studio app. 

Maybe he will be to help with the issues mentioned above.

**Comment by kenjinp** [comment]
This will be handled now via the Plugins feature
