### ISSUE TITLE
Use the source endpoint when updating resources using the original payload

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#691]
On nexus web one can modify the payload and click on the `save` button, which will update the resource with the passed payload.

In this case, the metadata fields are also saved. However I would recommend deleting them.

List of metadata fields
- _rev
- _deprecated
- _createdAt
- _updatedAt
- _createdBy
- _updatedBy
- _constrainedBy
- _self
- _project
- _total
- _results
- _maxScore
- _score
- _uuid
- _instant
- _subject
- _resourceId
- _organization
- _projectUuid
- _organizationUuid
- _incoming
- _outgoing
- _filename
- _digest
- _algorithm
- _value
- _bytes
- _mediaType
- _storage

~~In the future we can find better ways to o this. Probably when we have a fetch endpoint for the original source only (without metadata), that would be the one that nexus web should show for editing purposes.~~

**The future became present: Use the source endpoint to fetch the original source. This won't contain the metadata, so there is no problem of including back the metadata in the subsequent request.**

**Comment by umbreak** [comment]
This is outdated, now you should use the `source` endpoint instead, when updating resources

**Comment by julienmachon** [comment]
https://github.com/BlueBrain/nexus/issues/715#issue-476706009
