### ISSUE TITLE
Process to repair tag views (if needed)

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#697]
We need a process to verify that all the tags are correctly written on the `tag_views` table.

If that's not the case, anytime we use `getByTag` we are going to miss some resources.

That should be fixed in the latest version of akka-persistence-cassandra but we should have a way to at least monitor if there is a missing row on the tag_views table.

If that weren't fixed, we would need a healing process. Requesting a resource seems to magically add the necessary rows in the `tag_views` table. However that wouldn't be enough in order for the resource to be indexed. We would need to retrigger indexing, since we might be on a current offset which is further in time than the healed resources' offset.

**Comment by bogdanromanx** [comment]
We have a process to repair from the messages table.
