### ISSUE TITLE
Nexus Python SDK should remove the metadata fields before posting resource to the API

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#698]
A call to create or update a resource through the nexus sdk should remove the following metadata fields:
- _rev
- _deprecated
- _createdAt
- _updatedAt
- _createdBy
- _updatedBy
- _constrainedBy
- _self
- _project
- _total
- _results
- _maxScore
- _score
- _uuid
- _instant
- _subject
- _resourceId
- _organization
- _projectUuid
- _organizationUuid
- _incoming
- _outgoing
- _filename
- _digest
- _algorithm
- _value
- _bytes
- _mediaType
- _storage

**Comment by samuel-kerrien** [comment]
Python SDK isn't developed anymore.
