### ISSUE TITLE
Registering file in nexus with empty filename does work

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#699]
### Expected behavior

When the filename is empty, a `Bad Request` error should be generated.

### Actual Behavior (please include screenshot if possible)

No error is generated

### Steps to reproduce the problem

Running the following call
```
nexus.files.create_link(org_label=ORG, project_label=PROJECT,
            filename="", filepath=gpfs_file,
            media_type='image/jpeg')
```

with a valid ORG/PROJECT and existing `filepath` and with `filename=""`.

### Optional infrastructural data (user, platform, browser, environment, ...)

dev infrastructure

**Comment by alex4200** [comment]
With the current setup, I can upload an empty file. Example location: /gpfs/bbp.cscs.ch/data/project/nexustest/nexus-staging/0636daea-019e-4316-8c47-d93694fe9b83/a/f/1/5/2/8/9/5/empty_file.txt

**Comment by umbreak** [comment]
This is due to the fact that staging is not using the latest tagged version of nexus.
I will deploy the latest and let you know when you can re-test that

**Comment by bogdanromanx** [comment]
@alex4200 please retest this functionality.

**Comment by alex4200** [comment]
Seems to work now, closing ticket
