### ISSUE TITLE
Use incoming and outgoing endpoints from the API

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#714]
Nexus web is doing the Sparql query itself in order to determine the incoming and outgoing links.

v1.1 has support to [list incoming links](https://bluebrainnexus.io/docs/api/1.1/kg/kg-resources-api.html#list-incoming-links) and [list outgoing links](https://bluebrainnexus.io/docs/api/1.1/kg/kg-resources-api.html#list-outgoing-links).
You should be using this, since it also provides the intermediate properties to the final object

**Comment by Stafeeva** [comment]
This was fixes during the Refactor.
