### ISSUE TITLE
Detect proper Content-Type when linking

### ISSUE THREAD

**Issue by hygt** [BlueBrain/nexus#723]
The user provided media type is now optional when linking BlueBrain/nexus-kg#711 and we don't have a detection mechanism on our end.

This can be an issue when fetching a folder: a tar archive is streamed on the fly, while the Content-Type header either comes from the specified media type (probably irrelevant here), or defaults to `application/octet-stream`.

We could a detected content type to the file attributes in the response, when we initiate a linking operation on the nexus-storage side.

**Comment by umbreak** [comment]
This is already fixed. Now folders will always have `application/x-tar` content-type
