### ISSUE TITLE
Show error message when a SPARQL query is invalid

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#732]
Once the backend exposes the error message in a better fashion: https://github.com/BlueBrain/nexus/issues/731 please expose this message when a query execution fails.

**Comment by julienmachon** [comment]
This is what we are displaying now:

![Screenshot from 2019-11-26 11-30-21](https://user-images.githubusercontent.com/4364154/69621890-33216780-1040-11ea-88ba-15092a31e508.png)

Brutal... but more explicit

**Comment by samuel-kerrien** [comment]
Very useful already. Has there been a discussion with backend in order to expose a more concise error message?

**Comment by julienmachon** [comment]
I've raised it here https://github.com/BlueBrain/nexus/issues/914

We can pick that up once it's implemented. 

I'm closing this one for now
