### ISSUE TITLE
Prevent ability to run Denial of Service on SPARQL view (BlazeGraph)

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#734]
Currently (v1.1), running a long sparql query will be terminate with a Gateway Timeout after 15s. However, the query is still running on the underlying BlazeGraph server. If many of these queries happen to be launched, we have observed the CPU to max out and the server to become unresponsive.

Recommendations:
- make the gateway timeout longer by default (maybe @MFSY can recommend a better default?)
- ensure that when the gateway times out, the blazegraph query gets terminated (the BlazeGraph UI allows it, there must be an API call)

**Comment by adulbrich** [comment]
timeout is implemented
