### ISSUE TITLE
Incoming and outgoing results are inconsistent

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#735]
The results for `/incoming` seem to return results outside the scope of the immediate resource pointing to the selected one. Example:
`f2ae1d27-25e7-4e96-bdff-9c3cf8a93430` is in `190f32ae-2090-4d20-86dc-342f28da0a90` incoming links
but
`190f32ae-2090-4d20-86dc-342f28da0a90` is not in `f2ae1d27-25e7-4e96-bdff-9c3cf8a93430` outgoing links

Investigation shows that the relationship is:
```
f2ae1d27-25e7-4e96-bdff-9c3cf8a93430
---generated--->
   de4af788-a6cc-4b24-b64c-47246cffcc43
   ---distribution/contentUrl--->
      190f32ae-2090-4d20-86dc-342f28da0a90
```

**Comment by pafonta** [comment]
Thanks for having opened an issue for it.

**Comment by bogdanromanx** [comment]
Additionally, the `_self` in the result is incorrectly formatted.

**Comment by umbreak** [comment]
The problem with the `_self` has been fixed in dev and staging. It was due to encoding problem in the nexus-rdf library.

The query for incoming as it is now can jump to more resources than the targeted one. That's a bug and it is going to be addressed.

**Comment by pafonta** [comment]
Thanks for troubleshooting it.
