### ISSUE TITLE
Change the schema a resource is constrained by

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#737]
Right now, when a resource is created, we have to specify its schema:
`POST /v1/resources/{org_label}/{project_label}/{schema_id}`

What usually happens is that we start creating unconstrained data using the unconstrained schema `_` and once we're happy with it we create a matching schema **but** there is no way to change what schema the resource is validated against.

I know the trick would be to create an empty schema first and then create our resources using this schema (as it can be updated later) but it forces us to make premature decisions such as how many schema we will have, which resource is validated by which schema, etc... (or everything is validated by the same giant schema).

It would be very cool if we could just say `Resource X is no constrained by Schema Y`

**Comment by umbreak** [comment]
This is not something we are going to support anytime soon. It is the way how things are modeles on the `Event`. 

The work around:
1. Create a schema which always passes
2. Create your data against that "empty" schema
3. Iterate over your schema

**Comment by imsdu** [comment]
Fixed in #4387
