### ISSUE TITLE
ListItem or List component doesn't have a key

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#757]
![Screenshot 2019-10-17 at 15 30 46](https://user-images.githubusercontent.com/5485824/67013355-44975b80-f0f3-11e9-80ff-4ab7b1f7b958.png)

**Comment by stevenwally** [comment]
Hello! Can I take this bug?

**Comment by julienmachon** [comment]
Hi @stevenwally . This issue has been fixed already. But thanks for your interest and feel free to look at other issues!

**Comment by Stafeeva** [comment]
Fixed by BlueBrain/nexus-web#318

**Comment by stevenwally** [comment]
Thanks @julienmachon !
