### ISSUE TITLE
nexus.Resource.get has no option to return jsonLD metadata if it's a file

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#760]
If you try to fetch a resource that happens to be a file, it will return the actual file directly instead of the metadata. This would be fine, but there's no way to force the method to return the jsonld metadata instead. workaround: use httpGET with custom headers.

**Comment by julienmachon** [comment]
Actually, if you look at the doc: https://bluebrainnexus.io/docs/api/current/kg/kg-resources-api.html#fetch-a-resource it supports multiple formats.

So I guess the solution here could be to do something similar to what we've done for `File` https://github.com/BlueBrain/nexus-js/blob/master/packages/nexus-sdk/src/File/index.ts#L25-L47 and add `as` option here https://github.com/BlueBrain/nexus-js/blob/master/packages/nexus-sdk/src/Resource/types.ts#L49
