### ISSUE TITLE
Schema should link to the nexus resource

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#762]
in the resource details page, the schema for that resource is listed. It should link to the corresponding nexus resource if it exists in the system. 

Maybe it should be similar to the internal/external link in the links pages?

**Comment by julienmachon** [comment]
![Screenshot 2019-11-13 at 10 24 12](https://user-images.githubusercontent.com/4364154/68750202-c8b00680-05ff-11ea-9a2d-f9d3514233bb.png)

We might to (in order):
- fetch the project directly
- use resolvers
- expand the ID and follow
