### ISSUE TITLE
Implement `/source` endpoint

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#764]
You can now get the original payload of a resource: https://bluebrainnexus.io/docs/api/current/kg/kg-resources-api.html#fetch-a-resource-original-payload

This needs to be implemented into the sdk

**Comment by Stafeeva** [comment]
🔨 Implementation suggestions: 
- create a 'resource.getSource(orgLabel, projectLabel, resourceId, ?schemaId, ?options)' function in sdk;
- options will be only 'rev' and '?tag', so we need to create a new GetResourceSourceOptions type.

**Comment by julienmachon** [comment]
That sounds good to me. @dhaneshnm , @kenjinp waht do you think?
