### ISSUE TITLE
Remove `ts-ignore` in sparlview

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#765]
Depends on https://github.com/BlueBrain/nexus/issues/753

Once the issue above is fixed, get ride of the `@ts-ignore` rule
https://github.com/BlueBrain/nexus-web/blob/master/src/shared/views/SparqlQueryView.tsx#L32-L34

**Comment by Stafeeva** [comment]
Implemented by BlueBrain/nexus-web#320
