### ISSUE TITLE
update response type in Sparql Query form component

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#766]
depends on https://github.com/BlueBrain/nexus/issues/755

Once the issue above is fixed, update response type https://github.com/BlueBrain/nexus-web/blob/master/src/shared/components/ViewForm/SparqlQueryForm.tsx#L27-L30

**Comment by Stafeeva** [comment]
Do we just import this type (SparqlViewQueryResponse) from nexus-sdk?

**Comment by julienmachon** [comment]
Yes, I think so. 

What is going to be a little tricky here I guess is that the `SparqlViewQueryResponse` type can be 2 very different things depending on whether it's a `SelectQueryResponse` or a `AskQueryResponse`.

So you might have to change the code too
