### ISSUE TITLE
Project permissions page not working as expected

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#769]
The following urls do not work as expected: https://nexus.example.com/{org}/{project}/_settings/acls

Under the hood you are performing a request to the following API endpoint:
https://nexus.example.com/v1/acls/{org}/{project} which will return the ACLs on that path ({org}/{project}). To retrieve the *effective* ACLs you need to add the query parameter: `ancestors=true`

**Comment by julienmachon** [comment]
Good spot. Looks like the `ancestor: true` was lost during the refactor...
