### ISSUE TITLE
"header implementation" for all resources subtypes

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#772]
All the resources subtypes (Schemas, Resolvers, Views, Storages, Files, Archives) actually supports the [following format](https://bluebrainnexus.io/docs/api/current/kg/kg-resources-api.html#fetch-a-resource): `ld+json`, `n-triples`, `vnd.graphviz`.

[Right now](https://github.com/BlueBrain/nexus-js/blob/master/packages/nexus-sdk/src/Resource/types.ts#L53) in the SDK, only [Resources](https://github.com/BlueBrain/nexus-js/blob/master/packages/nexus-sdk/src/Resource/index.ts#L20-L26) support this. 

It should be implemented for all the Resources subtypes

**Comment by Stafeeva** [comment]
Suggestions

We could have a function in 'utils' file that takes 'as' from the options provided, and constructs headers, for example,
```
export function buildHeader(as: string = 'json') {
  let acceptHeader = 'application/ld+json';

  if (as === 'vnd.graph-viz') {
    acceptHeader = 'text/vnd.graphviz';
  }

  if (as === 'n-triples') {
    acceptHeader = 'application/n-triples';
  }

  return acceptHeader;
}
```

So we could use in httpGet request, something like
```
return httpGet({
        headers: { Accept: buildHeader(as) },
        path: `${
          context.uri
        }/resources/${orgLabel}/${projectLabel}/${DEFAULT_SCHEMA_ID}/${resourceId}${buildQueryParams(
          opts,
        )}`,
      });
```
and use it everywhere we need.

🙀

**Comment by julienmachon** [comment]
That's exactly what I was thinking :+1:
