### ISSUE TITLE
Display nexus services versions

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#773]
There is a new endpoint that displays the version of all Nexus services: https://staging.nexus.ocp.bbp.epfl.ch/version

That would be nice to display this information in the info section of Nexus Web:
![Screenshot from 2019-10-25 09-07-49](https://user-images.githubusercontent.com/4364154/67550551-0f989380-f707-11e9-870c-4a6d305d17aa.png)

**Comment by julienmachon** [comment]
This one might nit be as straight forward as it seems as the endpoint doesn't have the version `/v1`.

So I'm not sure if that should be added on the SDK or simply diplayed on the web interface with a basic `fetch` request...

**Comment by samuel-kerrien** [comment]
My 2 pence, it would be much easier/simpler to have a dedicated URL in the webapp just to hand out the version number than asking clients to parse HTML to extract it.
