### ISSUE TITLE
Display Resource metadata in Editor

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#779]
Do we need to display the content of `Resource.get` in the editor so we can see the metadata?

Right now we have this:
![Screenshot from 2019-10-29 08-41-37](https://user-images.githubusercontent.com/4364154/67746970-f3a73180-fa27-11e9-94a7-0daa3d907c34.png)

Before we had that:
![Screenshot from 2019-10-29 08-41-30](https://user-images.githubusercontent.com/4364154/67746989-015cb700-fa28-11e9-95d3-a7151dd7aa18.png)

We should potentially only use the `Resource.getSource` method to compute the diff if the user update the resource and make sure we don't sent Nexus metadata as part of our payload.

**Comment by bogdanromanx** [comment]
A toggle to switch between the source and Nexus metadata would be very useful, especially if some keys are not recognized as iris because of lacking context definitions.

**Comment by umbreak** [comment]
I agree with bogdan.

For the editing of the payload, a way to go is to have a button to edit the json. When clicking on edit, the payload changes to the payload retrieved from the source.
