### ISSUE TITLE
Display deprecated view after Deprecating Resource

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#782]
If the user navigates the tabs, the `rev` or the resource gets appended in the URL which means that after a deprecate, the view refreshes to that version, and not the latest (the deprecated one).

![deprecate](https://user-images.githubusercontent.com/4364154/67748028-50a3e700-fa2a-11e9-956c-2d20e6c3d012.gif)

**Comment by Stafeeva** [comment]
Here:

https://github.com/BlueBrain/nexus-web/blob/master/src/shared/containers/ResourceActions.tsx#L40

after we 'deprecate', instead of
```
location && location.reload();
```
we should push to a new url with the next revision like:
```
dispatch(
  push(`/${orgLabel}/${projectLabel}/resources/${resourceId}${_rev ? `?rev=${_rev}` : ''}`)
);
```
