### ISSUE TITLE
Possible memory leak during digest computation

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#790]
Keeping KG idle after ingesting large amounts of data results in memory leak while digests are being "computed"; none of the events are actual file events. The issue can be caused by monitoring as Kamon was enabled during the test. See screenshot...

Jaeger was configured but not enabled.

![Screenshot 2019-10-31 at 09 18 37](https://user-images.githubusercontent.com/5427480/67930316-c8574a80-fbbf-11e9-8e53-515f01ad1e74.png)

**Comment by umbreak** [comment]
This is probably introduced somewhere on the `TagProjection` code and not directly related to digest computation, since the pattern match you added on the event does not trigger any digest computation
