### ISSUE TITLE
Editing projects prefix mappings errors

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#792]
when you are on nexus web on the page
https://example.com/{org} you see a list of projects for a selected organization.

_Edit -> Add API mapping (you fill a prefix and a uri) -> Save _

Then you click again in Edit, and the prefix mapping you already added is gone.

What's more, if you try to add a new or the same prefix mapping and click save again, that will output an error.

**Comment by julienmachon** [comment]
Looks like we don't refresh after the update, so we have the previous state after adding the prefix mapping. That's why we get an error if we try to add it again without refreshing the page.
