### ISSUE TITLE
Remove `make public`

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#794]
In the "edit project" form, we need to remove the "make public" button

![Screenshot from 2019-11-01 10-36-46](https://user-images.githubusercontent.com/4364154/68016027-e42c2080-fc93-11e9-9391-e9e8e4020e66.png)

**Comment by Stafeeva** [comment]
Changes:

![Screenshot 2019-11-06 at 09 02 13](https://user-images.githubusercontent.com/23080476/68279664-33979580-0074-11ea-90fb-0018e2176442.png)
