### ISSUE TITLE
Graph Navigation & Visualization Improvements

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#797]
The main feedback we got was about the lack of visibility in terms of the shape of the data.

Engineers spend a great deal of time shaping their data in order to get the most out of the knowledge graph but all they get visually is a flat structure with  only incoming and outgoing link navigation.

They want to be able to see their linked data as a graph and be able to navigate it.

This will help Data Knowledge engineers and developers who produce data to have a great visual feedback tool.

It will also help the developers who are consuming this data to understand the data faster.

Finally, this can also be a useful tool for the "curious, non-technical" users, such as scientists, as the visual navigation of a graph is something that can be very intuitive.

**Comment by samuel-kerrien** [comment]
I have some ideas on the matter and would love to engage into a discussion on the topic.

**Comment by umbreak** [comment]
Definitely the data explorability can improve:
- Browsing the resources directly form the Json-LD content. If a field on the Json-LD document is an id and we know it is an outgoing link, we should be able to make it clickable in the Json-LD display.
- Graph visualization where the current resource and its relationships gets represented (outgoing links). When clicking on the outgoing nodes, the outgoing of the outgoing nodes gets added to the graph visualization. In this way, one can navigate and visually see a whole graph pattern. This is how is done on the Neo4j demos.

**Comment by kenjinp** [comment]
Graph Vis: Should be centered on a single resource, with incoming and outgoing links to other resources arrayed around it. By clicking on the surrounding nodes you'll be continuously adding to the graph the incoming and outgoing links of that node, building a continuous chain of relationships. 

I think this view might fit into the ProjectView (the project landing page), next to a searchable list of resources (instead of a whole board of multiple lists). If you click on a resource, the graph will update to center on that resource. Right clicking or some other method will lead to the resource details page.

**Comment by kenjinp** [comment]
Data Schema Graph Viewer - some dynamically generated UML-like diagram that shows the relationships of the data in the project by '@type' as it stands, using SPARQL, that will aggregate the data to show that, for example, all `Morphologies` point to a `Subject`, and those entities contain have properties A, B, and C. 

![Screenshot 2019-11-06 at 15 18 32](https://user-images.githubusercontent.com/5485824/68306039-0e714a00-00a9-11ea-8460-1e584a260d24.png)

**Comment by kenjinp** [comment]
The most often cited use case and frustration seems to be, whilst inside a resource view, the user has to keep the links in their head, because clicking through them resets the page and the previous resource's contents.

 It would solve their frustration if instead while clicking through the previous link contents were saved and they can open up whole lines of prov from this view
