### ISSUE TITLE
Statistics: Data Schema Graph Viewer

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#821]
Example: https://kg.ebrains.eu/statistics/

Part of #851 

AS A technical user
I WANT TO be able to display my resources types in a graph
SO I CAN see how my data types are shaped visually

------

- [ ] story #842 
- [ ] story #843
- [ ] story #844
- [ ] story #845

**Comment by adulbrich** [comment]
@samuel-kerrien ask HBP some information about their implementation of the statistics graph
