### ISSUE TITLE
Sparql

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#824]
Sparql is used a lot by the Data Knowledge engineers.

AS A technical user
I WANT TO be able to run SPARQL queries
SO I CAN search and extract data out of the knowledge graph

------

-  [ ] story #923 
-  [x] epic #838 
-  [x] epic #839
-  [ ] epic #840
-  [ ] epic #841

**Comment by akuckartz** [comment]
How was this resolved?
