### ISSUE TITLE
Navigate to other resources in the graph

### ISSUE THREAD

**Issue by Stafeeva** [BlueBrain/nexus#829]
Part of #820 

AS A technical user
I WANT TO be able to navigate to a resource from the graph view
SO THAT I CAN see its details

GIVEN there are links represented in a resource's graph view
WHEN I hover over that resource's label
THEN I will see a resourceCard popover; and
WHEN I click on that resource's label
THEN it will go to said resource

**Comment by kenjinp** [comment]
Changed Acceptance Criteria: 

GIVEN there are links represented in a resource's graph view
WHEN I interact with a resource node 
THEN I can go to said resource's resource view page
