### ISSUE TITLE
Add the possibility to remove deprecation flag from a resource

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#83]
From nexus-kg created by [umbreak](https://github.com/umbreak) : BlueBrain/nexus-kg#519  

Right now, once a resource is deprecated is not possible to un-deprecate it.

This feature has been requested several times (even though not formally, because I cannot find any issue where to link it).

- Is it for all resources incl. projects etc.? Yes, can be applied to all resources, even Delta-specific resources.
- Do we need a special ACL for this? If you can deprecate, you can un-deprecate. No additional ACLs.

**Comment by adulbrich** [comment]
@MFSY @annakristinkaufmann do you have any thoughts on the matter?

**Comment by MFSY** [comment]
Hi @adulbrich ,

I agree with @umbreak proposal. Nice feature to have.

**Comment by annakristinkaufmann** [comment]
Hi @adulbrich ! I agree with @MFSY.

**Comment by imsdu** [comment]
Fixed in #4401
