### ISSUE TITLE
Github pages contexts and schemas not resolved properly by RDF/JSONLD tools

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#84]
From nexus-kg created by [umbreak](https://github.com/umbreak) : BlueBrain/nexus-kg#502  

[Playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fbluebrain.github.io%2Fnexus%2Fcontexts%2Fresource%22%2C%22%40type%22%3A%22nxv%3APerson%22%2C%22_rev%22%3A3%7D) and Jena won't resolve correctly the contexts and schemas in the way they are being redirected from GitHub pages.
https://bluebrain.github.io/nexus/contexts/resource issues a 301 redirect to
https://bluebrain.github.io/nexus/contexts/resource/

Changing the uris to
- https://bluebrain.github.io/nexus/contexts/resource/
- https://bluebrain.github.io/nexus/contexts/resoure.json

would resolve the issue. But I don't like it. Let's see what else we can do...

**Comment by MFSY** [comment]
Hi,

This uri https://bluebrain.github.io/nexus/contexts/resoure.json looks great.

schema.org is doing the same with http://schema.org/docs/jsonldcontext.json

Now schema.org offers also access to its json-ld context via content negotiation on schema.org.
