### ISSUE TITLE
Manage ACLs

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#847]
AS AN administrator
I WANT TO change permissions
SO I CAN control who had access to what on the platform

**Comment by julienmachon** [comment]
We need to take this into account #481 (comment)

**Comment by adulbrich** [comment]
to be addressed in nexus fusion improvements for managing the instance

**Comment by adulbrich** [comment]
related to https://github.com/BlueBrain/nexus/issues/1412

**Comment by samuel-kerrien** [comment]
More recent/detailed ticket: #3920
