### ISSUE TITLE
Allow references by tag/revision (for immutability support)

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#85]
From nexus-kg created by [umbreak](https://github.com/umbreak) : BlueBrain/nexus-kg#501  

References happen in the following cases:

1. Resource referencing another resource. E.g.: `"hasProtocol": {"@id": "other/resource/id"}` 
2. Schema reference using `owl:imports`. E.g.: `"imports": ["other/schema/id"]`
3. Context reference on a resource. E.g.: `"@context": "other/context/id"`

It would be possible to do it using resource with the query params `?tag={tag}` or if `?rev={rev}`.
That would work without any problem for the cases 2 and 3. However if we change the value of the `@id` on the case 1, that does not make sense from the triple store perspective.

We have to find a way to resolve this linking using some special key. For example:
```json
{
   "hasProtocol": {
      "@id":  "other/resource/id",
      "_tagged" : "{tag}"
   }
}
```

Maybe there is a better way to do it from the data part. Thoughts @MFSY @bogdanromanx ?

**Comment by adulbrich** [comment]
Context and schema resolution takes revisions and tags into consideration. The vocabulary is a client-side concern.
