### ISSUE TITLE
Return resource `source` as part of the `Resource.list` payload

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#857]
if you provide a name in the payload it should show that instead of just the last path of the `_self` url or `@id`

**Comment by kenjinp** [comment]
Also in the Resource Link component

**Comment by julienmachon** [comment]
This isn't an easy task as you would have to call `Resource.get` for each listed resources.

Options are:
- backend to implement this on the API level
- change logic and use ES view instead

**Comment by julienmachon** [comment]
@umbreak to look at option 1

**Comment by julienmachon** [comment]
blocks #913

**Comment by bogdanromanx** [comment]
@kenjinp is this ticket still relevant?

**Comment by kenjinp** [comment]
While we don't get the `original_source` in the payload, we do get the `label` now, which covers our use case. We can close this!
