### ISSUE TITLE
Create a resource with Empty ID

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#860]
Behaves really weird (to be investigated)

On the UI side, if you do:

![Screenshot 2019-11-13 at 10 38 20](https://user-images.githubusercontent.com/4364154/68751386-c6e74280-0601-11ea-9284-e233b3d41c78.png)

![Screenshot 2019-11-13 at 10 37 57](https://user-images.githubusercontent.com/4364154/68751352-bafb8080-0601-11ea-8134-27c6450a0b78.png)

KG response:
![Screenshot 2019-11-13 at 10 39 43](https://user-images.githubusercontent.com/4364154/68751498-f4cc8700-0601-11ea-9645-0c6d6e8f277a.png)

**Comment by umbreak** [comment]
This is a Backend error. We should prevent that from the API.

From your side, you should simply handle errors accordingly.

**Comment by julienmachon** [comment]
:tada: :taco:
