### ISSUE TITLE
How to use elasticsearch views for Studio?

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#861]
AS A technical user
I WANT TO document the use of composite views
SO I CAN configure a studio

**Comment by kenjinp** [comment]
## Starting Assumptions:

We still want to keep views separately from dashboard (data queries) for the possibility to re-use them against other `Views` of the same `@type`.

## Changes to Dashboards

Have two different types

```@type: [“StudioDashboard”, “ElasticSearchViewStudioDashboard” ]```

And

```@type: [“StudioDashboard”, “SparqlViewStudioDashboard”]```

### `ElasticSearchViewStudioDashboard` Example 

```json
{
	"@context": "https://bluebrainnexus.io/studio/context",
	"@type": "StudioDashboard",
	"dataQuery": {
		"query": {
			"bool": {
				"must": [{
					"match": {
						"@type": "ReconstructedNeuron"
					}
				}],
				"filter": [{
					"range": {
						"_createdAt": {
							"gte": "2020-01-01"
						}
					}
				}]
			}
		}
	},
	"label": "Pagination Example",
	"plugins": []
}
```
  
## Workspace Changes

the shape should be no different, however the UI must invalidate dashboard/view pairings that don’t match in types.

## Components

### DashboardResultsContainer

should refactor to have two possible query functions based on @type of inputed dashboard, which should parse the query and format the result in a common way. 


## Ways this can break:

- If view / dashboard pairing is not compatible, then the queries will be invalid and lead to invalid request
- If the elastic search view mapping is not compatible with the dataQuery inside the ElasticSearchViewStudioDashboard, it will fail
