### ISSUE TITLE
Visually indicate whether a node can be expanded

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#870]
Part of #820

AS A technical user 
I WANT TO see specially indicated nodes as expandable
SO I CAN tell which ones are navigable

GIVEN that some nodes are expandable themselves (themselves have outgoing links)
WHEN I click on them
THEN they should change visually from an unexpanded to an expanded visual cue

Navigating through the graph is hard to use if you don't know a node can be expanded or not. There should be a visual way to indicate a node can be expanded, and a way to indicate if a node has already been expanded or not. 

[the JSON-LD playground](https://json-ld.org/playground/) achieves this very cleverly. 
There, expandable nodes are larger than non-expandable nodes. Also, expanded nodes are hollow with a border, whereas non-expanded nodes are solid, giving clear visual feedback as to where the user can go. 

![Screenshot 2019-11-13 at 14 15 17](https://user-images.githubusercontent.com/5485824/68766928-176d9880-0620-11ea-8025-64c279f478c5.png)

**Comment by umbreak** [comment]
I think this tree representation, from left to right is also a good approach. If we can achieve something similar in terms of grid display, would be great

**Comment by kenjinp** [comment]
As you saw yesterday @umbreak , the 3rd party layouts are all top-down for some reason with this one. I'll put off trying to rotate the nodes with math until we get feedback from more users, as for now it's placed as another issue https://github.com/BlueBrain/nexus/issues/866
