### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by baixiaotian63648995** [BlueBrain/nexus#875]
Hello,
When I copy the token and run the cammand `nexus auth set-token $TOKEN && nexus profiles list`
it didn't work and come out `Provided tokens could not be decoded. Please provide a valid tokens.`,
and I don't know what's wrong.

**Comment by samuel-kerrien** [comment]
The steps to authenticate in the CLI are as follow:

in your terminal, type `nexus auth web`
that will open Nexus Web, you will login with your GitHub account and enter the application. There, click on the `Copy token` button on the top right. That will copy the token in the clipboard.

If you want to see what is encoded in this token, you can go to this website: `https://jwt.io/` and paste your token into the `ENCODED` field, your decoded token will show on the right hand side.

Now let's add your token to the CLI, you can type: 
`export TOKEN="<content of your clipboard>"`

then
`nexus auth set-token $TOKEN`

if you want to check how long your token is valid for, you can type:
`nexus profiles list`

this will show your selected profile and display the expiry time of your token.

I hope this helps.
