### ISSUE TITLE
Enable downloading in different formats

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#900]
Have the ability to download resources in all the formats provided via the API, maybe by a dropdown, with a default to JSON (if a resource) or binary (if a file).

**Comment by umbreak** [comment]
Is this feature for the archives API?

**Comment by dhaneshnm** [comment]
@umbreak  No, this is not for the archive.  This is an implementation of the resource fetch (https://bluebrainnexus.io/docs/api/current/kg/kg-resources-api.html#fetch-a-resource).
