### ISSUE TITLE
Studio: Custom components #3

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#910]
Using **iframes**

- documentation
- prototype
- pros/cons

**Comment by kenjinp** [comment]
# IFRAMES! 🖼

## PRO
- Real-time configurable plugin deliver
- Security guarantees from iframe API whitelisting
- 3rd party hosting and implementation is all up to the plugin developer, less implementation details for us
- Does not need to include any custom component code into the build itself, or to the source code of nexus-web
- Plugin developers can create custom elements and test them out without building anything, just by changing their plugin configurations

## CON
- Needs to be wholly hosted, self-contained application
- Not responsive!
 (changes in parent dimension at the DOM level, like changers height and width, needs to be sent to iframe, and the 3rd party developer needs to handle that and make sure events are captured and resized
- If we want to enforce certain guidelines, like prioritizing responsive behavior, we need to police carefully each 3rd party plugin for compliance
- Slow  
    - iframe needs to load an entire application stack, including css and js, which by using other methods might already be included in nexus web and thus avoidable
    - Dom repainting with an iframe can be slow
    - Posting messages to and from iframe can be slow
- No SEO! (different domains will not be indexed)

**Comment by julienmachon** [comment]
This has been decided not to be a good idea. at all.
