### ISSUE TITLE
Resource List Items Should Show Resource Name if Available

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#913]
Once KG return the resource payload in the listing, we will be able to display the `name` or `label` field if present.

Blocked by #857

**Comment by kenjinp** [comment]
This issue has been resolved by the backend team. The frontend code already takes the labels into account and no further action is needed from our side 👍  

<img width="411" alt="Screenshot 2020-08-03 at 13 54 24" src="https://user-images.githubusercontent.com/5485824/89180259-b44ada00-d591-11ea-9b13-c1daaa05f72b.png">
