### ISSUE TITLE
Composite view projections automatic restart

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#919]
Provides a restart strategy to the composite view. This will wipe the progress of the view projections and restart the stream. It is necessary in order to rerun the query in a -possibly- bigger graph

```
{
  "@type": "CompositeView",
  "sources": [ ... ],
  "projections": [ ... ],
  "rebuildStrategy": {
  	"@type": "Interval",
  	"value": "5 days"
  }
}
```

**Comment by wwajerowicz** [comment]
What about letting user specify something like a `cron` expression to schedule restarts?

**Comment by bogdanromanx** [comment]
That would be great to add in the future, but for now I think `Interval` will be sufficient.
