### ISSUE TITLE
Sparql: update editor

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#923]
We need to start using Yasgui, which seems to be what everyone is using: https://github.com/TriplyDB/YASGUI

It has syntax check, multiple tabs, different visualisation (including google charts).

It's great

**Comment by samuel-kerrien** [comment]
Yes indeed, Francois has told us many times but I think it wasn't straight forward to integrate at least las time I heard. Definitely worth looking into it again !
