### ISSUE TITLE
Dashboard query config editor

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#926]
part of https://github.com/BlueBrain/nexus/issues/902

- AS A technical user
- I WANT TO be able to use a SPARQL query editor
- SO I CAN make adjustments to the dashboard config
- GIVEN that I’m in a dashboard edit modal view
- WHEN I edit the SPARQL editor
- THEN it should  provide the sprawl results there
- GIVEN that I’ve made a valid query (there is a _self value?)
- And WHEN I click save
- THEN it should update that query config

**Comment by julienmachon** [comment]
Done as part of #927
