### ISSUE TITLE
Source endpoint of resources with type RemoteDiskStorage contains Nexus internal metadata

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus#938]
When performing a `GET` on the `source` endpoint of a resource of type **RemoteDiskStorage**, the response contains the Nexus internal property `_algorithm`. Subsequently, to be able to update the resource, this property needs to be deleted from the payload, otherwise the following error is returned:

`InvalidResource`
`Resource failed to validate against the constraints defined by 'https://bluebrain.github.io/nexus/schemas/storage.json`

**Comment by umbreak** [comment]
What is the message you get when the `_algorithm` field is added on `RemoteDiskStorage` creation?

**Comment by umbreak** [comment]
Seems to be some problem on the SHACL context we have. I will double check
