### ISSUE TITLE
Add incoming and outgoing

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#94]
From nexus-kg created by [umbreak](https://github.com/umbreak) : BlueBrain/nexus-kg#400  

We have to find a way to add to the Sparql view incoming and outgoing routes which has a similar functionality to `v0` incoming and outgoing. Not sure how this is going to be look like and how it makes sense though...

- /v1/resources/{org}/{project}/{schema}/{id}/incoming
- /v1/resources/{org}/{project}/{schema}/{id}/outgoing

**Comment by umbreak** [comment]
Reuse the queries @kenjinp is using on the frontend side

**Comment by umbreak** [comment]
Incoming query
```
prefix nxv: <https://bluebrain.github.io/nexus/vocabulary/>

SELECT ?total ?s ?p  ?self

WITH {
  SELECT DISTINCT ?s ?p ?self
  WHERE {
    graph ?g1 {
      ?ref ?p <{ID}> .
      ?s nxv:constrainedBy ?aSchema .
      ?s nxv:self ?self
    }
  }
} AS %resultSet
WHERE {
  {
    SELECT (COUNT(?s) AS ?total)
    WHERE { INCLUDE %resultSet }
  }
  UNION
  {
    SELECT *
    WHERE { INCLUDE %resultSet }
    ORDER BY ?s ?p
    LIMIT {size}
    OFFSET {offset}
   }
}
```

KG response
```
{
  "@context": [
      "https://bluebrain.github.io/nexus/contexts/search.json",
      "https://bluebrain.github.io/nexus/contexts/resource.json"
    ],
  "_total": 2,
  "_next": ".../v1/resources/{org}/{project}/{schema}/{id}/incoming?from={from}&size={size}",
  "_results": [
    {
      "@id": "?s",
      "_property": "?p",
      "_self": "?self"
    },
    ...
  ]
}
```

**Comment by umbreak** [comment]
Outgoing query
```
prefix nxv: <https://bluebrain.github.io/nexus/vocabulary/>
SELECT ?total ?o ?p ?self

WITH {
  SELECT DISTINCT ?p ?o ?self WHERE {
    GRAPH <{ID}/graph> {
      ?s ?p ?o
      FILTER(isIri(?o) && ?p NOT IN (nxv:updatedBy, nxv:createdBy, nxv:constrainedBy, nxv:project, rdf:type, nxv:self))
    } .
    OPTIONAL {
      GRAPH ?g2 {
        ?o nxv:constrainedBy ?aSchema .
        ?o nxv:self ?self
        FILTER(?g2 != <{ID}/graph>)
      }
    }
  }
} AS %resultSet


WHERE {
   {
      SELECT (COUNT(?o) AS ?total)
      WHERE { INCLUDE %resultSet }
   }
   UNION
  {
      SELECT *
      WHERE { INCLUDE %resultSet }
      ORDER BY ?o ?p
      LIMIT ${size}
      OFFSET ${from}
   }
}
```

KG response (note that _self might be there or not, depending if the outgoing link is platform managed or not). We could also have a query param to define if we want to include not platform managed resources on the response.
```
{
  "@context": [
      "https://bluebrain.github.io/nexus/contexts/search.json",
      "https://bluebrain.github.io/nexus/contexts/resource.json"
    ],
  "_total": ?total,
  "_next": ".../v1/resources/{org}/{project}/{schema}/{id}/incoming?from={from}&size={size}",
  "_results": [
    {
      "@id": "?o",
      "_property": "?p",
      "_self": "?self"
    },
    ...
  ]
}
```

**Comment by bogdanromanx** [comment]
We can also pull out the types and the schema for these. I think they would be useful. But the query looks good.

**Comment by bogdanromanx** [comment]
For the outgoing I think we should target only managed resources. In the select distinct query we can bound the triples in two graphs g1 and g2 where g1!=g2.

**Comment by umbreak** [comment]
Unmanaged resources are also outgoing links, and @kenjinp has use cases for it. As I pointed out, we could have a query param on outgoing to decide whether or not we want to show also the unmanaged resources.

**Comment by bogdanromanx** [comment]
I think we should go only with managed resources first. I'd like to understand the use cases for providing an API to select all the leaf iris in a graph.

Note: the query as defined right now does not select only the leaf iris but all the iris.

**Comment by bogdanromanx** [comment]
It seems to me that a client should be able to inspect all or leaf iris in a graph without the need to query the sparql endpoint.

**Comment by umbreak** [comment]
Easy example: BrainRegion is an outgoing link which is managed out of nexus.
Other example: Links to resources in v0
Other example: Links to resources which are not yet in v1, but have to be populated.

Linked data lives out of the scope of the nexus world. I think we should offer the possibility to the client to decide whether he/she wants all the outgoing relationships or just the contained on the platform.

**Comment by bogdanromanx** [comment]
What query param do you have in mind?

**Comment by umbreak** [comment]
something like `remoteLinks` or `externalLinks` should be explanatory enough:
- `/v1/resources/{org}/{project}/{schema}/{id}/outgoing?from={from}&size={size}&remoteLinks=true|false`
