### ISSUE TITLE
Allow SPARQL queries to be executed through GET method

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#941]
Currently Nexus only allows the execution of SPARQL queries through POST:
https://bluebrainnexus.io/docs/api/current/kg/kg-views-api.html#sparql-query

The SPARQL specification allows both GET and POST to be used:
https://www.w3.org/TR/sparql11-protocol/#query-operation

Some tools, such as Gruff (https://allegrograph.com/products/gruff/) allow the visualisation of data originating from SPARQL endpoints. It appears they are using a GET to fetch the data, rendering Nexus impossible to query.

**Comment by wwajerowicz** [comment]
Fixed by https://github.com/BlueBrain/nexus-kg/pull/759
