### ISSUE TITLE
Remove uses of `getResourceLabelsAndIdsFromSelf()`

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#944]
It may be inconsistent to derive important values from the nexus address (`_self`) of a resources, especially the `@id`. This is because the `@id` will not be expanded when a base project api mapping is assigned on things like files and resources, so the base url will not be applied to those nexus addresses and the last path won't be the `@id`, but a sort of truncated version, even if fetching by that _not-quite-an-id_ `@id` will still be resolvable. 

Therefore, instead of searching for these values in the nexus address, we should fetch the resource using it and reading the values from the resource payload.

**Comment by julienmachon** [comment]
Nice!

Also, in some cases, the function is called inside a container component that is aware of the `org` and `project` already. So instead of passing the `_self` value as props, why not pass the `@id` value?
