### ISSUE TITLE
Save workspaces to Studio as an array of [{ "@id" }]

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#945]
Right now workspaces are saved to the Studio as a simple array of strings, but should be saved as an array of objects containing an `@id` to be discoverable using the links API. 

There's also a bug where `undefined` will be populated to the workspace array

**Comment by julienmachon** [comment]
If Studio Resources are created using the right context, I don't think this is necessary. I have checked on my side following the doc and it works fine. Plus, this is how nexus-web created studios and there are no linking issues as far as I am concerned?

**Comment by julienmachon** [comment]
The `undefined` stuff is valid though

**Comment by kenjinp** [comment]
Yup the context fixes that problem! I didn't realize
