### ISSUE TITLE
Investigate error report

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#964]
This errors occurs a lot:
https://sentry.io/organizations/blue-brain-project/issues/1385181181/?project=1845930&query=is%3Aunresolved

We need to fix it

**Comment by kenjinp** [comment]
This is caused by the statistics endpoint polling every 3000 ms, but the user does not have access to the project. According to the logs, someone must have left their browser open for up to 21 hours. 

Perhaps we can stop polling the statistics endpoint if the first response is a 401.
