### ISSUE TITLE
Project Page Mini-Refactor

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#979]
Let's simplify the project page. 

A feature sanity check:
- do people use multiple Resource Lists
- do people need more than one Studio per project?

**Comment by kenjinp** [comment]
Possible next tasks:

Refactor Easy Mode: 
- Remove "Add List" button
- Put "Resource" overlay into a column, just like the Studio List

**Comment by adulbrich** [comment]
From users, they do use up to 3 resource lists. Regarding studios, see issue #993

**Comment by adulbrich** [comment]
not necessary at the moment to deliver on studio objectives, postponed
