### ISSUE TITLE
Improve Page not found error in dashboards

### ISSUE THREAD

**Issue by Stafeeva** [BlueBrain/nexus#980]
Currently, when you click on resources in the dashboard table, some of them will redirect you to Page not Found page, which is not very pretty.

![Screenshot 2020-01-14 at 11 41 22](https://user-images.githubusercontent.com/23080476/72359380-774ef100-36ee-11ea-812d-157891eda3a4.png)

**Comment by kenjinp** [comment]
This is because of an error when fetching resources that have a special schema (like files) it should be resolved by https://github.com/BlueBrain/nexus-web/pull/510 I think

**Comment by Stafeeva** [comment]
This issue was solved by BlueBrain/nexus-web#510
