### ISSUE TITLE
Setup Google Tag Manager (GTM)

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#984]
[Quick Start Guide](https://developers.google.com/tag-manager/quickstart)for setting up Google Tag Manager.

We need to set-up the different [environments](https://support.google.com/tagmanager/answer/6311518?hl=en).

Container ID is available in GTM.

- [x] Blue Brain Product Page

- [x] Blue Brain Docs (same container as Product Page)

- [x] Nexus Web

Don't forget the **allow cookies** script!

**Comment by adulbrich** [comment]
Probably need to setup one container on nexus-web in all environments, but also on the nexus product page https://bluebrainnexus.io/. I created a second container for that in GTM.

**Comment by adulbrich** [comment]
Configuring IP anonymization fro Google Analytics at the Tag Manager level: https://www.optimizesmart.com/how-to-turn-on-ip-anonymization-in-google-analytics-and-google-tag-manager/

**Comment by kenjinp** [comment]
GTA PR in product page https://github.com/BlueBrain/nexus/pull/985

**Comment by kenjinp** [comment]
GTM PR for docs https://github.com/BlueBrain/nexus/pull/995

**Comment by kenjinp** [comment]
https://github.com/BlueBrain/nexus-web/pull/527
