### ISSUE TITLE
Add ES support for pagination above 10000 entries

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#99]
From nexus-kg created by [umbreak](https://github.com/umbreak) : BlueBrain/nexus-kg#265  

Right now when `size` + `from` query params. on any search endpoint exceeds 10000 we get an HTTP 500 in ElasticSearch which gets transmitted to the API call site. This is a known limitation on [ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html) using regular pagination.

We should either implement [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) or [search after](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html) or at least signal the error properly on the HTTP response

**Comment by wwajerowicz** [comment]
I think we could use the search_after.

Probably we would have to reintroduce 
`_links` in the listings and have something like this:
```json
{
  "_total": 44,
    "_results": ["..."],
    "_links" : {
       "_next": "https://nexus.example.com/resources/{org}/{proj}/_/?search_after={search_after_param}"
     }
}
```
as  `search_after_param` we could just use the URL encoded JSON array used as "search_after" in ElasticSearch, e.g. URL encoded `[1463538857, "654323"]`.

We should keep the `size` and `from` parameters, but we should return `400 Bad Request` with meaningful error message when the `from` query parameter is higher than 10000.

**Comment by umbreak** [comment]
For simplicity I would just add `_next` and `_previous` at the top level, not in `_links`.

```
{
  "_total": 44,
    "_results": ["..."],
    "_next": "https://nexus.example.com/resources/{org}/{proj}/_/?search_after={search_after_param}"
    "_previous": "https://nexus.example.com/resources/{org}/{proj}/_/?search_after={search_after_param}"
}
```

**Comment by wwajerowicz** [comment]
I thinks keeping it inside `_links` makes more sense since it makes is consistent with HATEOAS/HAL. 

`_previous` link is non-trivial since we would have to keep track of the previous request the user has made before making current request.

**Comment by umbreak** [comment]
we don't do HATEOAS anymore. Before, inside `_links` you will find things like `schema`, `project`, etc. I find it inconsistent to have links for some things and not for others, so I'd rather not have them.

In any case, our approach seems to be correct already (JSON-LD section): https://sookocheff.com/post/api/on-choosing-a-hypermedia-format/
